import test from 'node:test';import assert from 'node:assert/strict';import * as Q from '../src/index.js';import {readFileSync,readdirSync} from 'node:fs';
const graph=()=>{const g=new Q.BidirectionalGraph();g.AddVertexRange(['a','b','c','d','alone']);g.AddEdgeRange([new Q.TaggedEdge('a','b',2),new Q.TaggedEdge('b','c',3),new Q.TaggedEdge('a','c',9),new Q.TaggedEdge('c','d',1)]);return g;};
test('AlgorithmExtensions tree and shortest-path delegates reconstruct edge chains',()=>{for(const name of ['TreeBreadthFirstSearch','TreeDepthFirstSearch','ShortestPathsDijkstra','ShortestPathsBellmanFord','ShortestPathsDag']){const g=graph(),fn=name.startsWith('Tree')?Q[name](g,'a'):Q[name](g,e=>e.Tag,'a');assert.equal(fn('d').at(-1).Target,'d');assert.equal(fn('alone'),undefined);assert.ok(Q.IsPath(fn('d')));}const path=Q.ShortestPathsAStar(graph(),e=>e.Tag,()=>0,'a')('d');assert.equal(path.reduce((n,e)=>n+e.Tag,0),6);});
test('AlgorithmExtensions structural wrappers preserve components and graph reachability',()=>{const g=graph(),components=new Map();assert.equal(Q.WeaklyConnectedComponents(g,components),2);assert.equal(components.size,5);assert.deepEqual(Q.Roots(g),['a','alone']);assert.deepEqual(Q.Sinks(g),['d','alone']);assert.deepEqual(Q.IsolatedVertices(g),['alone']);assert.equal(Q.IsDirectedAcyclicGraph(g),true);assert.equal(Q.ComputeTransitiveClosure(g).EdgeCount,6);assert.equal(Q.ComputeTransitiveReduction(g).EdgeCount,3);assert.equal(Q.CondensateEdges(g,v=>v!=='b').ContainsVertex('b'),false);const out=[];assert.equal(Q.TopologicalSort(g,out),out);assert.equal(out.length,5);g.AddEdge(new Q.Edge('d','a'));assert.equal(Q.IsDirectedAcyclicGraph(g),false);});
test('Graph clone maps object identity and identity delegates are stable',()=>{const original=graph(),copy=new Q.BidirectionalGraph();Q.Clone(original,v=>({name:v}),(e,s,t)=>new Q.TaggedEdge(s,t,e.Tag),copy);assert.equal(copy.VertexCount,5);assert.ok(copy.ContainsVertex([...copy.Edges][0].Source));const ids=Q.GetVertexIdentity(copy),a={},b={};assert.equal(ids(a),ids(a));assert.notEqual(ids(a),ids(b));assert.equal(Q.GetIndexer(new Map([['key',3]]))('key'),3);assert.throws(()=>Q.GetIndexer(new Map())('missing'));});
test('Cryptographic random APIs validate bounds and fill buffers larger than Web Crypto quota',()=>{const random=new Q.CryptoRandom(123),bytes=new Uint8Array(70000);random.NextBytes(bytes);assert.ok(bytes.some(v=>v!==0));assert.equal(random.Next(2,2),2);assert.equal(random.Next(0),0);for(let i=0;i<1000;i++){const n=random.Next(-10,20);assert.ok(n>=-10&&n<20);const f=random.NextDouble();assert.ok(f>=0&&f<1);}assert.throws(()=>random.Next(9,3));assert.throws(()=>random.Next(-1));});
test('Graph equality preserves parallel-edge multiplicity with explicit endpoint comparers',()=>{const a=graph(),b=graph(),vertices=(a,b)=>a===b,edges=(a,b)=>a.Source===b.Source&&a.Target===b.Target;assert.equal(Q.EquateGraphs.Equate(a,b),false);assert.ok(Q.EquateGraphs.Equate(a,b,vertices,edges));b.AddEdge(new Q.Edge('a','b'));assert.equal(Q.EquateGraphs.Equate(a,b,vertices,edges),false);});

function make(pairs=[],Type=Q.BidirectionalGraph,vertices=[]){const g=new Type();g.AddVertexRange(vertices);g.AddVerticesAndEdgeRange(pairs.map(([a,b,w])=>w===undefined?new Q.Edge(a,b):new Q.TaggedEdge(a,b,w)));return g;}
function nullVariants(fn,args,indexes=args.map((_,i)=>i)){for(let mask=1;mask<1<<indexes.length;++mask){const parameters=args.slice();for(let i=0;i<indexes.length;++i)if(mask>>i&1)parameters[indexes[i]]=null;assert.throws(()=>fn(...parameters),`${fn.name} null mask ${mask}`);}}
const endpoints=path=>path?.map(e=>[e.Source,e.Target]);

// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::GetIndexer
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::GetIndexer_Throws
test('GetIndexer retains live dictionary lookup and identity keys',()=>{const d=new Map(),get=Q.GetIndexer(d);assert.throws(()=>get(12));d.set(12,42);assert.equal(get(12),42);const a={value:1},b={value:1},v={value:2};d.set(a,v);assert.equal(get(a),v);assert.throws(()=>get(b));d.set('undefined',undefined);assert.equal(get('undefined'),undefined);assert.throws(()=>Q.GetIndexer(null));const o=Object.create(null);o['__proto__']=7;assert.equal(Q.GetIndexer(o)('__proto__'),7);});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::GetVertexIdentity
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::GetVertexIdentity_Throws
test('Vertex identities retain primitive spelling, object identity and mixed-type uniqueness',()=>{const ids=Q.GetVertexIdentity(make());assert.equal(ids(12),'12');assert.equal(ids(42),'42');assert.equal(ids(12),'12');assert.equal(ids(true),'True');assert.equal(ids(false),'False');const a={},b={},objects=Q.GetVertexIdentity(make([],Q.AdjacencyGraph,[a,b]));assert.equal(objects(a),'0');assert.equal(objects(b),'1');assert.equal(objects(a),'0');const mixed=make([],Q.AdjacencyGraph,[1,'1',true,'True',{},Symbol('1')]),mixedId=Q.GetVertexIdentity(mixed);assert.equal(new Set([...mixed.Vertices].map(mixedId)).size,mixed.VertexCount);const fresh=Q.GetVertexIdentity(make());const values=[0,'0',1,'1',{},false,'False',NaN,'NaN',Symbol('0')];assert.equal(new Set(values.map(fresh)).size,values.length);assert.throws(()=>Q.GetVertexIdentity(null));assert.throws(()=>ids(null));});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::GetEdgeIdentity
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::GetEdgeIdentity_Throws
test('Edge identities respect reference edges and equatable edges',()=>{const id=Q.GetEdgeIdentity(make()),a=new Q.Edge(1,2),b=new Q.Edge(2,3),c=new Q.Edge(1,2);assert.deepEqual([id(a),id(b),id(c),id(a)],['0','1','2','0']);const valueId=Q.GetEdgeIdentity(make());assert.equal(valueId(new Q.SEquatableEdge(1,2)),valueId(new Q.SEquatableEdge(1,2)));assert.throws(()=>Q.GetEdgeIdentity(null));assert.throws(()=>id(null));});

// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::TreeBreadthFirstSearch
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::TreeDepthFirstSearch
test('BFS and DFS wrappers reproduce original fixture paths and detach recorders',()=>{const g=make([[1,2],[1,3],[2,3],[2,4],[3,5],[3,6]],Q.AdjacencyGraph,[7]);const bfs=Q.TreeBreadthFirstSearch(g,1),dfs=Q.TreeDepthFirstSearch(g,1);assert.deepEqual(endpoints(bfs(5)),[[1,3],[3,5]]);assert.deepEqual(endpoints(dfs(5)),[[1,2],[2,3],[3,5]]);assert.equal(bfs(7),undefined);assert.equal(dfs(7),undefined);assert.equal(bfs.algorithm.TreeEdge.Count,0);assert.equal(dfs.algorithm.TreeEdge.Count,0);});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::TreeBreadthFirstSearch_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::TreeDepthFirstSearch_Throws
test('Tree wrappers validate graph/root combinations',()=>{for(const fn of [Q.TreeBreadthFirstSearch,Q.TreeDepthFirstSearch]){nullVariants(fn,[make([[1,2]]),1]);assert.throws(()=>fn(make([[1,2]]),3));}});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::TreeCyclePoppingRandom
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::TreeCyclePoppingRandom_Throws
test('Cycle-popping wrapper invokes optional chain and handles isolated vertex',()=>{const g=make([[1,2],[1,3],[2,1],[2,3],[2,4],[3,2],[3,5],[3,6],[4,1],[4,2],[4,5],[4,6],[5,6],[6,2],[6,3]],Q.AdjacencyGraph,[7]);assert.equal(Q.TreeCyclePoppingRandom(g,2)(7),undefined);const chain=new Q.NormalizedMarkovEdgeChain();assert.equal(Q.TreeCyclePoppingRandom(g,2,chain)(7),undefined);nullVariants(Q.TreeCyclePoppingRandom,[g,2,chain]);});

// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ShortestPaths_Dijkstra_AStar_BellmanFord_Dag
test('Four shortest-path wrappers reproduce upstream directed paths',()=>{const g=make([[1,2],[1,3],[1,8],[2,4],[2,5],[2,6],[3,4],[4,5],[4,6],[5,6],[6,7],[8,10],[9,5],[10,9]],Q.AdjacencyGraph);for(const result of [Q.ShortestPathsDijkstra(g,()=>1,2),Q.ShortestPathsAStar(g,()=>1,()=>1,2),Q.ShortestPathsBellmanFord(g,()=>1,2),Q.ShortestPathsDag(g,()=>1,2)]){assert.equal(result(1),undefined);assert.deepEqual(endpoints(result(7)),[[2,6],[6,7]]);assert.deepEqual(endpoints(result(4)),[[2,4]]);}});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ShortestPaths_BellmanFord_NegativeCycle
test('Bellman-Ford wrapper exposes negative-cycle out flag without looping in path access',()=>{const g=make([[1,2,12],[2,4,-42],[4,1,22]]),result=Q.ShortestPathsBellmanFord(g,e=>e.Tag,1);assert.equal(result.hasNegativeCycle,true);assert.throws(()=>result(4),{name:'InvalidOperationException'});});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ShortestPathsDijkstra_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ShortestPathsAStar_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ShortestPathsBellmanFord_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ShortestPathsDag_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ShortestPathsUndirectedDijkstra_Throws
test('Shortest-path wrappers validate every required null combination',()=>{for(const Type of [Q.AdjacencyGraph,Q.UndirectedGraph])nullVariants(Q.ShortestPathsDijkstra,[make([[1,2]],Type),()=>1,1]);for(const fn of [Q.ShortestPathsBellmanFord,Q.ShortestPathsDag])nullVariants(fn,[make([[1,2]]),()=>1,1]);nullVariants(Q.ShortestPathsAStar,[make([[1,2]]),()=>1,()=>0,1]);});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ShortestPaths_UndirectedDijkstra
test('Undirected Dijkstra wrapper follows reversed original edge orientation',()=>{const g=make([[1,2],[1,3],[1,8],[4,5],[4,6],[5,6],[6,7],[8,10]],Q.UndirectedGraph,[9]),get=Q.ShortestPathsDijkstra(g,()=>1,2);assert.equal(get(9),undefined);assert.deepEqual(endpoints(get(8)),[[1,2],[1,8]]);assert.deepEqual(endpoints(get(1)),[[1,2]]);});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::RankedShortestPathHoffmanPavley
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::RankedShortestPathHoffmanPavley_Throws
test('Ranked wrapper routes maxCount and returns original simple paths',()=>{const g=make([[1,2],[1,3],[1,8],[2,1],[2,4],[2,5],[2,6],[3,3],[3,4],[4,5],[4,6],[5,6],[6,7],[8,10],[9,5],[10,9]]),paths=Q.RankedShortestPathHoffmanPavley(g,()=>1,1,5,5);assert.equal(paths.length,4);assert.deepEqual(paths.map(p=>p.length),[2,3,3,4]);assert.deepEqual(new Set(paths.map(p=>JSON.stringify(endpoints(p)))),new Set([[[1,2],[2,5]],[[1,3],[3,4],[4,5]],[[1,2],[2,4],[4,5]],[[1,8],[8,10],[10,9],[9,5]]].map(JSON.stringify)));assert.equal(Q.RankedShortestPathHoffmanPavley(g,()=>1,1,5).length,3);nullVariants(Q.RankedShortestPathHoffmanPavley,[g,()=>1,1,5,5],[0,1,2,3]);for(const n of [-1,0,1])assert.throws(()=>Q.RankedShortestPathHoffmanPavley(g,()=>1,1,5,n));});

// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::Sinks
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::Roots_NotBidirectional
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::Roots_Bidirectional
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::IsolatedVertices
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::OddVertices
test('Root/sink/isolated/odd wrappers reproduce graph-query fixtures',()=>{const fixtures=[[[],[],[]],[[[1,2],[2,4],[4,1]],[],[]],[[[1,2],[2,4],[2,5],[3,5],[4,1],[2,2]],[3],[5]],[[[2,2]],[],[]],[[[1,2],[1,4],[2,3],[2,4],[3,5],[4,5]],[1],[5]],[[[1,2],[1,4],[2,4],[3,5],[4,5],[4,6]],[1,3],[5,6]]];for(const Type of [Q.AdjacencyGraph,Q.BidirectionalGraph])for(const [pairs,roots,sinks]of fixtures){const g=make(pairs,Type);assert.deepEqual(new Set(Q.Roots(g)),new Set(roots));assert.deepEqual(new Set(Q.Sinks(g)),new Set(sinks));g.AddVertex(99);assert.deepEqual(Q.IsolatedVertices(g),[99]);const counts=new Map([...g.Vertices].map(v=>[v,0]));for(const e of g.Edges){counts.set(e.Source,counts.get(e.Source)+1);counts.set(e.Target,counts.get(e.Target)+1);}assert.deepEqual(new Set(Q.OddVertices(g)),new Set([...counts].filter(([,n])=>n%2).map(([v])=>v)));}assert.deepEqual(Q.OddVertices(make([[NaN,NaN]],Q.UndirectedGraph)),[]);});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::Sinks_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::Roots_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::IsolatedVertices_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::OddVertices_Throws
test('Graph-query wrappers reject null graphs',()=>{for(const fn of [Q.Sinks,Q.Roots,Q.IsolatedVertices,Q.OddVertices])assert.throws(()=>fn(null));});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::AdjacencyGraphRoots
test('Root wrapper checks all original graph fixtures',()=>{const dir=new URL('./fixtures/GraphML/',import.meta.url);for(const filename of readdirSync(dir).filter(n=>/^g\.\d+\.\d+\.graphml$/.test(n))){const xml=readFileSync(new URL(filename,dir),'utf8'),vs=[...xml.matchAll(/<node\b[^>]*\bid="([^"]+)"/g)].map(m=>m[1]),pairs=[...xml.matchAll(/<edge\b[^>]*\bsource="([^"]+)"[^>]*\btarget="([^"]+)"/g)].map(m=>[m[1],m[2]]),g=make(pairs,Q.AdjacencyGraph,vs),roots=new Set(Q.Roots(g));for(const [,target]of pairs)assert.equal(roots.has(target),false);}});

// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::TopologicalSort
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::SourceFirstTopologicalSort
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::SourceFirstBidirectionalTopologicalSort
test('Topological wrappers reproduce forward and backward upstream order',()=>{const g=make([[1,2],[2,4],[3,1],[3,5],[5,7],[6,3],[6,7]]);assert.deepEqual(Q.TopologicalSort(g),[6,3,5,7,1,2,4]);assert.deepEqual(Q.SourceFirstTopologicalSort(g),[6,3,1,5,2,7,4]);assert.deepEqual(Q.SourceFirstBidirectionalTopologicalSort(g),[6,3,1,5,2,7,4]);assert.deepEqual(Q.SourceFirstBidirectionalTopologicalSort(g,Q.TopologicalSortDirection.Backward),[4,7,2,5,1,3,6]);const output=[];assert.equal(Q.SourceFirstBidirectionalTopologicalSort(g,output),output);assert.equal(output.length,7);});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::TopologicalSort_Undirected
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::SourceFirstTopologicalSort_Undirected
test('Topological wrappers dispatch to undirected algorithms',()=>{const g=make([[1,2],[2,4],[3,1],[3,5],[5,7],[6,7]],Q.UndirectedGraph);assert.deepEqual(Q.TopologicalSort(g),[1,3,5,7,6,2,4]);assert.deepEqual(Q.SourceFirstTopologicalSort(g),[4,6,2,7,1,5,3]);});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::TopologicalSort_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::SourceFirstTopologicalSort_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::SourceFirstBidirectionalTopologicalSort_Throws
test('Topological wrappers reject null graphs',()=>{for(const fn of [Q.TopologicalSort,Q.SourceFirstTopologicalSort,Q.SourceFirstBidirectionalTopologicalSort])assert.throws(()=>fn(null));});

// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ConnectedComponents
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::StronglyConnectedComponents
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::WeaklyConnectedComponents
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ConnectedComponents_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::StronglyConnectedComponents_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::WeaklyConnectedComponents_Throws
test('Component wrappers populate the caller dictionary and return a count',()=>{for(const [fn,Type,expected]of [[Q.ConnectedComponents,Q.UndirectedGraph,3],[Q.WeaklyConnectedComponents,Q.AdjacencyGraph,3],[Q.StronglyConnectedComponents,Q.AdjacencyGraph,5]]){const g=make([[1,2],[2,3],[3,1],[3,4],[5,6]],Type,[7]),map=new Map([['stale',100]]);assert.equal(fn(g,map),expected);assert.equal(map.size,7);assert.equal(map.has('stale'),false);assert.equal(map.get(1),map.get(3));nullVariants(fn,[g,map]);}});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::IncrementalConnectedComponent
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::IncrementalConnectedComponent_Throws
test('Incremental wrapper returns a disposable live component reader',()=>{const g=make([],Q.AdjacencyGraph,[0,1,2,3]),reader=Q.IncrementalConnectedComponents(g);assert.equal(reader.GetComponents().Key,4);g.AddEdge(new Q.Edge(0,1));assert.equal(reader.GetComponents().Key,3);g.AddEdge(new Q.Edge(2,3));assert.equal(reader.GetComponents().Key,2);g.AddEdge(new Q.Edge(1,3));assert.equal(reader.GetComponents().Key,1);g.AddVertex(4);assert.equal(reader.GetComponents().Key,2);reader.Dispose();assert.equal(g.EdgeAdded.Count,0);assert.throws(()=>Q.IncrementalConnectedComponents(null));});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::StronglyCondensedGraph_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::WeaklyCondensedGraph_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::EdgesCondensedGraph_Throws
test('Condensation wrappers return graphs and route graph factories/predicates',()=>{const g=make([[1,2],[2,1],[2,3],[3,4]]);assert.equal(Q.CondensateStronglyConnected(g).VertexCount,3);assert.equal(Q.CondensateWeaklyConnected(g).VertexCount,1);const c=Q.CondensateStronglyConnected(g,()=>new Q.AdjacencyGraph());for(const v of c.Vertices)assert.ok(v instanceof Q.AdjacencyGraph);const merged=Q.CondensateEdges(g,v=>v!==3);assert.equal(merged.ContainsVertex(3),false);assert.equal(merged.ContainsEdge(2,4),true);for(const fn of [Q.CondensateStronglyConnected,Q.CondensateWeaklyConnected,Q.CondensateEdges])assert.throws(()=>fn(null));assert.throws(()=>Q.CondensateEdges(g,null));});

// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::IsDirectedAcyclicGraph
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::IsDirectedAcyclicGraph_FromEdges
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::IsDirectedAcyclicGraph_Throws
test('Directed acyclicity wrapper supports graph and iterable overloads',()=>{const fixtures=[[[],true],[[[1,2],[1,4],[2,3],[2,4]],true],[[[1,2],[1,4],[2,3],[5,6]],true],[[[2,2]],false],[[[1,2],[1,4],[2,2],[2,3],[2,4]],false],[[[1,2],[1,4],[2,3],[2,4],[4,1]],false],[[[1,2],[1,3],[2,3],[3,1],[3,4],[4,4]],false],[[[1,6],[2,3],[2,5],[3,4],[3,5],[5,2]],false]];for(const Type of [Q.AdjacencyGraph,Q.BidirectionalGraph])for(const [pairs,result]of fixtures){const g=make(pairs,Type,[0]);assert.equal(Q.IsDirectedAcyclicGraph(g),result);assert.equal(Q.IsDirectedAcyclicGraph(g.Edges),result);assert.equal(Q.IsDirectedAcyclicGraph((function*(){yield* g.Edges;})()),result);}assert.throws(()=>Q.IsDirectedAcyclicGraph(null));assert.throws(()=>Q.IsDirectedAcyclicGraph([new Q.Edge(1,2),null]));});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::IsUndirectedAcyclicGraph
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::IsUndirectedAcyclicGraph_FromEdges
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::IsUndirectedAcyclicGraph_Throws
test('Undirected acyclicity handles forests, edge iterables, parallel edges and NaN',()=>{const fixtures=[[[],true],[[[1,2],[2,3],[2,4]],true],[[[1,2],[1,4],[2,3],[5,6]],true],[[[2,2]],false],[[[1,2],[1,4],[2,2],[2,3],[2,4]],false],[[[1,2],[1,4],[2,3],[2,4]],false],[[[1,6],[2,3],[2,5],[3,5]],false],[[[1,2],[1,2]],false],[[[NaN,1]],true],[[[NaN,NaN]],false]];for(const [pairs,result]of fixtures){const g=make(pairs,Q.UndirectedGraph,[0]);assert.equal(Q.IsUndirectedAcyclicGraph(g),result);assert.equal(Q.IsUndirectedAcyclicGraph(g.Edges),result);}assert.throws(()=>Q.IsUndirectedAcyclicGraph(null));assert.throws(()=>Q.IsUndirectedAcyclicGraph([new Q.Edge(1,2),null]));});

// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ComputePredecessorCost
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ComputePredecessorCost_Throws
test('Predecessor-cost wrapper accepts cost dictionaries and detects cyclic misuse',()=>{const predecessors=new Map(),costs=new Map();assert.equal(Q.ComputePredecessorCost(predecessors,costs,1),0);const e12=new Q.Edge(1,2),e31=new Q.Edge(3,1),e34=new Q.Edge(3,4);predecessors.set(2,e12);costs.set(e12,12);assert.equal(Q.ComputePredecessorCost(predecessors,costs,2),12);predecessors.set(1,e31);predecessors.set(4,e34);costs.set(e31,-5);costs.set(e34,42);assert.deepEqual([1,2,3,4].map(v=>Q.ComputePredecessorCost(predecessors,costs,v)),[-5,7,0,42]);nullVariants(Q.ComputePredecessorCost,[predecessors,costs,1]);assert.throws(()=>Q.ComputePredecessorCost(predecessors,new Map(),2));assert.throws(()=>Q.ComputePredecessorCost(new Map([[NaN,new Q.Edge(NaN,NaN)]]),()=>1,NaN));});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ComputeDisjointSet
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::ComputeDisjointSet_Throws
test('Disjoint-set wrapper returns all vertices and connected partitions',()=>{const g=make([[0,1],[2,3]],Q.UndirectedGraph,[4,NaN]),set=Q.ComputeDisjointSet(g);assert.equal(set.SetCount,4);assert.equal(set.ElementCount,6);assert.equal(set.AreInSameSet(0,1),true);assert.equal(set.AreInSameSet(1,2),false);assert.equal(set.AreInSameSet(NaN,NaN),true);assert.throws(()=>Q.ComputeDisjointSet(null));});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::MinimumSpanningTreePrim_Throws
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::MinimumSpanningTreeKruskal_Throws
test('MST wrappers return edges for the minimum forest and reject missing weights',()=>{const g=make([[1,2,5],[1,3,1],[2,3,2],[4,5,-1]],Q.UndirectedGraph,[6]);for(const fn of [Q.MinimumSpanningTreePrim,Q.MinimumSpanningTreeKruskal]){assert.equal(fn(g,e=>e.Tag).reduce((s,e)=>s+e.Tag,0),2);nullVariants(fn,[g,()=>1]);}});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::OfflineLeastCommonAncestor_Throws
test('Offline LCA wrapper returns pair lookups including NaN and validates endpoints',()=>{const g=make([[NaN,1],[NaN,2],[1,3]]),pair=new Q.SEquatableEdge(3,2),get=Q.OfflineLeastCommonAncestor(g,NaN,[pair]);assert.ok(Number.isNaN(get(new Q.SEquatableEdge(3,2))));assert.equal(get(new Q.SEquatableEdge(1,2)),undefined);nullVariants(Q.OfflineLeastCommonAncestor,[g,NaN,[pair]]);assert.throws(()=>Q.OfflineLeastCommonAncestor(g,NaN,[]));assert.throws(()=>Q.OfflineLeastCommonAncestor(g,NaN,[new Q.Edge(3,4)]));});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::MaximumFlow_Throws
test('Maximum-flow wrapper returns value/predecessor out data and validates augmentors',()=>{const g=make([[0,1,3],[0,2,2],[1,2,1],[1,3,2],[2,3,3]]),flow=Q.MaximumFlow(g,e=>e.Tag,0,3);assert.equal(flow.value,5);assert.equal(typeof flow.predecessors,'function');assert.equal(flow.algorithm.MaxFlow,5);assert.throws(()=>Q.MaximumFlow(g,()=>1,0,0));assert.throws(()=>Q.MaximumFlow(g,()=>1,NaN,NaN));const factory=(a,b)=>new Q.Edge(a,b),augmentor=new Q.ReversedEdgeAugmentorAlgorithm(g,factory);assert.throws(()=>Q.MaximumFlow(g,()=>1,0,3,factory,augmentor));nullVariants(Q.MaximumFlow,[g,()=>1,0,3,factory],[0,1,2,3,4]);assert.throws(()=>Q.MaximumFlow(g,()=>1,0,3,factory,null));});
test('Transitive convenience wrappers preserve vertices, edges and edge factory results',()=>{const g=make([[1,2],[2,3]],Q.AdjacencyGraph,[4]),closure=Q.ComputeTransitiveClosure(g,(a,b)=>new Q.TaggedEdge(a,b,'derived'));assert.equal(closure.VertexCount,4);assert.equal(closure.EdgeCount,3);assert.equal(closure.TryGetEdge(1,3).Tag,'derived');assert.equal(Q.ComputeTransitiveReduction(closure).EdgeCount,2);assert.throws(()=>Q.ComputeTransitiveClosure(g,null));assert.throws(()=>Q.ComputeTransitiveClosure(null));assert.throws(()=>Q.ComputeTransitiveReduction(null));});
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::Clone
// Upstream: tests/QuikGraph.Tests/Extensions/AlgorithmExtensionsTests.cs::Clone_Throws
test('Clone wrapper clears destinations, remaps edge endpoints and validates every argument',()=>{const original=make([[1,2],[2,2],[2,3],[3,1]],Q.AdjacencyGraph),cloneVertex=v=>({value:v}),cloneEdge=(e,s,t)=>new Q.Edge(s,t);for(const Type of [Q.AdjacencyGraph,Q.BidirectionalGraph]){const target=make([[1,4]],Type);Q.Clone(original,cloneVertex,cloneEdge,target);assert.equal(target.VertexCount,3);assert.equal(target.EdgeCount,4);for(const e of target.Edges){assert.equal(target.ContainsVertex(e.Source),true);assert.equal(target.ContainsVertex(e.Target),true);}Q.Clone(make(),v=>v,(e,s,t)=>new Q.Edge(s,t),target);assert.equal(target.VertexCount,0);}nullVariants(Q.Clone,[original,cloneVertex,cloneEdge,new Q.AdjacencyGraph()]);assert.throws(()=>Q.Clone(original,()=>null,cloneEdge,new Q.AdjacencyGraph()));assert.throws(()=>Q.Clone(original,cloneVertex,()=>null,new Q.AdjacencyGraph()));assert.throws(()=>Q.Clone(original,v=>v,e=>e,original));});

// Upstream: tests/QuikGraph.Tests/Misc/CryptoRandomTests.cs::Constructor
// Upstream: tests/QuikGraph.Tests/Misc/CryptoRandomTests.cs::Next
// Upstream: tests/QuikGraph.Tests/Misc/CryptoRandomTests.cs::NextWithMax
// Upstream: tests/QuikGraph.Tests/Misc/CryptoRandomTests.cs::NextWithMax_Throws
// Upstream: tests/QuikGraph.Tests/Misc/CryptoRandomTests.cs::NextWithMinMax
// Upstream: tests/QuikGraph.Tests/Misc/CryptoRandomTests.cs::NextWithMinMax_Throws
// Upstream: tests/QuikGraph.Tests/Misc/CryptoRandomTests.cs::NextDouble
// Upstream: tests/QuikGraph.Tests/Misc/CryptoRandomTests.cs::NextBytes
// Upstream: tests/QuikGraph.Tests/Misc/CryptoRandomTests.cs::NextBytes_Throws
test('CryptoRandom original constructor, Int32 bounds and byte-array cases',()=>{for(const random of [new Q.CryptoRandom(),new Q.CryptoRandom(123456)]){for(const [min,max]of [[-2147483648,2147483647],[10,2147483647],[-2147483648,10],[-10,10],[-10,0],[-10,-1]])for(let i=0;i<20;++i){const n=random.Next(min,max);assert.ok(n>=min&&n<max);}assert.equal(random.Next(10,10),10);assert.equal(random.Next(0),0);assert.ok(random.Next()>=0);assert.ok(random.Next(10)<10);assert.ok(random.NextDouble()<1);for(const values of [[-1],[-12],[10,9],[10,-9],[-10,-11]])assert.throws(()=>random.Next(...values));const bytes=Array(5).fill(0);random.NextBytes(bytes);assert.ok(bytes.every(v=>Number.isInteger(v)&&v>=0&&v<256));assert.throws(()=>random.NextBytes(null));}});
test('HashCodeHelpers uses upstream little-endian bytewise FNV-1',()=>{for(const [values,expected]of [[[0,0],-1679724187],[[1,2],-373379628],[[-1,2147483647],905105677],[[-2147483648,0,42],1091733735],[[1,2,3,4],1724866073]])assert.equal(Q.HashCodeHelpers.Combine(...values),expected);assert.throws(()=>Q.HashCodeHelpers.Combine(1));assert.throws(()=>Q.HashCodeHelpers.Combine(1,2,3,4,5));});
test('Enumerable and try-function helpers preserve values and null-result semantics',()=>{const found=[];Q.EnumerableHelpers.ForEach((function*(){yield 0;yield null;yield 'a';})(),v=>found.push(v));assert.deepEqual(found,[0,null,'a']);const fn=Q.QuikGraphHelpers.ToTryFunc(v=>v);assert.equal(fn(null),undefined);assert.equal(fn(false),false);assert.equal(fn(0),0);assert.throws(()=>Q.QuikGraphHelpers.ToTryFunc(null));});
// Upstream: tests/QuikGraph.Tests/Graphs/EquatableGraphTests.cs::EquateWithComparer
// Upstream: tests/QuikGraph.Tests/Graphs/EquatableGraphTests.cs::EquateWithComparer_Throws
// Upstream: tests/QuikGraph.Tests/Graphs/EquatableGraphTests.cs::Equate
// Upstream: tests/QuikGraph.Tests/Graphs/EquatableGraphTests.cs::EquateReversedGraph
// Upstream: tests/QuikGraph.Tests/Graphs/EquatableGraphTests.cs::EquateCompressedGraph
test('Graph equality supports null graphs, reference edges and explicit comparer objects',()=>{assert.equal(Q.EquateGraphs.Equate(null,null),true);assert.equal(Q.EquateGraphs.Equate(make(),null),false);assert.equal(Q.EquateGraphs.Equate(null,make()),false);const g=make([[1,2]]),same=make();same.AddVertexRange(g.Vertices);same.AddEdgeRange(g.Edges);assert.equal(Q.EquateGraphs.Equate(g,same),true);const other=make([[1,2]]);assert.equal(Q.EquateGraphs.Equate(g,other),false);const vertexComparer={Equals:(a,b)=>a===b},edgeComparer={Equals:(a,b)=>a.Source===b.Source&&a.Target===b.Target};assert.equal(Q.EquateGraphs.Equate(g,other,vertexComparer,edgeComparer),true);assert.equal(Q.EquateGraphs.Equate(g,make([[1,2]],Q.UndirectedGraph),vertexComparer,edgeComparer),false);nullVariants(Q.EquateGraphs.Equate,[g,other,vertexComparer,edgeComparer],[2,3]);const a=make(),b=make();a.AddVerticesAndEdge(new Q.EquatableEdge(1,2));b.AddVerticesAndEdge(new Q.EquatableEdge(1,2));assert.equal(Q.EquateGraphs.Equate(a,b),true);const compressed=new Q.ArrayAdjacencyGraph(g);assert.equal(Q.EquateGraphs.Equate(g,compressed),true);const r1=new Q.ReversedBidirectionalGraph(g),r2=new Q.ReversedBidirectionalGraph(other);assert.equal(Q.EquateGraphs.Equate(r1,r2,vertexComparer,edgeComparer),true);});
