import test from 'node:test';
import assert from 'node:assert/strict';
import * as G from '../src/graphviz.js';
import { AdjacencyGraph,UndirectedGraph,Edge } from '../src/core.js';

// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizVertexTests.cs::ToDot
{
let vertex = new G.GraphvizVertex();
{ const value=vertex, expected=""; test("GraphvizVertexTests.ToDot fixture 1",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Label:"Test Vertex"});
{ const value=vertex, expected="label=\"Test Vertex\""; test("GraphvizVertexTests.ToDot fixture 2",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Shape:G.GraphvizVertexShape.DoubleCircle,Style:G.GraphvizVertexStyle.Filled,FillColor:G.GraphvizColor.Blue});
{ const value=vertex, expected="shape=doublecircle, style=filled, fillcolor=\"#0000FFFF\""; test("GraphvizVertexTests.ToDot fixture 3",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Label:"<b>Bold</b> text"});
{ const value=vertex, expected="label=\"<b>Bold</b> text\""; test("GraphvizVertexTests.ToDot fixture 4",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{IsHtmlLabel:true,Label:"<b>Bold</b> text"});
{ const value=vertex, expected="label=<<b>Bold</b> text>"; test("GraphvizVertexTests.ToDot fixture 5",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Position:new G.GraphvizPoint(10,-20),Comment:"Test comment",Label:"Test label",ToolTip:"Test tooltip",Url:"https://test.com",FillColor:G.GraphvizColor.Red,Font:new G.GraphvizFont("Test font",12.0),FontColor:G.GraphvizColor.Green,PenWidth:2.0,Group:"Test group",Layer:new G.GraphvizLayer("Vertex Layer"),Orientation:12,Peripheries:1,Regular:true,Shape:G.GraphvizVertexShape.Diamond,StrokeColor:G.GraphvizColor.Azure,Style:G.GraphvizVertexStyle.Dashed,Z:100});
{ const value=vertex, expected="fontname=\"Test font\", fontsize=12, fontcolor=\"#008000FF\", penwidth=2, tooltip=\"Test tooltip\", " + "comment=\"Test comment\", URL=\"https://test.com\", shape=diamond, label=\"Test label\", " + "style=dashed, color=\"#F0FFFFFF\", fillcolor=\"#FF0000FF\", orientation=12, regular=true, " + "group=\"Test group\", layer=\"Vertex Layer\", peripheries=1, " + "z=100, pos=\"10,-20!\""; test("GraphvizVertexTests.ToDot fixture 6",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{FixedSize:false,Size:new G.GraphvizSizeF(10.0,15.0)});
{ const value=vertex, expected=""; test("GraphvizVertexTests.ToDot fixture 7",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{FixedSize:true,Size:new G.GraphvizSizeF(10.0,15.0)});
{ const value=vertex, expected="fixedsize=true, height=15, width=10"; test("GraphvizVertexTests.ToDot fixture 8",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{FixedSize:true,Size:new G.GraphvizSizeF(0.0,15.0)});
{ const value=vertex, expected="fixedsize=true, height=15"; test("GraphvizVertexTests.ToDot fixture 9",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{FixedSize:true,Size:new G.GraphvizSizeF(10.0,0.0)});
{ const value=vertex, expected="fixedsize=true, width=10"; test("GraphvizVertexTests.ToDot fixture 10",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Shape:G.GraphvizVertexShape.Box,Sides:8,Skew:2.0,Distortion:2.0});
{ const value=vertex, expected="shape=box"; test("GraphvizVertexTests.ToDot fixture 11",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Shape:G.GraphvizVertexShape.Polygon,Sides:8,Skew:2.0,Distortion:2.0});
{ const value=vertex, expected="shape=polygon, sides=8, skew=2, distortion=2"; test("GraphvizVertexTests.ToDot fixture 12",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Shape:G.GraphvizVertexShape.Polygon,Skew:2.0,Distortion:2.0});
{ const value=vertex, expected="shape=polygon, sides=4, skew=2, distortion=2"; test("GraphvizVertexTests.ToDot fixture 13",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Shape:G.GraphvizVertexShape.Polygon,Sides:0,Skew:2.0,Distortion:2.0});
{ const value=vertex, expected="shape=polygon, skew=2, distortion=2"; test("GraphvizVertexTests.ToDot fixture 14",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Shape:G.GraphvizVertexShape.Polygon,Sides:8,Distortion:2.0});
{ const value=vertex, expected="shape=polygon, sides=8, distortion=2"; test("GraphvizVertexTests.ToDot fixture 15",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Shape:G.GraphvizVertexShape.Polygon,Sides:8,Skew:2.0});
{ const value=vertex, expected="shape=polygon, sides=8, skew=2"; test("GraphvizVertexTests.ToDot fixture 16",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Shape:G.GraphvizVertexShape.Rectangle,Label:"Test label",Record:Object.assign(new G.GraphvizRecord(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Text:"Test Cell"})])})});
{ const value=vertex, expected="shape=rectangle, label=\"Test label\""; test("GraphvizVertexTests.ToDot fixture 17",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Shape:G.GraphvizVertexShape.Record,Label:"Test label",Record:Object.assign(new G.GraphvizRecord(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Text:"Test Cell"})])})});
{ const value=vertex, expected="shape=record, label=\"Test label\""; test("GraphvizVertexTests.ToDot fixture 18",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Shape:G.GraphvizVertexShape.Record,Label:"Start\\ Cell | { <Port_A> a | b | c }",Record:Object.assign(new G.GraphvizRecord(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Text:"Test Cell"})])})});
{ const value=vertex, expected="shape=record, label=\"Start\\ Cell | { <Port_A> a | b | c }\""; test("GraphvizVertexTests.ToDot fixture 19",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Shape:G.GraphvizVertexShape.Record,Record:Object.assign(new G.GraphvizRecord(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Text:"Test Cell1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"Test Port2",Text:"Test Cell2"}),Object.assign(new G.GraphvizRecordCell(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"Sub Test Port1",Text:"Sub Test Cell1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"Sub Test Port2",Text:"Sub Test Cell2"})])})])})});
{ const value=vertex, expected="shape=record, label=\"Test\\ Cell1 | <Test_Port2> Test\\ Cell2 | { <Sub_Test_Port1> Sub\\ Test\\ Cell1 | <Sub_Test_Port2> Sub\\ Test\\ Cell2 }\""; test("GraphvizVertexTests.ToDot fixture 20",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{Comment:"\"The Comment\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪",Label:"\"The Label\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪",ToolTip:"\"The Tooltip\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪"});
{ const value=vertex, expected="tooltip=\"\\\"The Tooltip\\\"\\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\\\[]() Content ∴∞⇐ℜΩ÷嗷娪\", " + "comment=\"\\\"The Comment\\\"\\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\\\[]() Content ∴∞⇐ℜΩ÷嗷娪\", " + "label=\"\\\"The Label\\\"\\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\\\[]() Content ∴∞⇐ℜΩ÷嗷娪\""; test("GraphvizVertexTests.ToDot fixture 21",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
vertex = Object.assign(new G.GraphvizVertex(),{IsHtmlLabel:true,Label:"<i>\"The Label\"</i>\n &amp;/&lt;&gt;@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪"});
{ const value=vertex, expected="label=<<i>\"The Label\"</i>" + "\n" + " &amp;/&lt;&gt;@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪>"; test("GraphvizVertexTests.ToDot fixture 22",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
}

// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeTests.cs::ToDot
{
let edge = new G.GraphvizEdge();
{ const value=edge, expected=""; test("GraphvizEdgeTests.ToDot fixture 1",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
edge = Object.assign(new G.GraphvizEdge(),{Url:"https://test.url.fr"});
{ const value=edge, expected="URL=\"https://test.url.fr\""; test("GraphvizEdgeTests.ToDot fixture 2",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
edge = Object.assign(new G.GraphvizEdge(),{ToolTip:"The edge tooltip",Style:G.GraphvizEdgeStyle.Dotted,StrokeColor:G.GraphvizColor.LightYellow});
{ const value=edge, expected="color=\"#FFFFE0FF\", style=dotted, tooltip=\"The edge tooltip\""; test("GraphvizEdgeTests.ToDot fixture 3",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
edge = Object.assign(new G.GraphvizEdge(),{Label:Object.assign(new G.GraphvizEdgeLabel(),{Value:"<b>Bold</b> text"}),Head:Object.assign(new G.GraphvizEdgeExtremity(true),{Label:"<b>Bold</b> text"}),Tail:Object.assign(new G.GraphvizEdgeExtremity(false),{Label:"<b>Bold</b> text"})});
{ const value=edge, expected="headlabel=\"<b>Bold</b> text\", label=\"<b>Bold</b> text\", taillabel=\"<b>Bold</b> text\""; test("GraphvizEdgeTests.ToDot fixture 4",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
edge = Object.assign(new G.GraphvizEdge(),{Label:Object.assign(new G.GraphvizEdgeLabel(),{IsHtmlLabel:true,Value:"<b>Bold</b> text"}),Head:Object.assign(new G.GraphvizEdgeExtremity(true),{IsHtmlLabel:true,Label:"<b>Bold</b> text"}),Tail:Object.assign(new G.GraphvizEdgeExtremity(false),{IsHtmlLabel:true,Label:"<b>Bold</b> text"})});
{ const value=edge, expected="headlabel=<<b>Bold</b> text>, label=<<b>Bold</b> text>, taillabel=<<b>Bold</b> text>"; test("GraphvizEdgeTests.ToDot fixture 5",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
edge = Object.assign(new G.GraphvizEdge(),{Comment:"Test comment",Label:Object.assign(new G.GraphvizEdgeLabel(),{Value:"Test Label",Angle:15,Distance:5,Float:false,Font:new G.GraphvizFont("Label font",10.0),FontColor:G.GraphvizColor.Aquamarine}),ToolTip:"Test tooltip",Url:"https://test.com",Direction:G.GraphvizEdgeDirection.Both,Font:new G.GraphvizFont("Test font",12.0),FontColor:G.GraphvizColor.Chocolate,PenWidth:2.0,Head:Object.assign(new G.GraphvizEdgeExtremity(true),{Label:"Head label"}),HeadArrow:new G.GraphvizArrow(G.GraphvizArrowShape.Diamond),HeadPort:"TestHeadPort",Tail:Object.assign(new G.GraphvizEdgeExtremity(false),{Label:"Tail label"}),TailArrow:new G.GraphvizArrow(G.GraphvizArrowShape.Curve),TailPort:"TestTailPort",IsConstrained:false,IsDecorated:true,Layer:new G.GraphvizLayer("Edge Layer"),StrokeColor:G.GraphvizColor.DarkGreen,Style:G.GraphvizEdgeStyle.Bold,Weight:2,Length:5,MinLength:2});
{ const value=edge, expected="dir=both, fontname=\"Test font\", fontsize=12, fontcolor=\"#D2691EFF\", penwidth=2, " + "headlabel=\"Head label\", arrowhead=\"diamond\", headport=\"TestHeadPort\", " + "constraint=false, decorate=true, label=\"Test Label\", labelangle=15, " + "labeldistance=5, labelfloat=false, labelfontname=\"Label font\", labelfontsize=10, " + "labelfontcolor=\"#7FFFD4FF\", layer=\"Edge Layer\", minlen=2, len=5, color=\"#006400FF\", " + "style=bold, taillabel=\"Tail label\", arrowtail=\"curve\", tailport=\"TestTailPort\", " + "tooltip=\"Test tooltip\", comment=\"Test comment\", URL=\"https://test.com\", " + "weight=2"; test("GraphvizEdgeTests.ToDot fixture 6",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
edge = Object.assign(new G.GraphvizEdge(),{Comment:"\"The Comment\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪",Label:Object.assign(new G.GraphvizEdgeLabel(),{Value:"\"The Label\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪"}),ToolTip:"\"The Tooltip\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪",Head:Object.assign(new G.GraphvizEdgeExtremity(true),{Label:"\"The Head Label\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪"}),HeadPort:"\"The Head Port\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪",Tail:Object.assign(new G.GraphvizEdgeExtremity(false),{Label:"\"The Tail Label\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪"}),TailPort:"\"The Tail Port\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪"});
{ const value=edge, expected="headlabel=\"\\\"The Head Label\\\"\\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\\\[]() Content ∴∞⇐ℜΩ÷嗷娪\", " + "headport=\"_The_Head_Port___&/__@~__With_æéèêë£¤¶ÀÁÂÃÄÅ_Escaped_Ση←_♠_[]()_Content_∴∞⇐ℜΩ÷嗷娪\", " + "label=\"\\\"The Label\\\"\\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\\\[]() Content ∴∞⇐ℜΩ÷嗷娪\", " + "taillabel=\"\\\"The Tail Label\\\"\\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\\\[]() Content ∴∞⇐ℜΩ÷嗷娪\", " + "tailport=\"_The_Tail_Port___&/__@~__With_æéèêë£¤¶ÀÁÂÃÄÅ_Escaped_Ση←_♠_[]()_Content_∴∞⇐ℜΩ÷嗷娪\", " + "tooltip=\"\\\"The Tooltip\\\"\\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\\\[]() Content ∴∞⇐ℜΩ÷嗷娪\", " + "comment=\"\\\"The Comment\\\"\\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\\\[]() Content ∴∞⇐ℜΩ÷嗷娪\""; test("GraphvizEdgeTests.ToDot fixture 7",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
edge = Object.assign(new G.GraphvizEdge(),{Label:Object.assign(new G.GraphvizEdgeLabel(),{IsHtmlLabel:true,Value:"<i>\"The Label\"</i>\n &amp;/&lt;&gt;@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪"}),Head:Object.assign(new G.GraphvizEdgeExtremity(true),{IsHtmlLabel:true,Label:"<i>\"The Label\"</i>\n &amp;/&lt;&gt;@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪"}),Tail:Object.assign(new G.GraphvizEdgeExtremity(false),{IsHtmlLabel:true,Label:"<i>\"The Label\"</i>\n &amp;/&lt;&gt;@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪"})});
{ const value=edge, expected="headlabel=<<i>\"The Label\"</i>" + "\n" + " &amp;/&lt;&gt;@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪>, " + "label=<<i>\"The Label\"</i>" + "\n" + " &amp;/&lt;&gt;@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪>, " + "taillabel=<<i>\"The Label\"</i>" + "\n" + " &amp;/&lt;&gt;@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪>"; test("GraphvizEdgeTests.ToDot fixture 8",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
}

// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizGraphTests.cs::ToDot
{
let graph = new G.GraphvizGraph();
{ const value=graph, expected=""; test("GraphvizGraphTests.ToDot fixture 1",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
graph = Object.assign(new G.GraphvizGraph(),{Comment:"Test comment"});
{ const value=graph, expected="comment=\"Test comment\""; test("GraphvizGraphTests.ToDot fixture 2",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
graph = Object.assign(new G.GraphvizGraph(),{Url:"https://test.fr",PageDirection:G.GraphvizPageDirection.LB});
{ const value=graph, expected="URL=\"https://test.fr\"; pagedir=LB;"; test("GraphvizGraphTests.ToDot fixture 3",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
graph = Object.assign(new G.GraphvizGraph(),{IsNormalized:true,NodeSeparation:2,RankSeparation:2,BackgroundColor:G.GraphvizColor.Coral});
{ const value=graph, expected="bgcolor=\"#FF7F50FF\"; nodesep=2; ranksep=2; normalize=true;"; test("GraphvizGraphTests.ToDot fixture 4",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
graph = Object.assign(new G.GraphvizGraph(),{Name:"GraphName",Comment:"Test comment",Url:"https://test.com",BackgroundColor:G.GraphvizColor.Bisque,ClusterRank:G.GraphvizClusterMode.Global,Font:new G.GraphvizFont("Test font",12),FontColor:G.GraphvizColor.DarkOrange,PenWidth:2.0,IsCentered:true,IsCompounded:true,IsConcentrated:true,IsNormalized:true,IsReMinCross:true,Label:"Test label",LabelJustification:G.GraphvizLabelJustification.L,LabelLocation:G.GraphvizLabelLocation.T,Layers:new G.GraphvizLayerCollection([new G.GraphvizLayer("Layer1"),new G.GraphvizLayer("Layer2")]),McLimit:2.0,NodeSeparation:1.0,RankDirection:G.GraphvizRankDirection.LR,RankSeparation:2.0,NsLimit:2,NsLimit1:3,OutputOrder:G.GraphvizOutputMode.NodesFirst,PageDirection:G.GraphvizPageDirection.RT,PageSize:new G.GraphvizSizeF(10.0,15.0),Quantum:1.0,Ratio:G.GraphvizRatioMode.Fill,Resolution:1,SamplePoints:9,SearchSize:25,Size:new G.GraphvizSizeF(25.0,45.0),Splines:G.GraphvizSplineType.Curved,StyleSheet:"stylesheet.xml"});
graph.Layers.Separators = ":-:";
{ const value=graph, expected="URL=\"https://test.com\"; bgcolor=\"#FFE4C4FF\"; center=true; clusterrank=\"global\"; " + "comment=\"Test comment\"; compound=true; concentrate=true; fontname=\"Test font\"; " + "fontsize=12; fontcolor=\"#FF8C00FF\"; penwidth=2; label=\"Test label\"; labeljust=\"l\"; " + "labelloc=\"t\"; layers=\"Layer1:-:Layer2\"; layersep=\":-:\"; mclimit=2; " + "nodesep=1; rankdir=LR; ranksep=2; normalize=true; nslimit=2; nslimit1=3; " + "outputorder=\"nodesfirst\"; page=\"10,15\"; pagedir=RT; quantum=1; ratio=\"fill\"; " + "remincross=true; resolution=1; samplepoints=9; searchsize=25; size=\"25,45\"; " + "splines=curved; stylesheet=\"stylesheet.xml\";"; test("GraphvizGraphTests.ToDot fixture 5",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
graph = Object.assign(new G.GraphvizGraph(),{Rotate:12});
{ const value=graph, expected="rotate=12"; test("GraphvizGraphTests.ToDot fixture 6",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
graph = Object.assign(new G.GraphvizGraph(),{IsLandscape:true});
{ const value=graph, expected="orientation=\"[1L]*\""; test("GraphvizGraphTests.ToDot fixture 7",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
graph = Object.assign(new G.GraphvizGraph(),{Rotate:14,IsLandscape:true});
{ const value=graph, expected="rotate=14"; test("GraphvizGraphTests.ToDot fixture 8",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
graph = Object.assign(new G.GraphvizGraph(),{Comment:"\"The Comment\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪",Label:"\"The Label\"\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪"});
{ const value=graph, expected="comment=\"\\\"The Comment\\\"\\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\\\[]() Content ∴∞⇐ℜΩ÷嗷娪\"; " + "label=\"\\\"The Label\\\"\\n &/<>@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\\\[]() Content ∴∞⇐ℜΩ÷嗷娪\";"; test("GraphvizGraphTests.ToDot fixture 9",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
graph = Object.assign(new G.GraphvizGraph(),{IsHtmlLabel:true,Label:"<i>\"The Label\"</i>\n &amp;/&lt;&gt;@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪"});
{ const value=graph, expected="label=<<i>\"The Label\"</i>" + "\n" + " &amp;/&lt;&gt;@~| With æéèêë£¤¶ÀÁÂÃÄÅ Escaped Ση← ♠\\[]() Content ∴∞⇐ℜΩ÷嗷娪>"; test("GraphvizGraphTests.ToDot fixture 10",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
}

// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordTests.cs::ToDot
{
let emptyRecord = new G.GraphvizRecord();
{ const value=emptyRecord, expected=""; test("GraphvizRecordTests.ToDot fixture 1",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let recordWithChildCell = Object.assign(new G.GraphvizRecord(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort",Text:"SubText"})])});
{ const value=recordWithChildCell, expected="<SubPort> SubText"; test("GraphvizRecordTests.ToDot fixture 2",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let recordWithChildrenCells = Object.assign(new G.GraphvizRecord(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort2",Text:"SubText2"}),Object.assign(new G.GraphvizRecordCell(),{Text:"SubText3"})])});
{ const value=recordWithChildrenCells, expected="<SubPort1>  | <SubPort2> SubText2 | SubText3"; test("GraphvizRecordTests.ToDot fixture 3",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let recordWithChildrenCellsAndNestedCells = Object.assign(new G.GraphvizRecord(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort1"}),Object.assign(new G.GraphvizRecordCell(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Text:"NestedText1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"NestedPort2",Text:"NestedText2"}),Object.assign(new G.GraphvizRecordCell(),{Text:"NestedText3"})])}),Object.assign(new G.GraphvizRecordCell(),{Text:"SubText3"})])});
{ const value=recordWithChildrenCellsAndNestedCells, expected="<SubPort1>  | { NestedText1 | <NestedPort2> NestedText2 | NestedText3 } | SubText3"; test("GraphvizRecordTests.ToDot fixture 4",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let recordWithChildrenCellsAndNestedCells2 = Object.assign(new G.GraphvizRecord(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort2",Text:"SubText2",Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Text:"NestedText1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"NestedPort2",Text:"NestedText2"}),Object.assign(new G.GraphvizRecordCell(),{Text:"NestedText3"})])}),Object.assign(new G.GraphvizRecordCell(),{Text:"SubText3"})])});
{ const value=recordWithChildrenCellsAndNestedCells2, expected="<SubPort1>  | <SubPort2> SubText2 | { NestedText1 | <NestedPort2> NestedText2 | NestedText3 } | SubText3"; test("GraphvizRecordTests.ToDot fixture 5",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
}

// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordCellTests.cs::ToDot
{
let emptyCell = new G.GraphvizRecordCell();
{ const value=emptyCell, expected=""; test("GraphvizRecordCellTests.ToDot fixture 1",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithText = Object.assign(new G.GraphvizRecordCell(),{Text:"SomeText"});
{ const value=cellWithText, expected="SomeText"; test("GraphvizRecordCellTests.ToDot fixture 2",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithPort = Object.assign(new G.GraphvizRecordCell(),{Port:"SomePort"});
{ const value=cellWithPort, expected="<SomePort> "; test("GraphvizRecordCellTests.ToDot fixture 3",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithBoth = Object.assign(new G.GraphvizRecordCell(),{Port:"Port",Text:"Text"});
{ const value=cellWithBoth, expected="<Port> Text"; test("GraphvizRecordCellTests.ToDot fixture 4",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithSpaceToEscape = Object.assign(new G.GraphvizRecordCell(),{Port:"Some Port",Text:"Some Text"});
{ const value=cellWithSpaceToEscape, expected="<Some_Port> Some\\ Text"; test("GraphvizRecordCellTests.ToDot fixture 5",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithBackslashToEscape = Object.assign(new G.GraphvizRecordCell(),{Port:"Some\\Port",Text:"Some\\Text"});
{ const value=cellWithBackslashToEscape, expected="<Some_Port> Some\\\\Text"; test("GraphvizRecordCellTests.ToDot fixture 6",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithDoubleQuoteToEscape = Object.assign(new G.GraphvizRecordCell(),{Port:"Some\"Port",Text:"Some\"Text"});
{ const value=cellWithDoubleQuoteToEscape, expected="<Some_Port> Some\\\"Text"; test("GraphvizRecordCellTests.ToDot fixture 7",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithLessToEscape = Object.assign(new G.GraphvizRecordCell(),{Port:"Some<Port",Text:"Some<Text"});
{ const value=cellWithLessToEscape, expected="<Some_Port> Some\\<Text"; test("GraphvizRecordCellTests.ToDot fixture 8",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithGreaterToEscape = Object.assign(new G.GraphvizRecordCell(),{Port:"Some>Port",Text:"Some>Text"});
{ const value=cellWithGreaterToEscape, expected="<Some_Port> Some\\>Text"; test("GraphvizRecordCellTests.ToDot fixture 9",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithPipeToEscape = Object.assign(new G.GraphvizRecordCell(),{Port:"Some|Port",Text:"Some|Text"});
{ const value=cellWithPipeToEscape, expected="<Some_Port> Some\\|Text"; test("GraphvizRecordCellTests.ToDot fixture 10",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithLineBreakToEscape = Object.assign(new G.GraphvizRecordCell(),{Port:"Some\nPort",Text:"Some\nText"});
{ const value=cellWithLineBreakToEscape, expected="<Some_Port> Some\\nText"; test("GraphvizRecordCellTests.ToDot fixture 11",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithChildCell = Object.assign(new G.GraphvizRecordCell(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort",Text:"SubText"})])});
{ const value=cellWithChildCell, expected="{ <SubPort> SubText }"; test("GraphvizRecordCellTests.ToDot fixture 12",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellMultiPatternWithChildCell = Object.assign(new G.GraphvizRecordCell(),{Port:"SomePort",Text:"SomeText",Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort",Text:"SubText"})])});
{ const value=cellMultiPatternWithChildCell, expected="<SomePort> SomeText | { <SubPort> SubText }"; test("GraphvizRecordCellTests.ToDot fixture 13",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithChildrenCells = Object.assign(new G.GraphvizRecordCell(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort2",Text:"SubText2"}),Object.assign(new G.GraphvizRecordCell(),{Text:"SubText3"})])});
{ const value=cellWithChildrenCells, expected="{ <SubPort1>  | <SubPort2> SubText2 | SubText3 }"; test("GraphvizRecordCellTests.ToDot fixture 14",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellMultiPatternWithChildrenCells = Object.assign(new G.GraphvizRecordCell(),{Port:"SomePort",Text:"SomeText",Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort2",Text:"SubText2"}),Object.assign(new G.GraphvizRecordCell(),{Text:"SubText3"})])});
{ const value=cellMultiPatternWithChildrenCells, expected="<SomePort> SomeText | { <SubPort1>  | <SubPort2> SubText2 | SubText3 }"; test("GraphvizRecordCellTests.ToDot fixture 15",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithChildrenCellsAndNestedCells = Object.assign(new G.GraphvizRecordCell(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort1"}),Object.assign(new G.GraphvizRecordCell(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Text:"NestedText1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"NestedPort2",Text:"NestedText2"}),Object.assign(new G.GraphvizRecordCell(),{Text:"NestedText3"})])}),Object.assign(new G.GraphvizRecordCell(),{Text:"SubText3"})])});
{ const value=cellWithChildrenCellsAndNestedCells, expected="{ <SubPort1>  | { NestedText1 | <NestedPort2> NestedText2 | NestedText3 } | SubText3 }"; test("GraphvizRecordCellTests.ToDot fixture 16",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellWithChildrenCellsAndNestedCells2 = Object.assign(new G.GraphvizRecordCell(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort2",Text:"SubText2",Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Text:"NestedText1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"NestedPort2",Text:"NestedText2"}),Object.assign(new G.GraphvizRecordCell(),{Text:"NestedText3"})])}),Object.assign(new G.GraphvizRecordCell(),{Text:"SubText3"})])});
{ const value=cellWithChildrenCellsAndNestedCells2, expected="{ <SubPort1>  | <SubPort2> SubText2 | { NestedText1 | <NestedPort2> NestedText2 | NestedText3 } | SubText3 }"; test("GraphvizRecordCellTests.ToDot fixture 17",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
let cellMultiPatternWithChildrenCellsAndNestedCells = Object.assign(new G.GraphvizRecordCell(),{Port:"SomePort",Text:"SomeText",Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Port:"SubPort1"}),Object.assign(new G.GraphvizRecordCell(),{Cells:new G.GraphvizRecordCellCollection([Object.assign(new G.GraphvizRecordCell(),{Text:"NestedText1"}),Object.assign(new G.GraphvizRecordCell(),{Port:"NestedPort2",Text:"NestedText2"}),Object.assign(new G.GraphvizRecordCell(),{Text:"NestedText3"})])}),Object.assign(new G.GraphvizRecordCell(),{Text:"SubText3"})])});
{ const value=cellMultiPatternWithChildrenCellsAndNestedCells, expected="<SomePort> SomeText | { <SubPort1>  | { NestedText1 | <NestedPort2> NestedText2 | NestedText3 } | SubText3 }"; test("GraphvizRecordCellTests.ToDot fixture 18",()=>{assert.equal(value.ToDot(),expected);assert.equal(value.ToString(),expected);}); }
}

// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizArrowTests.cs::ToDot
test("GraphvizArrowTests.ToDot variant 0",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Box, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"box");assert.equal(arrow.ToString(),"box");});
test("GraphvizArrowTests.ToDot variant 1",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Box, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"lbox");assert.equal(arrow.ToString(),"lbox");});
test("GraphvizArrowTests.ToDot variant 2",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Box, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"rbox");assert.equal(arrow.ToString(),"rbox");});
test("GraphvizArrowTests.ToDot variant 3",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Box, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"obox");assert.equal(arrow.ToString(),"obox");});
test("GraphvizArrowTests.ToDot variant 4",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Box, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"olbox");assert.equal(arrow.ToString(),"olbox");});
test("GraphvizArrowTests.ToDot variant 5",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Box, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"orbox");assert.equal(arrow.ToString(),"orbox");});
test("GraphvizArrowTests.ToDot variant 6",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Crow, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"crow");assert.equal(arrow.ToString(),"crow");});
test("GraphvizArrowTests.ToDot variant 7",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Crow, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"lcrow");assert.equal(arrow.ToString(),"lcrow");});
test("GraphvizArrowTests.ToDot variant 8",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Crow, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"rcrow");assert.equal(arrow.ToString(),"rcrow");});
test("GraphvizArrowTests.ToDot variant 9",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Diamond, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"diamond");assert.equal(arrow.ToString(),"diamond");});
test("GraphvizArrowTests.ToDot variant 10",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Diamond, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"ldiamond");assert.equal(arrow.ToString(),"ldiamond");});
test("GraphvizArrowTests.ToDot variant 11",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Diamond, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"rdiamond");assert.equal(arrow.ToString(),"rdiamond");});
test("GraphvizArrowTests.ToDot variant 12",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Diamond, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"odiamond");assert.equal(arrow.ToString(),"odiamond");});
test("GraphvizArrowTests.ToDot variant 13",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Diamond, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"oldiamond");assert.equal(arrow.ToString(),"oldiamond");});
test("GraphvizArrowTests.ToDot variant 14",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Diamond, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"ordiamond");assert.equal(arrow.ToString(),"ordiamond");});
test("GraphvizArrowTests.ToDot variant 15",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Dot, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"dot");assert.equal(arrow.ToString(),"dot");});
test("GraphvizArrowTests.ToDot variant 16",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Dot, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"odot");assert.equal(arrow.ToString(),"odot");});
test("GraphvizArrowTests.ToDot variant 17",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Inv, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"inv");assert.equal(arrow.ToString(),"inv");});
test("GraphvizArrowTests.ToDot variant 18",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Inv, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"linv");assert.equal(arrow.ToString(),"linv");});
test("GraphvizArrowTests.ToDot variant 19",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Inv, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"rinv");assert.equal(arrow.ToString(),"rinv");});
test("GraphvizArrowTests.ToDot variant 20",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Inv, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"oinv");assert.equal(arrow.ToString(),"oinv");});
test("GraphvizArrowTests.ToDot variant 21",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Inv, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"olinv");assert.equal(arrow.ToString(),"olinv");});
test("GraphvizArrowTests.ToDot variant 22",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Inv, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"orinv");assert.equal(arrow.ToString(),"orinv");});
test("GraphvizArrowTests.ToDot variant 23",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.None, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"none");assert.equal(arrow.ToString(),"none");});
test("GraphvizArrowTests.ToDot variant 24",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Normal, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"normal");assert.equal(arrow.ToString(),"normal");});
test("GraphvizArrowTests.ToDot variant 25",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Normal, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"lnormal");assert.equal(arrow.ToString(),"lnormal");});
test("GraphvizArrowTests.ToDot variant 26",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Normal, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"rnormal");assert.equal(arrow.ToString(),"rnormal");});
test("GraphvizArrowTests.ToDot variant 27",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Normal, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"onormal");assert.equal(arrow.ToString(),"onormal");});
test("GraphvizArrowTests.ToDot variant 28",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Normal, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"olnormal");assert.equal(arrow.ToString(),"olnormal");});
test("GraphvizArrowTests.ToDot variant 29",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Normal, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"ornormal");assert.equal(arrow.ToString(),"ornormal");});
test("GraphvizArrowTests.ToDot variant 30",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Tee, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"tee");assert.equal(arrow.ToString(),"tee");});
test("GraphvizArrowTests.ToDot variant 31",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Tee, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"ltee");assert.equal(arrow.ToString(),"ltee");});
test("GraphvizArrowTests.ToDot variant 32",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Tee, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"rtee");assert.equal(arrow.ToString(),"rtee");});
test("GraphvizArrowTests.ToDot variant 33",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Vee, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"vee");assert.equal(arrow.ToString(),"vee");});
test("GraphvizArrowTests.ToDot variant 34",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Vee, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"lvee");assert.equal(arrow.ToString(),"lvee");});
test("GraphvizArrowTests.ToDot variant 35",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Vee, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"rvee");assert.equal(arrow.ToString(),"rvee");});
test("GraphvizArrowTests.ToDot variant 36",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Curve, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"curve");assert.equal(arrow.ToString(),"curve");});
test("GraphvizArrowTests.ToDot variant 37",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Curve, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"lcurve");assert.equal(arrow.ToString(),"lcurve");});
test("GraphvizArrowTests.ToDot variant 38",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Curve, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"rcurve");assert.equal(arrow.ToString(),"rcurve");});
test("GraphvizArrowTests.ToDot variant 39",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.ICurve, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"icurve");assert.equal(arrow.ToString(),"icurve");});
test("GraphvizArrowTests.ToDot variant 40",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.ICurve, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"licurve");assert.equal(arrow.ToString(),"licurve");});
test("GraphvizArrowTests.ToDot variant 41",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.ICurve, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"ricurve");assert.equal(arrow.ToString(),"ricurve");});
test("GraphvizArrowTests.ToDot variant 42",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Crow, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"crow");assert.equal(arrow.ToString(),"crow");});
test("GraphvizArrowTests.ToDot variant 43",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Crow, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"lcrow");assert.equal(arrow.ToString(),"lcrow");});
test("GraphvizArrowTests.ToDot variant 44",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Crow, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"rcrow");assert.equal(arrow.ToString(),"rcrow");});
test("GraphvizArrowTests.ToDot variant 45",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Dot, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"dot");assert.equal(arrow.ToString(),"dot");});
test("GraphvizArrowTests.ToDot variant 46",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Dot, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"dot");assert.equal(arrow.ToString(),"dot");});
test("GraphvizArrowTests.ToDot variant 47",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Dot, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"odot");assert.equal(arrow.ToString(),"odot");});
test("GraphvizArrowTests.ToDot variant 48",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Dot, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"odot");assert.equal(arrow.ToString(),"odot");});
test("GraphvizArrowTests.ToDot variant 49",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.None, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"none");assert.equal(arrow.ToString(),"none");});
test("GraphvizArrowTests.ToDot variant 50",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.None, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Close);assert.equal(arrow.ToDot(),"none");assert.equal(arrow.ToString(),"none");});
test("GraphvizArrowTests.ToDot variant 51",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.None, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"none");assert.equal(arrow.ToString(),"none");});
test("GraphvizArrowTests.ToDot variant 52",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.None, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"none");assert.equal(arrow.ToString(),"none");});
test("GraphvizArrowTests.ToDot variant 53",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.None, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"none");assert.equal(arrow.ToString(),"none");});
test("GraphvizArrowTests.ToDot variant 54",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Tee, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"tee");assert.equal(arrow.ToString(),"tee");});
test("GraphvizArrowTests.ToDot variant 55",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Tee, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"ltee");assert.equal(arrow.ToString(),"ltee");});
test("GraphvizArrowTests.ToDot variant 56",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Tee, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"rtee");assert.equal(arrow.ToString(),"rtee");});
test("GraphvizArrowTests.ToDot variant 57",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Vee, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"vee");assert.equal(arrow.ToString(),"vee");});
test("GraphvizArrowTests.ToDot variant 58",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Vee, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"lvee");assert.equal(arrow.ToString(),"lvee");});
test("GraphvizArrowTests.ToDot variant 59",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Vee, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"rvee");assert.equal(arrow.ToString(),"rvee");});
test("GraphvizArrowTests.ToDot variant 60",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Curve, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"curve");assert.equal(arrow.ToString(),"curve");});
test("GraphvizArrowTests.ToDot variant 61",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Curve, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"lcurve");assert.equal(arrow.ToString(),"lcurve");});
test("GraphvizArrowTests.ToDot variant 62",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.Curve, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"rcurve");assert.equal(arrow.ToString(),"rcurve");});
test("GraphvizArrowTests.ToDot variant 63",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.ICurve, G.GraphvizArrowClipping.None, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"icurve");assert.equal(arrow.ToString(),"icurve");});
test("GraphvizArrowTests.ToDot variant 64",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.ICurve, G.GraphvizArrowClipping.Left, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"licurve");assert.equal(arrow.ToString(),"licurve");});
test("GraphvizArrowTests.ToDot variant 65",()=>{const arrow=new G.GraphvizArrow(G.GraphvizArrowShape.ICurve, G.GraphvizArrowClipping.Right, G.GraphvizArrowFilling.Open);assert.equal(arrow.ToDot(),"ricurve");assert.equal(arrow.ToString(),"ricurve");});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizLayerCollectionTests.cs::Constructor
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizLayerCollectionTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizLayerCollectionTests.cs::Separators
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizLayerCollectionTests.cs::Separators_Throws
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizLayerCollectionTests.cs::ToDot
test('GraphvizLayerCollectionTests constructors / separators / DOT',()=>{const empty=new G.GraphvizLayerCollection();assert.equal(empty.Count,0);assert.equal(empty.Separators,':');assert.equal(empty.ToDot(),'');assert.throws(()=>new G.GraphvizLayerCollection(null));for(const value of[null,''])assert.throws(()=>{empty.Separators=value;});const layers=new G.GraphvizLayerCollection([new G.GraphvizLayer('L1'),new G.GraphvizLayer('L2'),new G.GraphvizLayer('L3')]);assert.equal(layers.ToDot(),'layers="L1:L2:L3"; layersep=":"');layers.Separators=' -/';assert.equal(layers.ToDot(),'layers="L1 -/L2 -/L3"; layersep=" -/"');assert.deepEqual([...new G.GraphvizLayerCollection(layers)],[...layers]);});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeLabelTests.cs::Constructor
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeLabelTests.cs::AddParameters
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeLabelTests.cs::AddParameters_Throws
test('GraphvizEdgeLabelTests defaults and parameter map',()=>{const l=new G.GraphvizEdgeLabel(),p=new Map();assert.equal(l.Angle,-25);assert.equal(l.Distance,1);assert.equal(l.Float,true);assert.equal(l.Value,null);assert.throws(()=>l.AddParameters(null));l.FontColor=G.GraphvizColor.Azure;l.AddParameters(p);assert.equal(p.size,0);l.Value='"The label"\n';l.AddParameters(p);assert.equal(p.get('label'),'\\"The label\\"\\n');assert.equal(p.get('labelfontcolor'),G.GraphvizColor.Azure);Object.assign(l,{Value:'The Demo Label',Angle:35.5,Distance:2,Float:false,Font:new G.GraphvizFont('Test font',16),FontColor:G.GraphvizColor.BlueViolet});p.clear();l.AddParameters(p);assert.deepEqual(p,new Map([['label','The Demo Label'],['labelangle',35.5],['labeldistance',2],['labelfloat',false],['labelfontname','Test font'],['labelfontsize',16],['labelfontcolor',G.GraphvizColor.BlueViolet]]));});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeExtremityTests.cs::Constructor
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeExtremityTests.cs::AddParameters
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeExtremityTests.cs::AddParameters_Throws
for(const head of[true,false])test(`GraphvizEdgeExtremityTests parameter map ${head}`,()=>{const e=new G.GraphvizEdgeExtremity(head),p=new Map(),prefix=head?'head':'tail';assert.equal(e.IsClipped,true);assert.equal(e.IsHead,head);assert.equal(e.IsHtmlLabel,false);assert.throws(()=>e.AddParameters(null));e.AddParameters(p);assert.equal(p.size,0);Object.assign(e,{IsClipped:false,Url:'https://example.test',Label:'"label"\n',ToolTip:'"tooltip"',Logical:'cluster1',Same:'group1'});e.AddParameters(p);assert.deepEqual(p,new Map([[prefix+'URL','https://example.test'],[prefix+'clip',false],[prefix+'label','\\"label\\"\\n'],[prefix+'tooltip','\\"tooltip\\"'],['l'+prefix,'cluster1'],['same'+prefix,'group1']]));});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizFontTests.cs::Constructor
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizFontTests.cs::Constructor_Throws
test('GraphvizFontTests constructor validation',()=>{const f=new G.GraphvizFont('Arial',14.5);assert.equal(f.Name,'Arial');assert.equal(f.SizeInPoints,14.5);for(const name of[null,''])assert.throws(()=>new G.GraphvizFont(name,10));for(const n of[0,-1,NaN])assert.throws(()=>new G.GraphvizFont('a',n));});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizLayerTests.cs::Constructor
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizLayerTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizLayerTests.cs::Name
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizLayerTests.cs::Name_Throws
test('GraphvizLayerTests constructor / Name',()=>{const layer=new G.GraphvizLayer('layer');assert.equal(layer.Name,'layer');layer.Name='renamed';assert.equal(layer.Name,'renamed');for(const value of[null,'']){assert.throws(()=>new G.GraphvizLayer(value));assert.throws(()=>{layer.Name=value;});}});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeTests.cs::Label
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeTests.cs::Label_Throws
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeTests.cs::Head
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeTests.cs::Head_Throws
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeTests.cs::Tail
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeTests.cs::Tail_Throws
test('GraphvizEdgeTests component assignment',()=>{const edge=new G.GraphvizEdge(),head=new G.GraphvizEdgeExtremity(true),tail=new G.GraphvizEdgeExtremity(false),label=new G.GraphvizEdgeLabel();edge.Head=head;edge.Tail=tail;edge.Label=label;assert.equal(edge.Head,head);assert.equal(edge.Tail,tail);assert.equal(edge.Label,label);for(const property of['Head','Tail','Label'])assert.throws(()=>{edge[property]=null;});assert.throws(()=>{edge.Head=tail;});assert.throws(()=>{edge.Tail=head;});});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizGraphTests.cs::Name
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizGraphTests.cs::Name_Throws
test('GraphvizGraphTests name validation',()=>{const graph=new G.GraphvizGraph();assert.equal(graph.Name,'G');graph.Name='renamed';assert.equal(graph.Name,'renamed');assert.throws(()=>{graph.Name=null;});});
// upstream: tests/QuikGraph.Graphviz.Tests/GraphvizAlgorithmTests.cs::Constructor
// upstream: tests/QuikGraph.Graphviz.Tests/GraphvizAlgorithmTests.cs::Constructor_Throws
for(const Type of[AdjacencyGraph,UndirectedGraph])test(`GraphvizAlgorithmTests basic DOT ${Type.name}`,()=>{const graph=new Type();graph.AddVerticesAndEdge(new Edge('a','b'));graph.AddVertex('isolated');const a=new G.GraphvizAlgorithm(graph);assert.equal(a.ImageType,G.GraphvizImageType.Png);assert.equal(a.VisitedGraph,graph);assert.equal(a.Output,null);a.FormatVertex.add((sender,args)=>{assert.equal(sender,a);args.VertexFormat.Label=args.Vertex;});a.FormatEdge.add((sender,args)=>{args.EdgeFormat.Label.Value='relation';});const dot=a.Generate();assert.match(dot,/0 \[label="a"\]/);assert.match(dot,/2 \[label="isolated"\]/);assert.match(dot,Type===AdjacencyGraph?/0 -> 1/:/0 -- 1/);assert.equal(a.Output,dot);assert.equal(a.Generate(),dot);assert.throws(()=>new G.GraphvizAlgorithm(null));assert.throws(()=>{a.VisitedGraph=null;});assert.throws(()=>a.Generate(null,'file'));});
// upstream: tests/QuikGraph.Graphviz.Tests/FileFotEngineTests.cs::Run
// Portable write callback replaces the .NET filesystem path side effect.
test('FileDotEngineTests.Run',async()=>{const files=new Map(),engine=new G.FileDotEngine((path,text)=>files.set(path,text));assert.equal(engine.Run(G.GraphvizImageType.Png,'digraph {}','test'),'test.dot');assert.equal(files.get('test.dot'),'digraph {}');assert.equal(engine.Run(G.GraphvizImageType.Png,'digraph {}','test.DOT'),'test.DOT');assert.throws(()=>engine.Run('png','','a'));assert.throws(()=>engine.Run('png','dot',''));const asyncEngine=new G.FileDotEngine(async(path,text)=>files.set(path,text));assert.equal(await asyncEngine.Run('png','dot','async'),'async.dot');});
// upstream: tests/QuikGraph.Graphviz.Tests/SvgHtmlWrapperTests.cs::ParseSize
// upstream: tests/QuikGraph.Graphviz.Tests/SvgHtmlWrapperTests.cs::ParseSize_Throws
// upstream: tests/QuikGraph.Graphviz.Tests/SvgHtmlWrapperTests.cs::DumpHtml
// upstream: tests/QuikGraph.Graphviz.Tests/SvgHtmlWrapperTests.cs::DumpHtml_Throws
// upstream: tests/QuikGraph.Graphviz.Tests/SvgHtmlWrapperTests.cs::WrapSvg
// upstream: tests/QuikGraph.Graphviz.Tests/SvgHtmlWrapperTests.cs::WrapSvg_Throws
test('SvgHtmlWrapperTests parsing and portable HTML writing',()=>{const svg='<svg width="300" height="200"></svg>';assert.deepEqual(G.SvgHtmlWrapper.ParseSize(svg),new G.GraphvizSize(300,200));assert.deepEqual(G.SvgHtmlWrapper.ParseSize('<svg><rect width="30" height="20"/></svg>'),new G.GraphvizSize(400,400));assert.throws(()=>G.SvgHtmlWrapper.ParseSize(null));assert.throws(()=>G.SvgHtmlWrapper.DumpHtml(new G.GraphvizSize(1,1),null));assert.throws(()=>G.SvgHtmlWrapper.WrapSvg(null));const files=new Map();assert.equal(G.SvgHtmlWrapper.DumpHtml(new G.GraphvizSize(300,200),'test.svg',(p,t)=>files.set(p,t)),'test.svg.html');assert.match(files.get('test.svg.html'),/data="test.svg"/);assert.match(G.SvgHtmlWrapper.WrapSvg(svg),/width="300"/);});

const constructorChecks={equal:(a,b)=>assert.deepEqual(b,a),isNull:v=>assert.equal(v,null),notNull:v=>assert.notEqual(v,null),isFalse:v=>assert.equal(v,false),isTrue:v=>assert.equal(v,true),zero:v=>assert.equal(v,0),empty:v=>assert.equal([...v].length,0)};

// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizVertexTests.cs::Constructor
test("GraphvizVertexTests.Constructor full property defaults",()=>{const vertex=new G.GraphvizVertex();constructorChecks.isNull(vertex.Position);constructorChecks.isNull(vertex.Comment);constructorChecks.isFalse(vertex.IsHtmlLabel);constructorChecks.isNull(vertex.Label);constructorChecks.isNull(vertex.ToolTip);constructorChecks.isNull(vertex.Url);constructorChecks.zero(vertex.Distortion);constructorChecks.equal(G.GraphvizColor.White,vertex.FillColor);constructorChecks.isNull(vertex.Font);constructorChecks.equal(G.GraphvizColor.Black,vertex.FontColor);constructorChecks.equal(1.0,vertex.PenWidth);constructorChecks.isNull(vertex.Group);constructorChecks.isNull(vertex.Layer);constructorChecks.zero(vertex.Orientation);constructorChecks.equal(-1,vertex.Peripheries);constructorChecks.isFalse(vertex.Regular);constructorChecks.notNull(vertex.Record);constructorChecks.equal(G.GraphvizVertexShape.Unspecified,vertex.Shape);constructorChecks.equal(4,vertex.Sides);constructorChecks.notNull(vertex.Size);constructorChecks.zero(vertex.Size.Width);constructorChecks.zero(vertex.Size.Height);constructorChecks.isFalse(vertex.FixedSize);constructorChecks.zero(vertex.Skew);constructorChecks.equal(G.GraphvizColor.Black,vertex.StrokeColor);constructorChecks.equal(G.GraphvizVertexStyle.Unspecified,vertex.Style);constructorChecks.equal(-1,vertex.Z);});

// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeTests.cs::Constructor
test("GraphvizEdgeTests.Constructor full property defaults",()=>{const edge=new G.GraphvizEdge();constructorChecks.isNull(edge.Comment);constructorChecks.isFalse(edge.Label.IsHtmlLabel);constructorChecks.notNull(edge.Label);constructorChecks.isNull(edge.ToolTip);constructorChecks.isNull(edge.Url);constructorChecks.equal(G.GraphvizEdgeDirection.Forward,edge.Direction);constructorChecks.isNull(edge.Font);constructorChecks.equal(G.GraphvizColor.Black,edge.FontColor);constructorChecks.equal(1.0,edge.PenWidth);constructorChecks.notNull(edge.Head);constructorChecks.isNull(edge.HeadArrow);constructorChecks.isNull(edge.HeadPort);constructorChecks.notNull(edge.Tail);constructorChecks.isNull(edge.TailArrow);constructorChecks.isNull(edge.TailPort);constructorChecks.isTrue(edge.IsConstrained);constructorChecks.isFalse(edge.IsDecorated);constructorChecks.isNull(edge.Layer);constructorChecks.equal(G.GraphvizColor.Black,edge.StrokeColor);constructorChecks.equal(G.GraphvizEdgeStyle.Unspecified,edge.Style);constructorChecks.equal(1,edge.Weight);constructorChecks.equal(1,edge.Length);constructorChecks.equal(1,edge.MinLength);});

// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizGraphTests.cs::Constructor
test("GraphvizGraphTests.Constructor full property defaults",()=>{const graph=new G.GraphvizGraph();constructorChecks.isNull(graph.Comment);constructorChecks.isNull(graph.Url);constructorChecks.equal(G.GraphvizColor.White,graph.BackgroundColor);constructorChecks.equal(G.GraphvizClusterMode.Local,graph.ClusterRank);constructorChecks.isNull(graph.Font);constructorChecks.equal(G.GraphvizColor.Black,graph.FontColor);constructorChecks.equal(1.0,graph.PenWidth);constructorChecks.isFalse(graph.IsCentered);constructorChecks.isFalse(graph.IsCompounded);constructorChecks.isFalse(graph.IsConcentrated);constructorChecks.isFalse(graph.IsLandscape);constructorChecks.isFalse(graph.IsReMinCross);constructorChecks.isFalse(graph.IsHtmlLabel);constructorChecks.isNull(graph.Label);constructorChecks.equal(G.GraphvizLabelJustification.C,graph.LabelJustification);constructorChecks.notNull(graph.Layers);constructorChecks.equal(1.0,graph.McLimit);constructorChecks.equal(0.25,graph.NodeSeparation);constructorChecks.equal(G.GraphvizRankDirection.TB,graph.RankDirection);constructorChecks.equal(0.5,graph.RankSeparation);constructorChecks.equal(-1,graph.NsLimit);constructorChecks.equal(-1,graph.NsLimit1);constructorChecks.equal(G.GraphvizOutputMode.BreadthFirst,graph.OutputOrder);constructorChecks.equal(G.GraphvizPageDirection.BL,graph.PageDirection);constructorChecks.notNull(graph.PageSize);constructorChecks.zero(graph.PageSize.Width);constructorChecks.zero(graph.PageSize.Height);constructorChecks.zero(graph.Quantum);constructorChecks.equal(G.GraphvizRatioMode.Auto,graph.Ratio);constructorChecks.equal(0.96,graph.Resolution);constructorChecks.zero(graph.Rotate);constructorChecks.equal(8,graph.SamplePoints);constructorChecks.equal(30,graph.SearchSize);constructorChecks.notNull(graph.Size);constructorChecks.zero(graph.Size.Width);constructorChecks.zero(graph.Size.Height);constructorChecks.equal(G.GraphvizSplineType.Spline,graph.Splines);constructorChecks.isNull(graph.StyleSheet);});

// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordCellTests.cs::Constructor
test("GraphvizRecordCellTests.Constructor full property defaults",()=>{const cell=new G.GraphvizRecordCell();constructorChecks.isFalse(cell.HasPort);constructorChecks.isNull(cell.Port);constructorChecks.isFalse(cell.HasText);constructorChecks.isNull(cell.Text);constructorChecks.empty(cell.Cells);});

// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordTests.cs::Constructor
test("GraphvizRecordTests.Constructor full property defaults",()=>{const record=new G.GraphvizRecord();constructorChecks.empty(record.Cells);});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizArrowTests.cs::Constructor
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizArrowTests.cs::ToDot_SkippedModifiers
// Above 66 directly transcribed arrow cases include all upstream skipped-modifier combinations.
test('GraphvizArrowTests.Constructor',()=>{for(const [shape,clipping,filling]of[[G.GraphvizArrowShape.Box,G.GraphvizArrowClipping.None,G.GraphvizArrowFilling.Close],[G.GraphvizArrowShape.Diamond,G.GraphvizArrowClipping.None,G.GraphvizArrowFilling.Close],[G.GraphvizArrowShape.Dot,G.GraphvizArrowClipping.Left,G.GraphvizArrowFilling.Open],[G.GraphvizArrowShape.Normal,G.GraphvizArrowClipping.Right,G.GraphvizArrowFilling.Close]]){const a=new G.GraphvizArrow(shape,clipping,filling);assert.equal(a.Shape,shape);assert.equal(a.Clipping,clipping);assert.equal(a.Filling,filling);}const a=new G.GraphvizArrow(G.GraphvizArrowShape.Box);assert.equal(a.Clipping,G.GraphvizArrowClipping.None);assert.equal(a.Filling,G.GraphvizArrowFilling.Close);});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizColorTests.cs::Constructor
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizColorTests.cs::Equals
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizColorTests.cs::HashCode
test('GraphvizColorTests constructor/value equality/hash',()=>{assert.deepEqual([new G.GraphvizColor().A,new G.GraphvizColor().R,new G.GraphvizColor().G,new G.GraphvizColor().B],[0,0,0,0]);for(const channels of[[250,255,125,45],[125,12,25,42]]){const c=new G.GraphvizColor(...channels);assert.deepEqual([c.A,c.R,c.G,c.B],channels);}const c=new G.GraphvizColor(255,150,160,25),same=new G.GraphvizColor(255,150,160,25);assert.equal(c.Equals(c),true);assert.equal(c.Equals(same),true);for(const channels of[[125,150,160,25],[255,155,160,25],[255,150,120,25],[255,150,160,30]])assert.equal(c.Equals(new G.GraphvizColor(...channels)),false);assert.equal(c.Equals(null),false);assert.equal(c.Equals({}),false);assert.equal(c.GetHashCode(),same.GetHashCode());assert.equal(new G.GraphvizColor().GetHashCode(),0);assert.notEqual(c.GetHashCode(),0);});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizPointTests.cs::Constructor
test('GraphvizPointTests.Constructor',()=>{for(const[x,y]of[[0,0],[10,20],[-2,3],[3,-20]]){const p=new G.GraphvizPoint(x,y);assert.equal(p.X,x);assert.equal(p.Y,y);}});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizSizeTests.cs::Constructor_Size
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizSizeTests.cs::Constructor_SizeF
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizSizeTests.cs::Constructor_SizeThrow
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizSizeTests.cs::Constructor_SizeFThrow
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizSizeTests.cs::ToString_Size
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizSizeTests.cs::ToString_SizeF
for(const Type of[G.GraphvizSize,G.GraphvizSizeF])test(`${Type.name}Tests full size/default/string assertions`,()=>{assert.equal(new Type().ToString(),'0x0');for(const[w,h]of[[0,0],[0,10],[10,0],[10,15],[30,25]]){const s=new Type(w,h);assert.equal(s.Width,w);assert.equal(s.Height,h);assert.equal(s.IsEmpty,w===0||h===0);assert.equal(s.ToString(),`${w}x${h}`);}for(const[w,h]of[[-1,10],[10,-2],[-5,-2]])assert.throws(()=>new Type(w,h));if(Type===G.GraphvizSizeF)assert.equal(new Type(12.2,25.6).ToString(),'12.2x25.6');});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordCellCollectionTests.cs::Constructor
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordCellCollectionTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordCellTests.cs::Cells
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordCellTests.cs::Cells_Throws
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordCellTests.cs::Port
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordCellTests.cs::Text
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordTests.cs::Cells
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizRecordTests.cs::Cells_Throws
test('Record collections, cells, port and text property semantics',()=>{const cells=new G.GraphvizRecordCellCollection(),first=new G.GraphvizRecordCell();assert.equal(cells.Count,0);cells.Add(first);assert.deepEqual([...cells],[first]);assert.deepEqual([...new G.GraphvizRecordCellCollection(cells)],[first]);assert.deepEqual([...new G.GraphvizRecordCellCollection([first])],[first]);assert.throws(()=>new G.GraphvizRecordCellCollection(null));for(const record of[new G.GraphvizRecord(),first]){record.Cells=cells;assert.equal(record.Cells,cells);assert.throws(()=>{record.Cells=null;});}for(const property of['Port','Text']){const cell=new G.GraphvizRecordCell();for(const v of[null,'']){cell[property]=v;assert.equal(cell['Has'+property],false);assert.equal(cell[property],v);}cell[property]='Test'+property;assert.equal(cell['Has'+property],true);assert.equal(cell[property],'Test'+property);}});
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizVertexTests.cs::ToDot_InvariantCulture
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizEdgeTests.cs::ToDot_InvariantCulture
// upstream: tests/QuikGraph.Graphviz.Tests/Dot/GraphvizGraphTests.cs::ToDot_InvariantCulture
test('DOT numeric properties retain invariant decimal separators',()=>{const vertex=new G.GraphvizVertex(),edge=new G.GraphvizEdge(),graph=new G.GraphvizGraph();vertex.PenWidth=0.25;edge.Weight=12.5;graph.RankSeparation=0.75;assert.equal(vertex.ToDot(),'penwidth=0.25');assert.equal(edge.ToDot(),'weight=12.5');assert.equal(graph.ToDot(),'ranksep=0.75');assert.equal(vertex.ToString(),vertex.ToDot());assert.equal(edge.ToString(),edge.ToDot());assert.equal(graph.ToString(),graph.ToDot());});
// upstream: tests/QuikGraph.Graphviz.Tests/Extensions/BasicStructuresExtensionsTests.cs::ToFont
// upstream: tests/QuikGraph.Graphviz.Tests/Extensions/BasicStructuresExtensionsTests.cs::ToGraphvizFont
test('BasicStructuresExtensions font roundtrip with host construction adapter',()=>{assert.equal(G.BasicStructuresExtensions.ToFont(null),null);assert.equal(G.BasicStructuresExtensions.ToGraphvizFont(null),null);for(const[name,size]of[['Arial',12],['Tahoma',8.25]]){const portable=new G.GraphvizFont(name,size),native=G.BasicStructuresExtensions.ToFont(portable,(Name,SizeInPoints)=>({Name,SizeInPoints}));const copy=G.BasicStructuresExtensions.ToGraphvizFont(native);assert.equal(copy.Name,name);assert.equal(copy.SizeInPoints,size);}});
// upstream: tests/QuikGraph.Graphviz.Tests/FileFotEngineTests.cs::Run_Throws
test('FileDotEngineTests.Run_Throws',()=>{const engine=new G.FileDotEngine(()=>{});for(const dot of[null,''])for(const path of[null,'','file'])assert.throws(()=>engine.Run('png',dot,path));for(const path of[null,''])assert.throws(()=>engine.Run('png','graph {}',path));});
