import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as Q from '../src/index.js';
import {createFixtureRegistry,NrbfTestVertex,NrbfTestEdge} from './nrbf-test-schemas.js';
const folder=new URL('./fixtures/nrbf/',import.meta.url),manifest=JSON.parse(readFileSync(new URL('manifest.json',folder),'utf8')),registry=createFixtureRegistry();
const read=name=>readFileSync(new URL(name+'.nrbf',folder));
function snapshot(value){if(value==null)return null;if(typeof value==='bigint')return String(value);if(typeof value==='number')return Number.isFinite(value)?value:String(value);if(typeof value!=='object')return value;if(value instanceof Q.NrbfDecimal)return {decimalValue:value.Value};if(value instanceof Q.NrbfDateTime)return {dateTimeTicks:String(value.Ticks),kind:['Unspecified','Utc','Local','Local'][value.Kind]};if(value instanceof Q.NrbfPrimitive)return value.Type===Q.NrbfPrimitiveType.TimeSpan?{timeSpanTicks:String(value.Value)}:snapshot(value.Value);if(value instanceof NrbfTestVertex)return {id:value.ID,text:value.String,number:value.Int,integer64:String(value.Long),boolean:value.Bool,single:value.Float,number64:value.Double,array:snapshot(value.IntArray),list:snapshot(value.IntIList)};if(value.Vertices&&value.Edges){const result={vertices:value.Vertices.map(snapshot),edges:value.Edges.map(snapshot),directed:value.IsDirected,parallel:value.AllowParallelEdges};if(value.Clusters)result.clusters=value.Clusters.map(snapshot);return result;}if(value instanceof Q.Edge){const result={source:snapshot(value.Source),target:snapshot(value.Target)};if('Tag'in value)result.tag=snapshot(value.Tag);if('SourceTerminal'in value){result.sourceTerminal=value.SourceTerminal;result.targetTerminal=value.TargetTerminal;}if(value instanceof NrbfTestEdge)Object.assign(result,{id:value.ID,text:value.String,number:value.Int,integer64:String(value.Long),number64:value.Double,boolean:value.Bool,single:value.Float});return result;}if(value instanceof Error)return {type:value.ClrTypeName?.split('.').at(-1)??value.name,message:value.message,inner:snapshot(value.cause)};if(value instanceof Q.GraphvizColor)return {a:value.A,r:value.R,g:value.G,b:value.B};if(value instanceof Q.GraphvizSizeF)return {width:value.Width,height:value.Height};if(value instanceof Q.EqualityMap)return Array.from(value,([k,v])=>({key:snapshot(k),value:snapshot(v)}));if(Array.isArray(value)){const shape=value.NrbfShape,raw=Q.GetNrbfMetadata(value);const values=raw?.ElementType?.primitive===Q.NrbfPrimitiveType.TimeSpan?value.map(v=>({timeSpanTicks:String(v)})):value.map(snapshot);return shape&&(shape.lengths.length>1||shape.lowerBounds.some(n=>n!==0))?{lengths:shape.lengths,lowerBounds:shape.lowerBounds,values}:values;}if(value instanceof Q.Queue)return value.ToArray().map(snapshot);throw new Error('Missing snapshot '+value.constructor.name);}
function assertFixture(value,fixture){if(fixture.name==='identity-cycles'){assert.equal(value[0],value);assert.equal(value[1],value[2]);assert.deepEqual(snapshot(value[1]),fixture.expected.graph);return;}let expected=fixture.expected;if(fixture.name==='array-single')expected=expected.map(v=>typeof v==='number'?Math.fround(v):v);assert.deepEqual(snapshot(value),expected);}
for(const fixture of manifest.fixtures){test(`NRBF genuine .NET fixture ${fixture.name}: bytes, data and JS reserialization`,()=>{const bytes=readFileSync(new URL(fixture.file,folder));assert.equal(createHash('sha256').update(bytes).digest('hex'),fixture.sha256);const raw=Q.DecodeNrbf(bytes);assert.ok(raw.Objects.size>0);const value=Q.DeserializeNrbf(raw,{registry});assertFixture(value,fixture);assertFixture(Q.DeserializeNrbf(Q.SerializeNrbf(value,{registry}),{registry}),fixture);});}
const methodFixtures={BinarySerialization_AdjacencyGraph_Simple:['adjacency-int','array-adjacency-int','adjacency-empty'],BinarySerialization_AdjacencyGraph_Complex:['adjacency-custom','array-adjacency-custom'],BinarySerialization_AdapterGraph_Simple:['bidirectional-adapter-int'],BinarySerialization_AdapterGraph_Complex:['bidirectional-adapter-custom'],BinarySerialization_ClusteredGraph_Simple:['clustered-int'],BinarySerialization_ClusteredGraph_Complex:['clustered-custom'],BinarySerialization_CompressedGraph_Simple:['compressed-int'],BinarySerialization_CompressedGraph_Complex:['compressed-custom'],BinarySerialization_BidirectionalGraph_Simple:['bidirectional-int','array-bidirectional-int','reversed-bidirectional-int','undirected-bidirectional-int'],BinarySerialization_BidirectionalGraph_Complex:['bidirectional-custom','array-bidirectional-custom','reversed-bidirectional-custom','undirected-bidirectional-custom'],BinarySerialization_BidirectionalMatrixGraph:['matrix-int'],BinarySerialization_UndirectedGraph_Simple:['undirected-int','array-undirected-int'],BinarySerialization_UndirectedGraph_Complex:['undirected-custom','array-undirected-custom'],BinarySerialization_EdgeListGraph_Simple:['edge-list-graph-int'],BinarySerialization_EdgeListGraph_Complex:['edge-list-graph-custom']};
for(const [method,names]of Object.entries(methodFixtures))test(`BinarySerializationTests.${method} actual NRBF graph contract`,()=>{for(const name of names){const before=Q.DeserializeNrbfGraph(read(name),{registry});let bytes;const formatter=new Q.QuikGraphNrbfFormatter({registry});Q.SerializeToBinary(before,{Write:b=>{bytes=b;}},formatter);const after=Q.DeserializeFromBinary(bytes,formatter);assert.equal(after.constructor,before.constructor);assert.deepEqual(snapshot(after),snapshot(before));}});
for(const [fixture,method]of [['graphviz-color','GraphvizColorTests.Serialization'],['graphviz-size','GraphvizSizeTests.Serialization_Size'],['graphviz-size-f','GraphvizSizeTests.Serialization_SizeF'],['edge-edge-dictionary','EdgeEdgeDictionaryTests.Serialization'],['vertex-edge-dictionary','VertexEdgeDictionaryTests.Serialization']])test(method+' actual BinaryFormatter wire roundtrip',()=>{const before=Q.DeserializeNrbf(read(fixture));assert.deepEqual(snapshot(Q.DeserializeNrbf(Q.SerializeNrbf(before))),snapshot(before));});
test('ExceptionTests.ExceptionsSerialization preserves CLR exception strings and inner state',()=>{for(const name of ['negative-cycle-exception','non-acyclic-exception','non-strongly-connected-exception','parallel-edge-exception','vertex-not-found-exception','no-path-exception']){const a=Q.DeserializeNrbf(read(name)),b=Q.DeserializeNrbf(Q.SerializeNrbf(a));assert.equal(b.ToString(),a.ToString());assert.equal(b.HResult,a.HResult);assert.equal(b.constructor,a.constructor);}assert.equal(Q.DeserializeNrbf(read('negative-cycle-exception')).ToString(),'QuikGraph.NegativeCycleGraphException: negative cycle ---> System.InvalidOperationException: inner\n   --- End of inner exception stack trace ---');});
test('NRBF graph import canonicalizes registered custom endpoints and cluster parent cycles',()=>{const g=Q.DeserializeNrbfGraph(read('adjacency-custom'),{registry});assert.ok(g.Vertices.every(v=>v instanceof NrbfTestVertex));assert.ok(g.Edges.every(e=>g.Vertices.includes(e.Source)&&g.Vertices.includes(e.Target)));const equal=Object.assign(new NrbfTestVertex(),{ID:g.Vertices[0].ID});assert.equal(g.ContainsVertex(equal),true);const c=Q.DeserializeNrbfGraph(read('clustered-int'));assert.equal(c.Clusters[0].Parent,c);assert.equal(c.Clusters[0].Clusters[0].Parent,c.Clusters[0]);});
test('NRBF graph materialization rejects unknown user code and corrupt graph counts',()=>{assert.throws(()=>Q.DeserializeNrbfGraph(read('adjacency-custom')),/Register an explicit schema/);const raw=Q.DecodeNrbf(read('adjacency-int'));raw.Root.Members['<EdgeCount>k__BackingField']=999;assert.throws(()=>Q.DeserializeNrbfGraph(raw),/edge count/);assert.throws(()=>Q.DeserializeNrbfGraph(Q.EncodeNrbf('hello')),/not a supported/);});
test('NRBF fresh collections preserve subsequent mutations and empty generic edge lists',()=>{const e=new Q.EquatableEdge(1,2),d=new Q.VertexEdgeDictionary([[1,new Q.EdgeList([e])],[2,new Q.EdgeList()]]);const copy=Q.DeserializeNrbf(Q.SerializeNrbf(d));assert.equal(copy.get(1)[0].Target,2);assert.equal(copy.get(2).Count,0);copy.get(2).Add(new Q.EquatableEdge(2,3));const next=Q.DeserializeNrbf(Q.SerializeNrbf(copy));assert.equal(next.get(2)[0].Target,3);const queue=Q.DeserializeNrbf(read('queue'));queue.Enqueue(13);assert.deepEqual(Q.DeserializeNrbf(Q.SerializeNrbf(queue)).ToArray(),[5,8,13]);});
test('NRBF fresh string tagged graph, no parallel graph and fixed matrix survive binary import',()=>{const g=new Q.BidirectionalGraph(false);g.AddVertex('isolated');g.AddVerticesAndEdge(new Q.TaggedEdge('α','😀',2.5));const copy=Q.DeserializeNrbfGraph(Q.SerializeNrbfGraph(g));assert.equal(copy.AllowParallelEdges,false);assert.equal(copy.Edges[0].Tag,2.5);assert.equal(copy.ContainsVertex('isolated'),true);const m=new Q.BidirectionalMatrixGraph(3);m.AddEdge(new Q.Edge(2,0));assert.equal(Q.DeserializeNrbfGraph(Q.SerializeNrbfGraph(m)).TryGetEdge(2,0).Target,0);});
test('NRBF native memory stream respects positions, partial reads, zero fill, length and disposal',()=>{const stream=new Q.NrbfMemoryStream(),g=new Q.AdjacencyGraph();g.AddVerticesAndEdge(new Q.Edge(1,2));Q.SerializeToBinary(g,stream);assert.equal(stream.Position,stream.Length);stream.Position=0;assert.equal(Q.DeserializeFromBinary(stream).EdgeCount,1);assert.equal(stream.Position,stream.Length);stream.SetLength(2);stream.Seek(4,'Begin');stream.Write(new Uint8Array([9]));assert.deepEqual([...stream.ToArray().slice(2)],[0,0,9]);stream.Dispose();assert.equal(stream.CanRead,false);assert.throws(()=>stream.Read(new Uint8Array(2),0,2),/closed/);assert.equal(stream.ToArray().length,5);});
test('NRBF graph input rejects allocation amplification and graph dependency cycles',()=>{const matrix=Q.DecodeNrbf(read('matrix-int'));matrix.Root.Members['<VertexCount>k__BackingField']=2147483647;assert.throws(()=>Q.DeserializeNrbfGraph(matrix),/matrix graph shape/);const csr=Q.DecodeNrbf(read('compressed-int'));const pairs=csr.Root.Members._outEdgeStartRanges.Members.KeyValuePairs.Values;pairs[1].Members.value.Members.Start=0;assert.throws(()=>Q.DeserializeNrbfGraph(csr),/CSR offsets/);assert.throws(()=>Q.DeserializeNrbfGraph(read('adjacency-int'),{maxGraphVertices:2}),/allocation limit/);assert.throws(()=>Q.DeserializeNrbfGraph(read('adjacency-int'),{maxGraphEdges:2}),/allocation limit/);const view=Q.DecodeNrbf(read('reversed-bidirectional-int'));view.Root.Members['<OriginalGraph>k__BackingField']=view.Root;assert.throws(()=>Q.DeserializeNrbfGraph(view),/wrapped graph/);});
test('NRBF custom schema serialization reserves objects before cyclic member conversion',()=>{class Node{constructor(name){this.name=name;this.next=null;}}const r=new Q.NrbfTypeRegistry().Register('App.Node',{library:'App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null',matches:v=>v instanceof Node,create:()=>Object.create(Node.prototype),populate:(target,members)=>Object.assign(target,members),serialize:(value,convert,record)=>{record.Members.name=value.name;record.Members.next=convert(value.next);return record;}});const node=new Node('cycle');node.next=node;const result=Q.DeserializeNrbf(Q.SerializeNrbf(node,{registry:r}),{registry:r});assert.ok(result instanceof Node);assert.equal(result.next,result);assert.equal(result.name,'cycle');});
test('NRBF full-width vertices and floating tags use a consistent CLR generic type',()=>{const g=new Q.AdjacencyGraph();g.AddVerticesAndEdge(new Q.TaggedEdge(1,2.5,1));g.AddVerticesAndEdge(new Q.TaggedEdge(2.5,4,1.25));const copy=Q.DeserializeNrbfGraph(Q.SerializeNrbfGraph(g));assert.deepEqual(copy.Edges.map(e=>[e.Source,e.Target,e.Tag]),[[1,2.5,1],[2.5,4,1.25]]);});
