import test from 'node:test';
import assert from 'node:assert/strict';
import { AdjacencyGraph, UndirectedGraph, Edge, TaggedEdge, EventHook, GraphColor } from '../src/core.js';
import { DistanceRelaxers } from '../src/algorithm-base.js';
import { DepthFirstSearchAlgorithm, EdgeDepthFirstSearchAlgorithm, UndirectedDepthFirstSearchAlgorithm } from '../src/search.js';
import { DijkstraShortestPathAlgorithm, UndirectedDijkstraShortestPathAlgorithm } from '../src/shortest-paths.js';
import * as O from '../src/observers.js';
function graph(rows,vertices=[],Type=AdjacencyGraph){const g=new Type();g.AddVertexRange(vertices);g.AddVerticesAndEdgeRange(rows.map(row=>new Edge(...row)));return g;}
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexTimeStamperObserverTests.cs::Attach
for(const [rows,vertices,discover,finish]of [[[],[],[],[]],[[],[1,2],[[1,0],[2,2]],[[1,1],[2,3]]],[[[1,2],[2,2],[3,4]],[],[[1,0],[2,1],[3,4],[4,5]],[[2,2],[1,3],[4,6],[3,7]]]])test(`VertexTimeStamperObserverTests.Attach fixture ${JSON.stringify(rows)} ${vertices}`,()=>{const a=new DepthFirstSearchAlgorithm(graph(rows,vertices)),r=new O.VertexTimeStamperObserver(),sub=r.Attach(a);a.Compute();sub.Dispose();assert.deepEqual([...r.DiscoverTimes],discover);assert.deepEqual([...r.FinishTimes],finish);});
test('VertexTimeStamperObserverTests.Constructor discover-only overload',()=>{const times=new Map(),r=new O.VertexTimeStamperObserver(times),a=new DepthFirstSearchAlgorithm(graph([[1,2]]));r.Attach(a);a.Compute();assert.equal(r.DiscoverTimes,times);assert.equal(r.FinishTimes,null);assert.deepEqual([...times],[[1,0],[2,1]]);});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexPredecessorRecorderObserverTests.cs::Attach
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexPredecessorRecorderObserverTests.cs::TryGetPath
for(const cycle of [false,true])test(`VertexPredecessorRecorderObserverTests.Attach / TryGetPath cycle=${cycle}`,()=>{const rows=[[1,2],[1,3],[1,4],[2,4],[3,1],[3,3],[3,4]];if(cycle)rows.push([4,1]);const g=graph(rows),a=new DepthFirstSearchAlgorithm(g),r=new O.VertexPredecessorRecorderObserver();r.Attach(a);a.Compute();assert.deepEqual([...r.VerticesPredecessors].map(([v,e])=>[v,e.Source,e.Target]),[[2,1,2],[4,2,4],[3,1,3]]);assert.deepEqual(r.TryGetPath(4).map(e=>[e.Source,e.Target]),[[1,2],[2,4]]);assert.equal(r.TryGetPath(1),undefined);assert.equal(r.TryGetPath(9),undefined);});
// Upstream .../VertexPredecessorPathRecorderObserverTests.cs::AllPaths
test('VertexPredecessorPathRecorderObserver records leaf paths',()=>{const g=graph([[1,2],[1,3],[2,4],[2,5],[3,1]],[9]),a=new DepthFirstSearchAlgorithm(g),r=new O.VertexPredecessorPathRecorderObserver();r.Attach(a);a.Compute();assert.deepEqual(r.EndPathVertices,[9,4,5,3]);assert.deepEqual([...r.AllPaths()].map(path=>path.map(e=>[e.Source,e.Target])),[[[1,2],[2,4]],[[1,2],[2,5]],[[1,3]]]);});
test('UndirectedVertexPredecessorRecorderObserver reversed path order',()=>{const g=graph([[0,1],[1,2]],[],UndirectedGraph),a=new UndirectedDepthFirstSearchAlgorithm(g),r=new O.UndirectedVertexPredecessorRecorderObserver();r.Attach(a);a.Compute(2);assert.deepEqual(r.TryGetPath(0).map(e=>[e.Source,e.Target]),[[1,2],[0,1]]);assert.equal(r.TryGetPath(2),undefined);});
test('VertexDistanceRecorderObserver upstream relaxer and dictionary constructors',()=>{const edge=new TaggedEdge(1,2,7),algorithm={TreeEdge:new EventHook()},distances=new Map([[1,11]]),r=new O.VertexDistanceRecorderObserver(e=>e.Tag,DistanceRelaxers.ShortestDistance,distances);r.Attach(algorithm);algorithm.TreeEdge.emit(edge);assert.equal(r.Distances,distances);assert.equal(r.EdgeWeights(edge),7);assert.equal(distances.get(2),18);});
for(const undirected of [false,true])test(`distance observer records final relaxed paths undirected=${undirected}`,()=>{const g=new(undirected?UndirectedGraph:AdjacencyGraph)();g.AddVerticesAndEdgeRange([[0,1,9],[0,2,1],[1,2,1],[1,3,2]].map(row=>new TaggedEdge(...row)));if(!undirected)g.AddEdge(new TaggedEdge(2,1,1));const a=new(undirected?UndirectedDijkstraShortestPathAlgorithm:DijkstraShortestPathAlgorithm)(g,e=>e.Tag),r=new(undirected?O.UndirectedVertexDistanceRecorderObserver:O.VertexDistanceRecorderObserver)(e=>e.Tag);r.Attach(a);a.Compute(0);assert.equal(r.Distances.get(3),4);});
test('EdgePredecessorRecorderObserver Path / AllPaths / AllMergedPaths',()=>{const g=graph([[0,1],[1,2],[1,3],[2,4]]),a=new EdgeDepthFirstSearchAlgorithm(g),r=new O.EdgePredecessorRecorderObserver();r.Attach(a);a.Compute(0);const paths=[...r.AllPaths()];assert.deepEqual(paths.map(path=>path.map(e=>[e.Source,e.Target])),[[[0,1],[1,2],[2,4]],[[0,1],[1,3]]]);const merged=[...r.AllMergedPaths()].flat();assert.equal(merged.length,4);assert.equal(new Set(merged).size,4);});
test('EdgePredecessorRecorderObserver single-edge merged path',()=>{const g=graph([[0,1]]),a=new EdgeDepthFirstSearchAlgorithm(g),r=new O.EdgePredecessorRecorderObserver();r.Attach(a);a.Compute();assert.deepEqual([...r.AllMergedPaths()],[[g.Edges[0]]]);});
test('observers detach idempotently without removing other subscriptions',()=>{const g=graph([[0,1],[1,2]]),a=new DepthFirstSearchAlgorithm(g),one=new O.VertexRecorderObserver(),two=new O.VertexRecorderObserver(),sub=one.Attach(a);two.Attach(a);a.Compute();sub.Dispose();sub.dispose();sub.unsubscribe();a.Compute();assert.deepEqual(one.Vertices,[0,1,2]);assert.deepEqual(two.Vertices,[0,1,2,0,1,2]);});
test('EdgeRecorderObserver preserves supplied records and discovered edge identities',()=>{const g=graph([[0,1],[1,2]]),extra=new Edge(4,5),r=new O.EdgeRecorderObserver([extra]),a=new DepthFirstSearchAlgorithm(g);r.Attach(a);a.Compute();assert.deepEqual(r.Edges,[extra,...g.Edges]);});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexPredecessorRecorderObserverTests.cs::Attach_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexPredecessorRecorderObserverTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/UndirectedVertexPredecessorRecorderObserverTests.cs::Attach_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/UndirectedVertexPredecessorRecorderObserverTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexPredecessorPathRecorderObserverTests.cs::Attach_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexPredecessorPathRecorderObserverTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgePredecessorRecorderObserverTests.cs::Attach_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgePredecessorRecorderObserverTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexTimeStamperObserverTests.cs::Attach_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexTimeStamperObserverTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexRecorderObserverTests.cs::Attach_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexRecorderObserverTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgeRecorderObserverTests.cs::Attach_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgeRecorderObserverTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexDistanceRecorderObserverTests.cs::Attach_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexDistanceRecorderObserverTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/UndirectedVertexDistanceRecorderObserverTests.cs::Attach_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/UndirectedVertexDistanceRecorderObserverTests.cs::Constructor_Throws
for(const [Observer,args]of [[O.VertexPredecessorRecorderObserver,[]],[O.UndirectedVertexPredecessorRecorderObserver,[]],[O.VertexPredecessorPathRecorderObserver,[]],[O.EdgePredecessorRecorderObserver,[]],[O.VertexTimeStamperObserver,[]],[O.VertexRecorderObserver,[]],[O.EdgeRecorderObserver,[]],[O.VertexDistanceRecorderObserver,[()=>1]],[O.UndirectedVertexDistanceRecorderObserver,[()=>1]]]){
  test(`${Observer.name}.Attach_Throws`,()=>{const r=new Observer(...args);assert.throws(()=>r.Attach(null),TypeError);});
  test(`${Observer.name}.Constructor_Throws`,()=>{assert.throws(()=>new Observer(null),TypeError);});
}
test('predecessor maps reject cycles instead of hanging',()=>{const e01=new Edge(0,1),e10=new Edge(1,0),r=new O.VertexPredecessorRecorderObserver(new Map([[0,e10],[1,e01]]));assert.throws(()=>r.TryGetPath(0),/cycle/);const er=new O.EdgePredecessorRecorderObserver(new Map([[e01,e10],[e10,e01]]));assert.throws(()=>er.Path(e01),/cycle/);});

// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexPredecessorRecorderObserverTests.cs::Constructor
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/UndirectedVertexPredecessorRecorderObserverTests.cs::Constructor
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexPredecessorPathRecorderObserverTests.cs::Constructor
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgePredecessorRecorderObserverTests.cs::Constructor
for(const Observer of [O.VertexPredecessorRecorderObserver,O.UndirectedVertexPredecessorRecorderObserver,O.VertexPredecessorPathRecorderObserver,O.EdgePredecessorRecorderObserver])test(`${Observer.name}.Constructor full dictionary branches`,()=>{const property=Observer===O.EdgePredecessorRecorderObserver?'EdgesPredecessors':'VerticesPredecessors';assert.equal(new Observer()[property].size,0);for(const map of [new Map(),new Map([[Observer===O.EdgePredecessorRecorderObserver?new Edge(3,2):1,new Edge(2,1)]])]){const r=new Observer(map);assert.equal(r[property],map);if(r.EndPathVertices)assert.deepEqual(r.EndPathVertices,[]);if(r.EndPathEdges)assert.deepEqual(r.EndPathEdges,[]);}});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexRecorderObserverTests.cs::Constructor
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgeRecorderObserverTests.cs::Constructor
test('sequence recorder constructors preserve all initial entries',()=>{assert.deepEqual(new O.VertexRecorderObserver().Vertices,[]);assert.deepEqual(new O.VertexRecorderObserver([1,2,3]).Vertices,[1,2,3]);assert.deepEqual(new O.EdgeRecorderObserver().Edges,[]);const edges=[[1,2],[2,2],[3,1]].map(e=>new Edge(...e));assert.deepEqual(new O.EdgeRecorderObserver(edges).Edges,edges);});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexTimeStamperObserverTests.cs::Constructor
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexTimeStamperObserverTests.cs::Constructor_Throws
test('timestamp constructor complete map and null branches',()=>{const r=new O.VertexTimeStamperObserver();assert.equal(r.DiscoverTimes.size,0);assert.equal(r.FinishTimes.size,0);for(const discover of [new Map(),new Map([[1,0],[2,1],[3,3],[4,2]])]){const one=new O.VertexTimeStamperObserver(discover);assert.equal(one.DiscoverTimes,discover);assert.equal(one.FinishTimes,null);for(const finish of [new Map(),new Map([[1,4],[2,6],[3,5],[4,7]])]){const two=new O.VertexTimeStamperObserver(discover,finish);assert.equal(two.DiscoverTimes,discover);assert.equal(two.FinishTimes,finish);}}for(const args of [[null],[new Map(),null],[null,new Map()],[null,null]])assert.throws(()=>new O.VertexTimeStamperObserver(...args),TypeError);});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexDistanceRecorderObserverTests.cs::Constructor
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexDistanceRecorderObserverTests.cs::Constructor_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/UndirectedVertexDistanceRecorderObserverTests.cs::Constructor
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/UndirectedVertexDistanceRecorderObserverTests.cs::Constructor_Throws
for(const Observer of [O.VertexDistanceRecorderObserver,O.UndirectedVertexDistanceRecorderObserver])test(`${Observer.name} complete constructor branches`,()=>{const weights=()=>1,one=new Observer(weights);assert.equal(one.EdgeWeights,weights);assert.ok(one.DistanceRelaxer);assert.ok(one.Distances);const distances=new Map(),two=new Observer(weights,DistanceRelaxers.ShortestDistance,distances);assert.equal(two.EdgeWeights,weights);assert.equal(two.DistanceRelaxer,DistanceRelaxers.ShortestDistance);assert.equal(two.Distances,distances);for(let mask=1;mask<8;mask++){const args=[weights,DistanceRelaxers.ShortestDistance,new Map()].map((value,i)=>mask&(1<<i)?null:value);assert.throws(()=>new Observer(...args),TypeError);}});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexRecorderObserverTests.cs::Attach
for(const [rows,vertices,initial,expected]of [[[],[],[],[]],[[],[1,2],[],[1,2]],[[],[1,2],[1],[1,1,2]],[[[1,2],[2,2],[3,4]],[],[],[1,2,3,4]]])test(`VertexRecorderObserver.Attach all fixtures ${JSON.stringify([rows,vertices,initial])}`,()=>{const r=new O.VertexRecorderObserver(initial),a=new DepthFirstSearchAlgorithm(graph(rows,vertices));const sub=r.Attach(a);a.Compute();sub.Dispose();assert.deepEqual(r.Vertices,expected);});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgeRecorderObserverTests.cs::Attach
for(const [rows,vertices,initialIndices,expectedIndices]of [[[],[],[],[]],[[],[1,2],[],[]],[[[1,2],[2,3]],[],[0],[0,0,1]],[[[1,2],[3,2]],[],[],[0]],[[[1,2],[2,2],[2,3],[3,4]],[],[],[0,2,3]]])test(`EdgeRecorderObserver.Attach all fixtures ${JSON.stringify([rows,vertices])}`,()=>{const g=graph(rows,vertices),edges=g.Edges,r=new O.EdgeRecorderObserver(initialIndices.map(i=>edges[i])),a=new DepthFirstSearchAlgorithm(g);const sub=r.Attach(a);a.Compute();sub.Dispose();assert.deepEqual(r.Edges,expectedIndices.map(i=>edges[i]));});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexDistanceRecorderObserverTests.cs::Attach
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexPredecessorPathRecorderObserverTests.cs::Attach
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexPredecessorPathRecorderObserverTests.cs::AllPaths
for(const variant of ['empty','vertices','acyclic','cyclic'])test(`directed observer Attach/AllPaths complete fixture ${variant}`,()=>{const rows=variant==='empty'||variant==='vertices'?[]:[[1,2],[1,3],[1,4],[2,4],[3,1],[3,3],[3,4]];if(variant==='cyclic')rows.push([4,1]);const g=graph(rows,variant==='vertices'?[1,2]:[]),a=new DepthFirstSearchAlgorithm(g),d=new O.VertexDistanceRecorderObserver(()=>1),r=new O.VertexPredecessorPathRecorderObserver();d.Attach(a);r.Attach(a);a.Compute();if(!rows.length){assert.equal(d.Distances.size,0);assert.equal(r.VerticesPredecessors.size,0);assert.deepEqual(r.EndPathVertices,variant==='vertices'?[1,2]:[]);assert.deepEqual([...r.AllPaths()],[]);}else{assert.deepEqual(d.Distances,new Map([[1,0],[2,1],[3,1],[4,2]]));assert.deepEqual(new Set(r.EndPathVertices),new Set([3,4]));assert.deepEqual(new Set([...r.AllPaths()].map(p=>p.map(e=>`${e.Source}${e.Target}`).join(','))),new Set(['13','12,24']));}});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/UndirectedVertexDistanceRecorderObserverTests.cs::Attach
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/UndirectedVertexPredecessorRecorderObserverTests.cs::Attach
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/UndirectedVertexPredecessorRecorderObserverTests.cs::TryGetPath
for(const variant of ['empty','vertices','graph'])test(`undirected observer Attach/TryGetPath complete fixture ${variant}`,()=>{const g=graph(variant==='graph'?[[1,2],[1,4],[3,1],[3,3],[3,4],[4,2]]:[],variant==='vertices'?[1,2]:[],UndirectedGraph),a=new UndirectedDepthFirstSearchAlgorithm(g),d=new O.UndirectedVertexDistanceRecorderObserver(()=>1),r=new O.UndirectedVertexPredecessorRecorderObserver();d.Attach(a);r.Attach(a);a.Compute();if(variant!=='graph'){assert.equal(d.Distances.size,0);assert.equal(r.VerticesPredecessors.size,0);assert.equal(r.TryGetPath(2),undefined);}else{assert.deepEqual(d.Distances,new Map([[1,0],[2,1],[3,3],[4,2]]));assert.deepEqual([...r.VerticesPredecessors].map(([v,e])=>[v,e.Source,e.Target]).sort(),[[2,1,2],[3,3,4],[4,4,2]]);assert.deepEqual(r.TryGetPath(4).map(e=>[e.Source,e.Target]),[[1,2],[4,2]]);}});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/VertexPredecessorRecorderObserverTests.cs::TryGetPath_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/UndirectedVertexPredecessorRecorderObserverTests.cs::TryGetPath_Throws
test('predecessor TryGetPath null argument branches',()=>{assert.throws(()=>new O.VertexPredecessorRecorderObserver().TryGetPath(null),TypeError);assert.throws(()=>new O.UndirectedVertexPredecessorRecorderObserver().TryGetPath(null),TypeError);});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgePredecessorRecorderObserverTests.cs::Attach
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgePredecessorRecorderObserverTests.cs::Path
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgePredecessorRecorderObserverTests.cs::AllPaths
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgePredecessorRecorderObserverTests.cs::MergedPath
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgePredecessorRecorderObserverTests.cs::AllMergedPath
for(const variant of ['empty','vertices','acyclic','cyclic'])test(`edge predecessor complete fixture ${variant}`,()=>{const rows=variant==='empty'||variant==='vertices'?[]:[[1,2],[1,3],[1,4],[2,4],[3,1],[3,3],[3,4]];if(variant==='cyclic')rows.push([4,1]);const g=graph(rows,variant==='vertices'?[1,2]:[]),a=new EdgeDepthFirstSearchAlgorithm(g),r=new O.EdgePredecessorRecorderObserver();r.Attach(a);a.Compute();const encode=path=>path.map(e=>`${e.Source}${e.Target}`).join(',');if(!rows.length){assert.equal(r.EdgesPredecessors.size,0);assert.deepEqual(r.EndPathEdges,[]);assert.deepEqual([...r.AllPaths()],[]);assert.deepEqual([...r.AllMergedPaths()],[]);const edge=new Edge(1,2);assert.deepEqual(r.Path(edge),[edge]);const colors=new Map([[edge,GraphColor.Black]]);assert.deepEqual(r.MergedPath(edge,colors),[]);colors.set(edge,GraphColor.White);assert.deepEqual(r.MergedPath(edge,colors),[edge]);}else{const cyclic=variant==='cyclic',byName=new Map(g.Edges.map(e=>[`${e.Source}${e.Target}`,e]));assert.deepEqual(new Map([...r.EdgesPredecessors].map(([e,p])=>[`${e.Source}${e.Target}`,`${p.Source}${p.Target}`])),new Map(cyclic?[['13','41'],['14','31'],['24','12'],['31','13'],['33','13'],['34','33'],['41','24']]:[['14','31'],['24','12'],['31','13'],['33','13'],['34','33']]));assert.deepEqual(new Set(r.EndPathEdges.map(e=>`${e.Source}${e.Target}`)),new Set(cyclic?['14','34']:['14','24','34']));assert.equal(encode(r.Path(byName.get('14'))),cyclic?'12,24,41,13,31,14':'13,31,14');assert.equal(encode(r.Path(byName.get('33'))),cyclic?'12,24,41,13,33':'13,33');assert.deepEqual(new Set([...r.AllPaths()].map(encode)),new Set(cyclic?['12,24,41,13,31,14','12,24,41,13,33,34']:['12,24','13,31,14','13,33,34']));assert.deepEqual(new Set([...r.AllMergedPaths()].map(encode)),new Set(cyclic?['12,24,41,13,31,14','33,34']:['12,24','13,31,14','33,34']));const colors=new Map(g.Edges.map(e=>[e,GraphColor.White])),end=byName.get(cyclic?'41':'24');assert.equal(encode(r.MergedPath(end,colors)),cyclic?'12,24,41':'12,24');assert.deepEqual(r.MergedPath(end,colors),[]);assert.equal(encode(r.MergedPath(byName.get(cyclic?'34':'31'),colors)),cyclic?'13,33,34':'13,31');}});
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgePredecessorRecorderObserverTests.cs::Path_Throws
// upstream: tests/QuikGraph.Tests/Algorithms/Observers/EdgePredecessorRecorderObserverTests.cs::MergedPath_Throws
test('edge predecessor null and missing-color argument branches',()=>{const r=new O.EdgePredecessorRecorderObserver();assert.throws(()=>r.Path(null),TypeError);for(const args of [[null,new Map()],[new Edge(1,2),null],[null,null]])assert.throws(()=>r.MergedPath(...args),TypeError);assert.throws(()=>r.MergedPath(new Edge(1,2),new Map()),{name:'KeyNotFoundException'});});
