// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_AdjacencyGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_AdjacencyGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_UndirectedGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::DeserializeFromGraphML
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::DeserializeFromGraphML_Throws_InvalidData
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::SerializeToGraphML_Throws_InvalidData
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::SerializeToXml
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::DeserializeFromXml_Reader
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlSerializableGraph
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlVertexList
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlVertexList_Add
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlEdgeList
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlEdgeList_Add
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::WriteXml
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync,readdirSync}from'node:fs';
import{AdjacencyGraph,UndirectedGraph,Edge}from'../src/core.js';
import * as S from '../src/serialization.js';
const simple=(Type=AdjacencyGraph)=>{const g=new Type();g.AddVertexRange(['a','b','isolated']);g.AddEdge(new Edge('a','b'));g.AddEdge(new Edge('a','b'));g.AddEdge(new Edge('b','b'));return g;};
// Source: GraphMLSerializerTests / GraphMLDeserializerTests roundtrip families.
for(const Type of[AdjacencyGraph,UndirectedGraph])test(`GraphMLSerializerTests.Serialize / Deserialize ${Type.name}`,()=>{const original=simple(Type),xml=S.SerializeToGraphML(original,{vertexIdentity:v=>v}),copy=S.DeserializeFromGraphML(xml);assert.equal(copy.IsDirected,original.IsDirected);assert.deepEqual([...copy.Vertices],[...original.Vertices]);assert.deepEqual([...copy.Edges].map(e=>[e.Source,e.Target]),[...original.Edges].map(e=>[e.Source,e.Target]));});
test('GraphMLSerializerTests.Serialize with types, defaults, metadata and escaping',()=>{const g=new AdjacencyGraph(),a={Name:'A<&"\n',Weight:1.25,Active:true,Big:9223372036854775807n,Defaulted:42,List:[1,2,3]},b={Name:'B',Weight:Infinity,Active:false,Big:-9223372036854775808n,Defaulted:7,List:[]};g.AddVertexRange([a,b]);const e=Object.assign(new Edge(a,b),{Label:'edge & <',Cost:-0.5});g.AddEdge(e);g.Title='test > graph';const options={vertexIdentity:v=>v.Name,graphProperties:{Title:'string'},vertexProperties:{Name:'string',Weight:'double',Active:'boolean',Big:'long',Defaulted:{type:'int',default:42},List:'int[]'},edgeProperties:{Label:'string',Cost:'double'}};const xml=S.SerializeToGraphML(g,options);assert.match(xml,/&lt;&amp;&quot;&#10;/);assert.match(xml,/<default>42<\/default>/);assert.match(xml,/9223372036854775807/);assert.match(xml,/>INF<\/data>/);const copy=new S.GraphMLDeserializer(options).Deserialize(xml);assert.equal(copy.Title,g.Title);const [ca,cb]=copy.Vertices;assert.equal(ca.Name,a.Name);assert.equal(ca.Big,a.Big);assert.equal(cb.Big,b.Big);assert.equal(ca.Defaulted,42);assert.equal(cb.Defaulted,7);assert.deepEqual(ca.List,a.List);assert.deepEqual(cb.List,b.List);assert.equal([...copy.Edges][0].Label,e.Label);});
test('GraphML factories preserve object identity and receive original edge ids',()=>{const xml=S.SerializeToGraphML(simple(),{vertexIdentity:v=>v,edgeIdentity:((i=0)=>()=>`edge-${i++}`)()});const g=new S.GraphMLDeserializer().Deserialize(xml,new AdjacencyGraph(),id=>({Id:id}),(s,t,id)=>Object.assign(new Edge(s,t),{Id:id}));const e=[...g.Edges][0];assert.equal(e.Source,[...g.Vertices][0]);assert.equal(e.Id,'edge-0');});
test('GraphML duplicate identities / invalid property types reject before writer side effects',()=>{let written=false;assert.throws(()=>new S.GraphMLSerializer().Serialize(()=>written=true,simple(),()=>1));assert.equal(written,false);assert.throws(()=>S.SerializeToGraphML(simple(),{vertexProperties:{x:'object'}}));});
for(const value of ['<!DOCTYPE graphml [<!ENTITY secret SYSTEM "file:///etc/passwd">]><graphml/>','<a><b></a>','<a id="x" id="y"/>','<a>&secret;</a>','<a>&#0;</a>','<a/><b/>','<a>\u0000</a>','<x:a/>'])test(`XML rejection ${value.slice(0,35)}`,()=>assert.throws(()=>S.ParseXml(value)));
test('XML numeric and named entities, namespaces and CDATA',()=>{const n=S.ParseXml('<?xml version="1.0"?><g:a xmlns:g="urn:g" x="a&amp;b&#x1F600;"><![CDATA[<literal>]]></g:a>');assert.equal(n.NamespaceURI,'urn:g');assert.equal(n.GetAttribute('x'),'a&b😀');assert.equal(n.Value,'<literal>');});
for(const [type,bad]of[['int','2147483648'],['int','1.5'],['long','9223372036854775808'],['boolean','True'],['double','5foo']])test(`GraphMLDeserializerTests invalid ${type} ${bad}`,()=>{const xml=`<graphml xmlns="http://graphml.graphdrawing.org/xmlns"><key id="k" for="node" attr.name="v" attr.type="${type}"/><graph edgedefault="directed"><node id="a"><data key="k">${bad}</data></node></graph></graphml>`;assert.throws(()=>S.DeserializeFromGraphML(xml));});
test('Generic XML callbacks retain user properties and custom element names',()=>{const g=simple();const xml=S.SerializeToXml(g,undefined,v=>v,((i=0)=>()=>String(i++))(),'network','vertex','link','urn:network',(w)=>w.WriteAttributeString('Title','Graph & graph'),(w,v)=>w.WriteAttributeString('label','label '+v));const root=S.ParseXml(xml);assert.equal(root.NamespaceURI,'urn:network');assert.equal(root.GetAttribute('Title'),'Graph & graph');const mapping=new Map();const copy=S.DeserializeFromXml(xml,'network','vertex','link',()=>new AdjacencyGraph(),n=>{const v={Id:n.GetAttribute('id'),Label:n.GetAttribute('label')};mapping.set(v.Id,v);return v;},n=>new Edge(mapping.get(n.GetAttribute('source')),mapping.get(n.GetAttribute('target'))));assert.equal(copy.VertexCount,3);assert.equal(copy.EdgeCount,3);});
test('XmlSerializableGraphTests.Vertices / Edges',()=>{const proxy=new S.XmlSerializableGraph();proxy.Vertices.Add('a');proxy.Edges.Add(new Edge('a','b'));assert.deepEqual([...proxy.Vertices],['a','b']);assert.equal([...proxy.Edges].length,1);});
test('DirectedGraphMLAlgorithmTests.Compute / format events / schema roundtrip',()=>{const g=simple(),a=new S.DirectedGraphMLAlgorithm(g,v=>v,e=>e.Source+'->'+e.Target);a.FormatNode.add((v,n)=>{n.Label='<'+v+'>';n.Group=S.GroupEnum.Expanded;n.GroupSpecified=true;});a.FormatEdge.add((e,l)=>{l.Category1='related';});a.FormatGraph.add((_,d)=>{d.Title='My & graph';d.GraphDirection=S.GraphDirectionEnum.LeftToRight;d.GraphDirectionSpecified=true;d.Styles=[new S.DirectedGraphStyle({TargetType:S.TargetTypeEnum.Node,Condition:new S.DirectedGraphStyleCondition({Expression:'HasCategory("related")'}),Setter:[new S.DirectedGraphStyleSetter({Property:'Background',Value:'Blue'})]})];});a.Compute();const d=a.DirectedGraph;assert.equal(d.Nodes.length,3);assert.equal(d.Links.length,3);const xml=S.WriteDirectedGraphXml(d),copy=S.ReadDirectedGraphXml(xml);assert.equal(copy.Title,d.Title);assert.equal(copy.Nodes[0].Label,'<a>');assert.equal(copy.Nodes[0].Group,S.GroupEnum.Expanded);assert.equal(copy.Nodes[0].GroupSpecified,true);assert.equal(copy.Styles[0].Setter[0].Value,'Blue');assert.equal(copy.GraphDirection,S.GraphDirectionEnum.LeftToRight);});
test('Binary serialization uses native NRBF by default and preserves explicit adapters',()=>{assert.throws(()=>S.SerializeToBinary(simple(),{}),/Write|write/);assert.throws(()=>S.DeserializeFromBinary({}),/bytes/);let bytes;S.SerializeToBinary(simple(),{Write:b=>{bytes=b;}});assert.equal(S.DeserializeFromBinary(bytes).VertexCount,3);assert.equal(S.SerializeToBinary(simple(),{},{Serialize:g=>g.VertexCount}),3);});
test('XML array helpers preserve upstream lexical representation',()=>{const w=new S.XmlStringWriter();S.XmlWriterExtensions.WriteBooleanArray(w,[true,false]);assert.equal(w.ToString(),'True False ');assert.deepEqual(S.XmlReaderExtensions.ReadBooleanArray('True False '),[true,false]);assert.equal(S.XmlReaderExtensions.ReadStringArray('null'),null);assert.deepEqual(S.XmlReaderExtensions.ReadStringArray('null '),['null']);assert.deepEqual(S.XmlReaderExtensions.ReadInt64Array('9223372036854775807 '),[9223372036854775807n]);});
// Source GraphML document corpus: exact files, safe legacy parser option; no external DTD loading.
const corpus=new URL('./fixtures/GraphML/',import.meta.url);
for(const file of readdirSync(corpus).filter(n=>/^g\..*\.graphml$/.test(n)||n==='DCT8.graphml'))test(`GraphMLDeserializerTests.UpstreamCorpus ${file}`,()=>{const xml=readFileSync(new URL(file,corpus),'utf8'),graph=new S.GraphMLDeserializer({allowLegacy:true}).Deserialize(xml),nodes=[...xml.matchAll(/<node\s+id="([^"]+)"/g)].map(m=>m[1]),edges=[...xml.matchAll(/<edge\b([^>]*)>/g)].map(m=>[m[1].match(/\bsource="([^"]+)"/)[1],m[1].match(/\btarget="([^"]+)"/)[1]]);assert.deepEqual([...graph.Vertices],nodes);assert.deepEqual([...graph.Edges].map(e=>[e.Source,e.Target]).sort(),edges.sort());const roundtrip=S.DeserializeFromGraphML(S.SerializeToGraphML(graph,{vertexIdentity:v=>v}));assert.equal(roundtrip.VertexCount,nodes.length);assert.equal(roundtrip.EdgeCount,edges.length);});
for(const file of readdirSync(corpus).filter(n=>/^DCT8_.*\.graphml$/.test(n)))test(`GraphMLDeserializerTests.MalformedCorpus ${file}`,()=>assert.throws(()=>S.DeserializeFromGraphML(readFileSync(new URL(file,corpus),'utf8'))));
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_HeaderCheck
for(const declaration of[true,false])test(`GraphMLSerialization_HeaderCheck ${declaration}`,()=>{const serializer=new S.GraphMLSerializer();serializer.EmitDocumentDeclaration=declaration;const xml=serializer.Serialize(simple());assert.equal(xml.startsWith('<?xml'),declaration);assert.equal(S.DeserializeFromGraphML(xml).EdgeCount,3);});
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::ToDirectedGraphML
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::ToDirectedGraphML_WithIdentity
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::ToDirectedGraphML_WithColors
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::ToDirectedGraphML_WithFormat
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::ToDirectedGraphML_Throws
test('DirectedGraphMLExtensionsTests all conversion overloads',()=>{const g=simple();assert.equal(S.ToDirectedGraphML(g).Nodes.length,3);const colors=S.ToDirectedGraphML(g,v=>v==='a'?2:v==='b'?1:0);assert.deepEqual(colors.Nodes.map(n=>n.Background),['Black','LightGray','White']);let i=0;const d=S.ToDirectedGraphML(g,v=>'v-'+v,()=>String(i++),(v,n)=>{n.Label=v;},(e,l)=>{l.Label='connected';});assert.equal(d.Nodes[0].Id,'v-a');assert.equal(d.Nodes[0].Label,'a');assert.equal(d.Links[0].Label,'connected');assert.throws(()=>S.ToDirectedGraphML(null));assert.throws(()=>S.ToDirectedGraphML(g,null));assert.throws(()=>S.ToDirectedGraphML(g,v=>v,null));});
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlSerializableGraph_Throws
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlVertexList_Throws
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlVertexList_Add_Throws
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlEdgeList_Throws
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlEdgeList_Add_Throws
test('XmlSerializableStructuresTests null validation',()=>{assert.throws(()=>new S.XmlSerializableGraph(null));assert.throws(()=>new S.XmlVertexList(null));assert.throws(()=>new S.XmlEdgeList(null));const g=new S.XmlSerializableGraph();assert.throws(()=>g.Vertices.Add(null));assert.throws(()=>g.Edges.Add(null));});
test('GraphMLXmlResolver embedded schemas and explicit external resolver',()=>{const resolver=new S.GraphMLXmlResolver({GetEntity:(uri,role)=>({uri,role})});for(const name of['graphml.dtd','graphml.xsd','graphml-structure.xsd','graphml-attributes.xsd','graphml-parseinfo.xsd','xlink.xsd']){const text=new TextDecoder().decode(resolver.GetEntity('https://example.test/'+name));assert.ok(text.length>50);assert.match(text,/</);}assert.deepEqual(resolver.GetEntity('urn:other','role'),{uri:'urn:other',role:'role'});assert.throws(()=>new S.GraphMLXmlResolver(null));assert.throws(()=>new S.GraphMLXmlResolver().GetEntity('urn:unknown'));});
test('XmlReaderExtensions named array APIs and nullable self-closing content',()=>{assert.deepEqual(S.XmlReaderExtensions.ReadElementContentAsInt32Array('<numbers>1 2 3 </numbers>','numbers',''),[1,2,3]);assert.equal(S.XmlReaderExtensions.ReadElementAsNullableString('<text/>','text',''),null);assert.equal(S.XmlReaderExtensions.ReadElementAsNullableString('<text></text>','text',''),'');assert.throws(()=>S.XmlReaderExtensions.ReadElementContentAsBooleanArray('<flags>true</flags>','other',''));});
test('Generic XML mixed content order and XPath child/descendant selection',()=>{assert.equal(S.ParseXml('<x>A<b>B</b>C<d>D</d>E</x>').Value,'ABCDE');const xml='<doc><ignored><node id="wrong"/></ignored><graph><vertices><node id="a"/><node id="b"/></vertices><edges><edge source="a" target="b"/></edges></graph></doc>';const g=S.DeserializeFromXml(xml,'/doc/graph','vertices/node','edges/edge');assert.deepEqual([...g.Vertices],['a','b']);assert.equal(g.EdgeCount,1);assert.throws(()=>S.DeserializeFromXml(xml,'//graph[@id="G"]'));});
test('GraphML property metadata setters are exercised and prototype is preserved',()=>{const xml='<graphml xmlns="http://graphml.graphdrawing.org/xmlns"><key id="k" for="node" attr.name="label" attr.type="string"/><graph edgedefault="directed"><node id="a"><data key="k">hello</data></node></graph></graphml>';const d=new S.GraphMLDeserializer({vertexProperties:{label:{type:'string',set:(o,v)=>{o._label=v.toUpperCase();}}}}),g=d.Deserialize(xml,new AdjacencyGraph(),id=>({Id:id}));assert.equal(g.Vertices[0]._label,'HELLO');});

test('DGML schema numeric fields and renamed Category attributes roundtrip',()=>{const graph=new S.DirectedGraph({Nodes:[new S.DirectedGraphNode({Id:'a',Category1:'Group',FontSize:14.5,FontSizeSpecified:true,LinesOfCode:42,LinesOfCodeSpecified:true})],Links:[],IdentifierAliases:[new S.DirectedGraphAlias({n:255,Id:'alias',Uri:'urn:test'})]});const xml=S.WriteDirectedGraphXml(graph);assert.match(xml,/Category="Group"/);assert.doesNotMatch(xml,/Category1=/);const copy=S.ReadDirectedGraphXml(xml);assert.equal(copy.Nodes[0].Category1,'Group');assert.equal(copy.Nodes[0].FontSize,14.5);assert.equal(copy.Nodes[0].LinesOfCode,42);assert.equal(copy.IdentifierAliases[0].n,255);assert.equal(new S.DirectedGraphAlias().n,0);});

// Source: SerializationTestCaseSources and SerializationTestVertexClasses; native attributes become explicit metadata.
import { BidirectionalGraph, BidirectionalAdapterGraph, ClusteredAdjacencyGraph, CompressedSparseRowGraph, EdgeListGraph, BidirectionalMatrixGraph, ArrayAdjacencyGraph, ArrayBidirectionalGraph, ArrayUndirectedGraph, ReversedBidirectionalGraph, UndirectedBidirectionalGraph } from '../src/core.js';
const valueVertex=(id,values={})=>Object.assign({ID:String(id),StringDefault:'',String:null,Int:0,Long:0n,Bool:false,Float:0,Double:0,IntArray:null,IntIList:null},values);
const valueEdge=(s,t,id,values={})=>Object.assign(new Edge(s,t),{ID:String(id),String:null,Int:0,Long:0n,Bool:false,Float:0,Double:0},values);
const sourceVertexProperties={StringDefault:{name:'v_stringDefault',type:'string',default:'defaultDefaultString'},String:{name:'v_string',type:'string',default:'defaultString'},Int:{name:'v_int',type:'int',default:1},Long:{name:'v_long',type:'long',default:2n},Bool:'boolean',Float:'float',Double:'double',IntArray:'int[]',IntIList:'int[]'};
const sourceEdgeProperties={String:{name:'e_string',type:'string',default:'defaultString'},Int:{name:'e_int',type:'int',default:1},Long:{name:'e_long',type:'long',default:2n},Bool:'boolean',Float:'float',Double:'double'};
function serializationSourceGraph(complex,empty,Type=AdjacencyGraph,heterogeneous=false){const g=new Type();if(empty)return g;const v=complex?[valueVertex(0,{String:'',StringDefault:null}),valueVertex(1,{Float:Math.fround(1.3),String:'test'}),valueVertex(2,{Double:12.5,Bool:true}),valueVertex(3,{Int:45,Long:51n}),valueVertex(4)]:[0,1,2,3,4];if(heterogeneous){v[2].Data=25;v[4].Data=42;}g.AddVertexRange(v);const edges=complex?[valueEdge(v[1],v[2],0,{Bool:true,Int:77}),valueEdge(v[1],v[3],1,{Long:99n}),valueEdge(v[1],v[4],2,{String:'test'}),valueEdge(v[2],v[2],3),valueEdge(v[3],v[4],4)]:[[0,1],[1,2],[2,0],[2,1],[2,2],[4,2]].map(([s,t])=>new Edge(s,t));if(heterogeneous){edges[1].Data=12;edges[4].Data=45.5;}g.AddEdgeRange(edges);return g;}
const sourceFamilies={AdjacencyGraph:g=>[g,new ArrayAdjacencyGraph(g)],AdapterGraph:g=>[new BidirectionalAdapterGraph(g)],ClusteredGraph:g=>[new ClusteredAdjacencyGraph(g)],CompressedGraph:g=>[new CompressedSparseRowGraph(g)],BidirectionalGraph:g=>{const b=new BidirectionalGraph();b.AddVertexRange(g.Vertices);b.AddEdgeRange(g.Edges);return[b,new ArrayBidirectionalGraph(b),new ReversedBidirectionalGraph(b),new UndirectedBidirectionalGraph(b)];},UndirectedGraph:g=>[g,new ArrayUndirectedGraph(g)],EdgeListGraph:g=>{const e=new EdgeListGraph();e.AddEdgeRange(g.Edges);return[e];}};
function assertSerializationContent(original,copy,complex,edgeData){const id=v=>complex?v.ID:String(v),vertexData=v=>complex?{...v}:v,edges=g=>[...g.Edges].map(e=>({Source:id(e.Source),Target:id(e.Target),...(edgeData?Object.fromEntries(Object.entries(e).filter(([k])=>k!=='Source'&&k!=='Target')):{})}));assert.equal(copy.IsDirected,original.IsDirected);assert.deepEqual([...copy.Vertices].map(vertexData),[...original.Vertices].map(vertexData));const order=(a,b)=>`${a.Source}|${a.Target}|${a.ID??''}`.localeCompare(`${b.Source}|${b.Target}|${b.ID??''}`);assert.deepEqual(edges(copy).sort(order),edges(original).sort(order));for(const e of copy.Edges){assert.ok([...copy.Vertices].includes(e.Source));assert.ok([...copy.Vertices].includes(e.Target));}}
function graphmlSourceRoundtrip(g,complex,edgeData=true){const options={vertexIdentity:v=>complex?v.ID:String(v),vertexProperties:complex?sourceVertexProperties:{},edgeProperties:complex&&edgeData?sourceEdgeProperties:{}};if(complex&&edgeData)options.edgeIdentity=e=>e.ID;const xml=S.SerializeToGraphML(g,options),copy=new S.GraphMLDeserializer(options).Deserialize(xml,undefined,complex?id=>valueVertex(id):Number,complex&&edgeData?(s,t,id)=>valueEdge(s,t,id):(s,t)=>new Edge(s,t));assertSerializationContent(g,copy,complex,complex&&edgeData);if(!(g instanceof ReversedBidirectionalGraph))assert.equal(S.SerializeToGraphML(copy,options),xml);}
function xmlSourceRoundtrip(g,complex,edgeData=true){const dataEntries=o=>Object.entries(o).filter(([k])=>k!=='Source'&&k!=='Target'),write=(w,o)=>{for(const[k,v]of dataEntries(o))w.WriteAttributeString(k,v===null?'[null]':String(v));},read=n=>{const v={};for(const[k,value]of Object.entries(n.Attributes)){if(['id','source','target'].includes(k))continue;v[k]=value==='[null]'?null:k==='Long'?BigInt(value):['Int','Float','Double','Data'].includes(k)?Number(value):k==='Bool'?value==='true':value;}return v;};let next=0;const xml=S.SerializeToXml(g,undefined,v=>complex?v.ID:String(v),e=>complex&&edgeData?e.ID:String(next++),'graph','node','edge','urn:tests',undefined,complex?write:undefined,complex&&edgeData?write:undefined),mapping=new Map();const copy=S.DeserializeFromXml(xml,'graph','node','edge','urn:tests',()=>g.IsDirected?new AdjacencyGraph():new UndirectedGraph(),n=>{const id=n.GetAttribute('id'),v=complex?read(n):Number(id);mapping.set(id,v);return v;},n=>{const e=new Edge(mapping.get(n.GetAttribute('source')),mapping.get(n.GetAttribute('target')));return complex&&edgeData?Object.assign(e,read(n)):e;});assertSerializationContent(g,copy,complex,complex&&edgeData);}
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_AdjacencyGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_AdjacencyGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_AdapterGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_AdapterGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_ClusteredGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_ClusteredGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_CompressedGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_CompressedGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_BidirectionalGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_BidirectionalGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_UndirectedGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_UndirectedGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_EdgeListGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_EdgeListGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_AdjacencyGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_AdjacencyGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_AdapterGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_AdapterGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_ClusteredGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_ClusteredGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_CompressedGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_CompressedGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_BidirectionalGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_BidirectionalGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_UndirectedGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_UndirectedGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_EdgeListGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_EdgeListGraph_Complex
for(const [family,wrap]of Object.entries(sourceFamilies))for(const complex of[false,true])for(const empty of[false,true])for(const format of['GraphML','XML'])test(`${format} source ${family} ${complex?'Complex':'Simple'} ${empty?'empty':'populated'}`,()=>{const base=serializationSourceGraph(complex,empty,family==='UndirectedGraph'?UndirectedGraph:AdjacencyGraph,complex&&format==='XML');for(const g of wrap(base)){const edgeData=!(g instanceof CompressedSparseRowGraph||g instanceof ReversedBidirectionalGraph);if(format==='GraphML')graphmlSourceRoundtrip(g,complex,edgeData);else xmlSourceRoundtrip(g,complex,edgeData);}});

// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_BidirectionalMatrixGraph
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::XmlSerialization_BidirectionalMatrixGraph
for(const [size,pairs]of[[10,[]],[5,[[0,1],[1,2],[2,0],[2,1],[2,2],[4,2]]],[5,[[1,2],[1,3],[1,4],[2,2],[3,4]]]])test(`Serialization BidirectionalMatrixGraph source ${size} vertices ${pairs.length} edges`,()=>{const g=new BidirectionalMatrixGraph(size);g.AddEdgeRange(pairs.map(([s,t])=>new Edge(s,t)));graphmlSourceRoundtrip(g,false);xmlSourceRoundtrip(g,false);});
test('Serialization ClusteredGraph source subgraph fixture is flattened consistently',()=>{for(const complex of[false,true]){const g=new ClusteredAdjacencyGraph(new AdjacencyGraph()),v=complex?Array.from({length:7},(_,i)=>valueVertex(i)):[0,1,2,3,4,5,6];g.AddVertexRange(v.slice(0,4));g.AddEdgeRange([[0,1],[1,2],[2,0],[3,2]].map(([s,t],i)=>complex?valueEdge(v[s],v[t],i):new Edge(v[s],v[t])));const sub=g.AddCluster();sub.AddVertexRange(v.slice(4));sub.AddEdge(complex?valueEdge(v[4],v[6],4):new Edge(v[4],v[6]));graphmlSourceRoundtrip(g,complex);xmlSourceRoundtrip(g,complex);}});
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::DeserializeAndValidateFromGraphML_Throws
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::DeserializeFromGraphML_Throws
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::SerializeToGraphML_Throws
test('GraphML source null argument combinations validate independently of content',()=>{const g=new AdjacencyGraph(),xml=S.SerializeToGraphML(g),vf=id=>id,ef=(s,t)=>new Edge(s,t),writer=()=>assert.fail('invalid inputs must not write');for(const reader of[xml,{ReadToEnd:()=>xml}])for(const args of[[null,reader,vf,ef],[g,null,vf,ef],[g,'',vf,ef],[g,reader,null,ef],[g,reader,vf,null]]){assert.throws(()=>S.DeserializeFromGraphML(...args));assert.throws(()=>S.DeserializeAndValidateFromGraphML(...args));}for(const args of[[null,writer],[g,null],[g,''],[null,writer,vf,ef],[g,null,vf,ef],[g,'',vf,ef],[g,writer,null,ef],[g,writer,vf,null]])assert.throws(()=>S.SerializeToGraphML(...args));});
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::WriteXml_Throws
test('DirectedGraphMLExtensions.WriteXml null graph and writer',()=>{assert.throws(()=>S.WriteDirectedGraphXml(null,()=>{}),TypeError);assert.throws(()=>S.WriteDirectedGraphXml(new S.DirectedGraph(),null),TypeError);});
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::SerializationToXml_Throws
test('XML serialization source validates every required parameter even on empty graphs',()=>{const valid=[new AdjacencyGraph(),()=>assert.fail('must not write'),String,String,'family','person','relation','urn:test'];for(const i of[0,1,2,3,4,5,6,7]){const args=[...valid];args[i]=null;assert.throws(()=>S.SerializeToXml(...args),`argument ${i}`);}for(const i of[4,5,6]){const args=[...valid];args[i]='';assert.throws(()=>S.SerializeToXml(...args));}});
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::DeserializeFromXml_Document_Throws
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::DeserializeFromXml_Reader_Throws
test('XML document and reader source null, empty selector, missing graph validation',()=>{const xml='<graph xmlns="urn:test"><node id="a"/></graph>';for(const reader of[S.ParseXml(xml),{ReadToEnd:()=>xml}]){const base=[reader,'graph','node','edge',()=>new AdjacencyGraph(),n=>n.GetAttribute('id'),()=>new Edge('a','a')];for(const i of[0,1,2,3,4,5,6]){const args=[...base];args[i]=null;assert.throws(()=>S.DeserializeFromXml(...args));}for(const i of[1,2,3]){const args=[...base];args[i]='';assert.throws(()=>S.DeserializeFromXml(...args));}assert.throws(()=>S.DeserializeFromXml(reader,'missing','node','edge'));const ns=[reader,'graph','node','edge','urn:test',...base.slice(4)];for(const i of[0,1,2,3,4,5,6,7]){const args=[...ns];args[i]=null;assert.throws(()=>S.DeserializeFromXml(...args));}}});
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::DeserializeFromXml_Document
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::DeserializeFromXml_Document_Empty
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::DeserializeFromXml_Reader_Empty
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::SerializeToXml_Empty
test('XML empty and populated document/readers preserve topology and namespace selections',()=>{for(const Type of[AdjacencyGraph,BidirectionalGraph,UndirectedGraph])for(const empty of[false,true]){const g=serializationSourceGraph(false,empty,Type);const xml=S.SerializeToXml(g,undefined,String,undefined,'graph','node','edge','urn:test');if(empty)assert.equal(xml,'<graph xmlns="urn:test"/>');for(const reader of[S.ParseXml(xml),{ReadToEnd:()=>xml}]){const copy=S.DeserializeFromXml(reader,'graph','node','edge','urn:test',()=>new Type(),n=>Number(n.GetAttribute('id')),n=>new Edge(Number(n.GetAttribute('source')),Number(n.GetAttribute('target'))));assertSerializationContent(g,copy,false,false);}}});

// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerializationWithValidation_WriteVertex
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerializationWithValidation_WriteEdge
test('GraphML source graph/vertex/edge scalar, defaults, array and IList content',()=>{const arrays={Bool:[true,false,true,true],Int:[2,3,45,3,44,-2,3,5,99999999],Long:[3n,4n,43n,999999999999999999n,445n,55n,3n,98n,49789238740598170n,987459n,97239n,234245n,0n,-2232n],Float:[3.14159265,1.1,1,23,-2,987459,97239,234245,0,-2232,234.55345].map(Math.fround),Double:[3.14159265,1.1,1,23,-2,987459,97239,234245,0,-2232,234.55345],String:['','Quick','','brown','fox','jumps','over','the','lazy','dog','.','']},types={Bool:'boolean',Int:'int',Long:'long',Float:'float',Double:'double',String:'string'},g=new AdjacencyGraph(),graphProperties={...types};Object.assign(g,{Bool:true,Double:1,Float:2,Int:10,Long:100n,String:'foo'});for(const[name,values]of Object.entries(arrays))for(const suffix of['Array','IList']){g[name+suffix]=values;graphProperties[name+suffix]=types[name]+'[]';}g.NullArray=null;graphProperties.NullArray='int[]';const a=valueVertex('v1',{StringDefault:'bar',String:'string',Long:20n,Float:25,Double:30,Bool:true,IntArray:[1,2,3,4],IntIList:[4,5,6,7]}),b=valueVertex('v2',{StringDefault:null,String:'',Int:42,IntArray:null});g.AddVertexRange([a,b]);g.AddEdgeRange([valueEdge(a,b,'e1',{String:'edge',Int:90,Long:100n,Float:25,Double:110,Bool:true}),valueEdge(a,b,'e2',{Float:Math.fround(13.4),Long:42n})]);const options={graphProperties,vertexProperties:sourceVertexProperties,edgeProperties:sourceEdgeProperties,vertexIdentity:v=>v.ID,edgeIdentity:e=>e.ID},xml=S.SerializeToGraphML(g,options),copy=new S.GraphMLDeserializer(options).Deserialize(xml,undefined,id=>valueVertex(id),(s,t,id)=>valueEdge(s,t,id));for(const name of Object.keys(graphProperties))assert.deepEqual(copy[name],g[name],name);assertSerializationContent(g,copy,true,true);assert.equal(S.SerializeToGraphML(copy,options),xml);assert.deepEqual(S.XmlReaderExtensions.ReadStringArray(S.XmlWriterExtensions.WriteStringArray(null,arrays.String)),arrays.String);});
test('GraphML metadata rejects unsupported, null, array and wrong typed default values',()=>{const g=new AdjacencyGraph();for(const definition of[{type:'char',default:'a'},{type:'string',default:null},{type:'int[]',default:[1,2]},{type:'boolean',default:1},{type:'string',default:1}])assert.throws(()=>S.SerializeToGraphML(g,{vertexProperties:{Test:definition}}));});
test('Serialization preserves custom Equals endpoint identity',()=>{class V{constructor(id){this.ID=id;}Equals(other){return other instanceof V&&other.ID===this.ID;}GetHashCode(){return this.ID;}}const g=new AdjacencyGraph();g.AddVertexRange([new V(1),new V(2)]);g.AddEdge(new Edge(new V(1),new V(2)));for(const xml of[S.SerializeToGraphML(g,{vertexProperties:{},vertexIdentity:v=>String(v.ID)}),S.SerializeToXml(g,undefined,v=>String(v.ID))]){const copy=xml.includes('graphml')?S.DeserializeFromGraphML(xml):S.DeserializeFromXml(xml);assert.deepEqual([...copy.Vertices],['1','2']);assert.equal(copy.Edges[0].Source,'1');assert.equal(copy.Edges[0].Target,'2');}const dgml=S.ToDirectedGraphML(g,{vertexIdentity:v=>String(v.ID)});assert.equal(dgml.Links[0].Source,'1');assert.equal(dgml.Links[0].Target,'2');});

// upstream: tests/QuikGraph.Serialization.Tests/BinarySerializationTests.cs::BinarySerialization_Throws
test('BinarySerializationTests.BinarySerialization_Throws validates stream capabilities before adapter',()=>{const g=new AdjacencyGraph(),stream={CanRead:true,CanWrite:true},invalid={CanRead:false,CanWrite:false};assert.throws(()=>S.SerializeToBinary(null,stream),/graph/);assert.throws(()=>S.SerializeToBinary(g,invalid),/writable/);assert.throws(()=>S.SerializeToBinary(g,null),/stream/);assert.throws(()=>S.DeserializeFromBinary(null),/stream/);assert.throws(()=>S.DeserializeFromBinary(invalid),/readable/);});
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::SerializeToXml_Empty
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::SerializeToXml
test('XmlSerializableGraph source XML proxy layout with empty and populated containers',()=>{const empty=S.SerializeToXml(new S.XmlSerializableGraph());assert.match(empty,/^<\?xml version="1.0" encoding="utf-8"\?>\s*<graph\s*.*?>\s*<vertices\s*\/>\s*<edges\s*\/>\s*<\/graph>$/);const g=new AdjacencyGraph();g.AddVerticesAndEdgeRange([new S.XmlSerializableEdge(1,2),new S.XmlSerializableEdge(1,3),new S.XmlSerializableEdge(2,2)]);g.AddVertex(4);const proxy=new S.XmlSerializableGraph(g),xml=S.SerializeToXml(proxy),root=S.ParseXml(xml);assert.deepEqual(root.Select('vertices')[0].Children.map(n=>[n.Name,n.Value]),[['vertex','1'],['vertex','2'],['vertex','3'],['vertex','4']]);assert.deepEqual(root.Select('edges')[0].Children.map(n=>[n.Name,n.Select('Source')[0].Value,n.Select('Target')[0].Value]),[['edge','1','2'],['edge','1','3'],['edge','2','2']]);assert.match(xml,/^<\?xml version="1.0" encoding="utf-8"\?>/);});

test('XML and GraphML arrays distinguish empty collections from empty string elements',()=>{for(const values of[[],[''],['',''],['','x','']]){const encoded=S.XmlWriterExtensions.WriteStringArray(null,values);assert.deepEqual(S.XmlReaderExtensions.ReadStringArray(encoded),values);const g=new AdjacencyGraph();g.AddVertex({ID:'v',Values:values});const options={vertexProperties:{Values:'string[]'},vertexIdentity:v=>v.ID},xml=S.SerializeToGraphML(g,options),copy=new S.GraphMLDeserializer(options).Deserialize(xml);assert.deepEqual(copy.Vertices[0].Values,values);}});
