// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_AdjacencyGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_AdjacencyGraph_Complex
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_UndirectedGraph_Simple
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::DeserializeFromGraphML
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::DeserializeFromGraphML_Throws_InvalidData
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::SerializeToGraphML_Throws_InvalidData
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::SerializeToXml
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializationTests.cs::DeserializeFromXml_Reader
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlSerializableGraph
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlVertexList
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlVertexList_Add
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlEdgeList
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlEdgeList_Add
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::WriteXml
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync,readdirSync}from'node:fs';
import{AdjacencyGraph,UndirectedGraph,Edge}from'../src/core.js';
import * as S from '../src/serialization.js';
const simple=(Type=AdjacencyGraph)=>{const g=new Type();g.AddVertexRange(['a','b','isolated']);g.AddEdge(new Edge('a','b'));g.AddEdge(new Edge('a','b'));g.AddEdge(new Edge('b','b'));return g;};
// Source: GraphMLSerializerTests / GraphMLDeserializerTests roundtrip families.
for(const Type of[AdjacencyGraph,UndirectedGraph])test(`GraphMLSerializerTests.Serialize / Deserialize ${Type.name}`,()=>{const original=simple(Type),xml=S.SerializeToGraphML(original,{vertexIdentity:v=>v}),copy=S.DeserializeFromGraphML(xml);assert.equal(copy.IsDirected,original.IsDirected);assert.deepEqual([...copy.Vertices],[...original.Vertices]);assert.deepEqual([...copy.Edges].map(e=>[e.Source,e.Target]),[...original.Edges].map(e=>[e.Source,e.Target]));});
test('GraphMLSerializerTests.Serialize with types, defaults, metadata and escaping',()=>{const g=new AdjacencyGraph(),a={Name:'A<&"\n',Weight:1.25,Active:true,Big:9223372036854775807n,Defaulted:42,List:[1,2,3]},b={Name:'B',Weight:Infinity,Active:false,Big:-9223372036854775808n,Defaulted:7,List:[]};g.AddVertexRange([a,b]);const e=Object.assign(new Edge(a,b),{Label:'edge & <',Cost:-0.5});g.AddEdge(e);g.Title='test > graph';const options={vertexIdentity:v=>v.Name,graphProperties:{Title:'string'},vertexProperties:{Name:'string',Weight:'double',Active:'boolean',Big:'long',Defaulted:{type:'int',default:42},List:'int[]'},edgeProperties:{Label:'string',Cost:'double'}};const xml=S.SerializeToGraphML(g,options);assert.match(xml,/&lt;&amp;&quot;&#10;/);assert.match(xml,/<default>42<\/default>/);assert.match(xml,/9223372036854775807/);assert.match(xml,/>INF<\/data>/);const copy=new S.GraphMLDeserializer(options).Deserialize(xml);assert.equal(copy.Title,g.Title);const [ca,cb]=copy.Vertices;assert.equal(ca.Name,a.Name);assert.equal(ca.Big,a.Big);assert.equal(cb.Big,b.Big);assert.equal(ca.Defaulted,42);assert.equal(cb.Defaulted,7);assert.deepEqual(ca.List,a.List);assert.deepEqual(cb.List,b.List);assert.equal([...copy.Edges][0].Label,e.Label);});
test('GraphML factories preserve object identity and receive original edge ids',()=>{const xml=S.SerializeToGraphML(simple(),{vertexIdentity:v=>v,edgeIdentity:((i=0)=>()=>`edge-${i++}`)()});const g=new S.GraphMLDeserializer().Deserialize(xml,new AdjacencyGraph(),id=>({Id:id}),(s,t,id)=>Object.assign(new Edge(s,t),{Id:id}));const e=[...g.Edges][0];assert.equal(e.Source,[...g.Vertices][0]);assert.equal(e.Id,'edge-0');});
test('GraphML duplicate identities / invalid property types reject before writer side effects',()=>{let written=false;assert.throws(()=>new S.GraphMLSerializer().Serialize(()=>written=true,simple(),()=>1));assert.equal(written,false);assert.throws(()=>S.SerializeToGraphML(simple(),{vertexProperties:{x:'object'}}));});
for(const value of ['<!DOCTYPE graphml [<!ENTITY secret SYSTEM "file:///etc/passwd">]><graphml/>','<a><b></a>','<a id="x" id="y"/>','<a>&secret;</a>','<a>&#0;</a>','<a/><b/>','<a>\u0000</a>','<x:a/>'])test(`XML rejection ${value.slice(0,35)}`,()=>assert.throws(()=>S.ParseXml(value)));
test('XML numeric and named entities, namespaces and CDATA',()=>{const n=S.ParseXml('<?xml version="1.0"?><g:a xmlns:g="urn:g" x="a&amp;b&#x1F600;"><![CDATA[<literal>]]></g:a>');assert.equal(n.NamespaceURI,'urn:g');assert.equal(n.GetAttribute('x'),'a&b😀');assert.equal(n.Value,'<literal>');});
for(const [type,bad]of[['int','2147483648'],['int','1.5'],['long','9223372036854775808'],['boolean','True'],['double','5foo']])test(`GraphMLDeserializerTests invalid ${type} ${bad}`,()=>{const xml=`<graphml xmlns="http://graphml.graphdrawing.org/xmlns"><key id="k" for="node" attr.name="v" attr.type="${type}"/><graph edgedefault="directed"><node id="a"><data key="k">${bad}</data></node></graph></graphml>`;assert.throws(()=>S.DeserializeFromGraphML(xml));});
test('Generic XML callbacks retain user properties and custom element names',()=>{const g=simple();const xml=S.SerializeToXml(g,undefined,v=>v,((i=0)=>()=>String(i++))(),'network','vertex','link','urn:network',(w)=>w.WriteAttributeString('Title','Graph & graph'),(w,v)=>w.WriteAttributeString('label','label '+v));const root=S.ParseXml(xml);assert.equal(root.NamespaceURI,'urn:network');assert.equal(root.GetAttribute('Title'),'Graph & graph');const mapping=new Map();const copy=S.DeserializeFromXml(xml,'network','vertex','link',()=>new AdjacencyGraph(),n=>{const v={Id:n.GetAttribute('id'),Label:n.GetAttribute('label')};mapping.set(v.Id,v);return v;},n=>new Edge(mapping.get(n.GetAttribute('source')),mapping.get(n.GetAttribute('target'))));assert.equal(copy.VertexCount,3);assert.equal(copy.EdgeCount,3);});
test('XmlSerializableGraphTests.Vertices / Edges',()=>{const proxy=new S.XmlSerializableGraph();proxy.Vertices.Add('a');proxy.Edges.Add(new Edge('a','b'));assert.deepEqual([...proxy.Vertices],['a','b']);assert.equal([...proxy.Edges].length,1);});
test('DirectedGraphMLAlgorithmTests.Compute / format events / schema roundtrip',()=>{const g=simple(),a=new S.DirectedGraphMLAlgorithm(g,v=>v,e=>e.Source+'->'+e.Target);a.FormatNode.add((v,n)=>{n.Label='<'+v+'>';n.Group=S.GroupEnum.Expanded;n.GroupSpecified=true;});a.FormatEdge.add((e,l)=>{l.Category1='related';});a.FormatGraph.add((_,d)=>{d.Title='My & graph';d.GraphDirection=S.GraphDirectionEnum.LeftToRight;d.GraphDirectionSpecified=true;d.Styles=[new S.DirectedGraphStyle({TargetType:S.TargetTypeEnum.Node,Condition:new S.DirectedGraphStyleCondition({Expression:'HasCategory("related")'}),Setter:[new S.DirectedGraphStyleSetter({Property:'Background',Value:'Blue'})]})];});a.Compute();const d=a.DirectedGraph;assert.equal(d.Nodes.length,3);assert.equal(d.Links.length,3);const xml=S.WriteDirectedGraphXml(d),copy=S.ReadDirectedGraphXml(xml);assert.equal(copy.Title,d.Title);assert.equal(copy.Nodes[0].Label,'<a>');assert.equal(copy.Nodes[0].Group,S.GroupEnum.Expanded);assert.equal(copy.Nodes[0].GroupSpecified,true);assert.equal(copy.Styles[0].Setter[0].Value,'Blue');assert.equal(copy.GraphDirection,S.GraphDirectionEnum.LeftToRight);});
test('CLR serialization requires explicit adapter',()=>{assert.throws(()=>S.SerializeToBinary(simple(),null),/adapter/);assert.throws(()=>S.DeserializeFromBinary(null),/adapter/);assert.equal(S.SerializeToBinary(simple(),null,{Serialize:g=>g.VertexCount}),3);});
test('XML array helpers preserve upstream lexical representation',()=>{const w=new S.XmlStringWriter();S.XmlWriterExtensions.WriteBooleanArray(w,[true,false]);assert.equal(w.ToString(),'True False ');assert.deepEqual(S.XmlReaderExtensions.ReadBooleanArray('True False '),[true,false]);assert.equal(S.XmlReaderExtensions.ReadStringArray('null'),null);assert.deepEqual(S.XmlReaderExtensions.ReadStringArray('null '),['null']);assert.deepEqual(S.XmlReaderExtensions.ReadInt64Array('9223372036854775807 '),[9223372036854775807n]);});
// Source GraphML document corpus: exact files, safe legacy parser option; no external DTD loading.
const corpus=new URL('./fixtures/GraphML/',import.meta.url);
for(const file of readdirSync(corpus).filter(n=>/^g\..*\.graphml$/.test(n)||n==='DCT8.graphml'))test(`GraphMLDeserializerTests.UpstreamCorpus ${file}`,()=>{const xml=readFileSync(new URL(file,corpus),'utf8'),graph=new S.GraphMLDeserializer({allowLegacy:true}).Deserialize(xml),nodes=[...xml.matchAll(/<node\s+id="([^"]+)"/g)].map(m=>m[1]),edges=[...xml.matchAll(/<edge\b([^>]*)>/g)].map(m=>[m[1].match(/\bsource="([^"]+)"/)[1],m[1].match(/\btarget="([^"]+)"/)[1]]);assert.deepEqual([...graph.Vertices],nodes);assert.deepEqual([...graph.Edges].map(e=>[e.Source,e.Target]).sort(),edges.sort());const roundtrip=S.DeserializeFromGraphML(S.SerializeToGraphML(graph,{vertexIdentity:v=>v}));assert.equal(roundtrip.VertexCount,nodes.length);assert.equal(roundtrip.EdgeCount,edges.length);});
for(const file of readdirSync(corpus).filter(n=>/^DCT8_.*\.graphml$/.test(n)))test(`GraphMLDeserializerTests.MalformedCorpus ${file}`,()=>assert.throws(()=>S.DeserializeFromGraphML(readFileSync(new URL(file,corpus),'utf8'))));
// upstream: tests/QuikGraph.Serialization.Tests/GraphMLSerializationTests.cs::GraphMLSerialization_HeaderCheck
for(const declaration of[true,false])test(`GraphMLSerialization_HeaderCheck ${declaration}`,()=>{const serializer=new S.GraphMLSerializer();serializer.EmitDocumentDeclaration=declaration;const xml=serializer.Serialize(simple());assert.equal(xml.startsWith('<?xml'),declaration);assert.equal(S.DeserializeFromGraphML(xml).EdgeCount,3);});
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::ToDirectedGraphML
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::ToDirectedGraphML_WithIdentity
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::ToDirectedGraphML_WithColors
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::ToDirectedGraphML_WithFormat
// upstream: tests/QuikGraph.Serialization.Tests/DirectedGraphMLExtensionsTests.cs::ToDirectedGraphML_Throws
test('DirectedGraphMLExtensionsTests all conversion overloads',()=>{const g=simple();assert.equal(S.ToDirectedGraphML(g).Nodes.length,3);const colors=S.ToDirectedGraphML(g,v=>v==='a'?2:v==='b'?1:0);assert.deepEqual(colors.Nodes.map(n=>n.Background),['Black','LightGray','White']);let i=0;const d=S.ToDirectedGraphML(g,v=>'v-'+v,()=>String(i++),(v,n)=>{n.Label=v;},(e,l)=>{l.Label='connected';});assert.equal(d.Nodes[0].Id,'v-a');assert.equal(d.Nodes[0].Label,'a');assert.equal(d.Links[0].Label,'connected');assert.throws(()=>S.ToDirectedGraphML(null));assert.throws(()=>S.ToDirectedGraphML(g,null));assert.throws(()=>S.ToDirectedGraphML(g,v=>v,null));});
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlSerializableGraph_Throws
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlVertexList_Throws
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlVertexList_Add_Throws
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlEdgeList_Throws
// upstream: tests/QuikGraph.Serialization.Tests/XmlSerializableStructuresTests.cs::XmlEdgeList_Add_Throws
test('XmlSerializableStructuresTests null validation',()=>{assert.throws(()=>new S.XmlSerializableGraph(null));assert.throws(()=>new S.XmlVertexList(null));assert.throws(()=>new S.XmlEdgeList(null));const g=new S.XmlSerializableGraph();assert.throws(()=>g.Vertices.Add(null));assert.throws(()=>g.Edges.Add(null));});
test('GraphMLXmlResolver embedded schemas and explicit external resolver',()=>{const resolver=new S.GraphMLXmlResolver({GetEntity:(uri,role)=>({uri,role})});for(const name of['graphml.dtd','graphml.xsd','graphml-structure.xsd','graphml-attributes.xsd','graphml-parseinfo.xsd','xlink.xsd']){const text=new TextDecoder().decode(resolver.GetEntity('https://example.test/'+name));assert.ok(text.length>50);assert.match(text,/</);}assert.deepEqual(resolver.GetEntity('urn:other','role'),{uri:'urn:other',role:'role'});assert.throws(()=>new S.GraphMLXmlResolver(null));assert.throws(()=>new S.GraphMLXmlResolver().GetEntity('urn:unknown'));});
test('XmlReaderExtensions named array APIs and nullable self-closing content',()=>{assert.deepEqual(S.XmlReaderExtensions.ReadElementContentAsInt32Array('<numbers>1 2 3 </numbers>','numbers',''),[1,2,3]);assert.equal(S.XmlReaderExtensions.ReadElementAsNullableString('<text/>','text',''),null);assert.equal(S.XmlReaderExtensions.ReadElementAsNullableString('<text></text>','text',''),'');assert.throws(()=>S.XmlReaderExtensions.ReadElementContentAsBooleanArray('<flags>true</flags>','other',''));});
test('Generic XML mixed content order and XPath child/descendant selection',()=>{assert.equal(S.ParseXml('<x>A<b>B</b>C<d>D</d>E</x>').Value,'ABCDE');const xml='<doc><ignored><node id="wrong"/></ignored><graph><vertices><node id="a"/><node id="b"/></vertices><edges><edge source="a" target="b"/></edges></graph></doc>';const g=S.DeserializeFromXml(xml,'/doc/graph','vertices/node','edges/edge');assert.deepEqual([...g.Vertices],['a','b']);assert.equal(g.EdgeCount,1);assert.throws(()=>S.DeserializeFromXml(xml,'//graph[@id="G"]'));});
test('GraphML property metadata setters are exercised and prototype is preserved',()=>{const xml='<graphml xmlns="http://graphml.graphdrawing.org/xmlns"><key id="k" for="node" attr.name="label" attr.type="string"/><graph edgedefault="directed"><node id="a"><data key="k">hello</data></node></graph></graphml>';const d=new S.GraphMLDeserializer({vertexProperties:{label:{type:'string',set:(o,v)=>{o._label=v.toUpperCase();}}}}),g=d.Deserialize(xml,new AdjacencyGraph(),id=>({Id:id}));assert.equal(g.Vertices[0]._label,'HELLO');});

test('DGML schema numeric fields and renamed Category attributes roundtrip',()=>{const graph=new S.DirectedGraph({Nodes:[new S.DirectedGraphNode({Id:'a',Category1:'Group',FontSize:14.5,FontSizeSpecified:true,LinesOfCode:42,LinesOfCodeSpecified:true})],Links:[],IdentifierAliases:[new S.DirectedGraphAlias({n:255,Id:'alias',Uri:'urn:test'})]});const xml=S.WriteDirectedGraphXml(graph);assert.match(xml,/Category="Group"/);assert.doesNotMatch(xml,/Category1=/);const copy=S.ReadDirectedGraphXml(xml);assert.equal(copy.Nodes[0].Category1,'Group');assert.equal(copy.Nodes[0].FontSize,14.5);assert.equal(copy.Nodes[0].LinesOfCode,42);assert.equal(copy.IdentifierAliases[0].n,255);assert.equal(new S.DirectedGraphAlias().n,0);});
