import {writeFile, mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import * as Q from '../../src/core.js';
import {VertexList, EdgeList, Queue, VertexEdgeDictionary, EdgeEdgeDictionary} from '../../src/collections.js';
import {GraphvizColor, GraphvizSize, GraphvizSizeF} from '../../src/graphviz.js';
import {SerializeNrbf, ToNrbfRecord} from '../../src/binary-serialization.js';
import {NrbfDecimal, NrbfDateTime, NrbfPrimitive, NrbfPrimitiveType} from '../../src/nrbf.js';

// Intentionally construct fresh objects using the public JavaScript API. No CLR
// bytes, parsed records, retained type metadata, or fixture snapshots are read.
const output = resolve(process.argv[2] ?? 'test-results/nrbf-fresh');
const cases = new Map();
const options = new Map();
const add = (name, value) => cases.set(name, value);
const adjacency = new Q.AdjacencyGraph(true, 4, 3);
adjacency.AddVertexRange([0, 1, 2, 9]);
adjacency.AddEdgeRange([new Q.EquatableEdge(0, 1), new Q.EquatableEdge(0, 1), new Q.EquatableEdge(1, 2), new Q.EquatableEdge(2, 2)]);
const bidirectional = new Q.BidirectionalGraph(true);
bidirectional.AddVertexRange(adjacency.Vertices); bidirectional.AddEdgeRange(adjacency.Edges);
const undirected = new Q.UndirectedGraph(true);
undirected.AddVertexRange(adjacency.Vertices); undirected.AddEdgeRange(adjacency.Edges);
const matrix = new Q.BidirectionalMatrixGraph(4);
matrix.AddEdgeRange([new Q.EquatableEdge(0, 1), new Q.EquatableEdge(1, 2), new Q.EquatableEdge(2, 2)]);
const cluster = new Q.ClusteredAdjacencyGraph(new Q.AdjacencyGraph(true));
cluster.AddVertex(9); const child = cluster.AddCluster(); child.AddVerticesAndEdge(new Q.EquatableEdge(0, 1));
child.AddCluster().AddVerticesAndEdge(new Q.EquatableEdge(1, 2));
const edgeList = new Q.EdgeListGraph(true, true); edgeList.AddEdgeRange(adjacency.Edges);
add('adjacency-int', adjacency);
add('array-adjacency-int', new Q.ArrayAdjacencyGraph(adjacency));
add('bidirectional-int', bidirectional);
add('array-bidirectional-int', new Q.ArrayBidirectionalGraph(bidirectional));
add('bidirectional-adapter-int', new Q.BidirectionalAdapterGraph(adjacency));
add('reversed-bidirectional-int', new Q.ReversedBidirectionalGraph(bidirectional));
add('undirected-bidirectional-int', new Q.UndirectedBidirectionalGraph(bidirectional));
add('undirected-int', undirected);
add('array-undirected-int', new Q.ArrayUndirectedGraph(undirected));
add('matrix-int', matrix);
add('compressed-int', new Q.CompressedSparseRowGraph(adjacency));
add('clustered-int', cluster);
add('edge-list-graph-int', edgeList);
add('adjacency-empty', new Q.AdjacencyGraph(false));
const strings = new Q.AdjacencyGraph(false);
strings.AddVertex('isolated'); strings.AddVerticesAndEdge(new Q.TaggedEdge('α', 'β', 2.5));
strings.AddVerticesAndEdge(new Q.TaggedEdge('β', 'emoji😀', -0.25));
add('adjacency-string-tagged', strings);
for (const [name, C] of [['edge-int', Q.Edge], ['equatable-edge-int', Q.EquatableEdge], ['undirected-edge-int', Q.UndirectedEdge], ['equatable-undirected-edge-int', Q.EquatableUndirectedEdge], ['s-edge-int', Q.SEdge], ['s-equatable-edge-int', Q.SEquatableEdge], ['s-undirected-edge-int', Q.SUndirectedEdge]]) add(name, new C(10, 20));
add('edge-string', new Q.Edge('α', 'emoji😀'));
for (const [name, C] of [['tagged-edge-int', Q.TaggedEdge], ['tagged-undirected-edge-int', Q.TaggedUndirectedEdge], ['equatable-tagged-edge-int', Q.EquatableTaggedEdge], ['s-tagged-edge-int', Q.STaggedEdge], ['s-equatable-tagged-edge-int', Q.SEquatableTaggedEdge], ['s-tagged-undirected-edge-int', Q.STaggedUndirectedEdge]]) add(name, new C(10, 20, 'weight'));
add('term-edge-int', new Q.TermEdge(10, 20, 3, 4));
add('equatable-term-edge-int', new Q.EquatableTermEdge(10, 20, 3, 4));
add('s-reversed-edge-int', new Q.SReversedEdge(new Q.EquatableEdge(10, 20)));
add('graphviz-color', new GraphvizColor(128, 10, 20, 30));
add('graphviz-size', new GraphvizSize(12, 34));
add('graphviz-size-f', new GraphvizSizeF(1.25, 2.5));
for (const [name, C, message] of [['non-acyclic-exception', Q.NonAcyclicGraphException, 'cycle'], ['non-strongly-connected-exception', Q.NonStronglyConnectedGraphException, 'disconnected'], ['parallel-edge-exception', Q.ParallelEdgeNotAllowedException, 'parallel'], ['vertex-not-found-exception', Q.VertexNotFoundException, 'missing'], ['no-path-exception', Q.NoPathFoundException, 'no path']]) add(name, new C(message));
add('vertex-list', new VertexList([5, 8, 13]));
add('edge-list', new EdgeList([new Q.EquatableEdge(0, 1), new Q.EquatableEdge(1, 2)]));
const queue = new Queue(); queue.Enqueue(3); queue.Enqueue(5); queue.Enqueue(8); queue.Dequeue(); add('queue', queue);
const vertexEdges = new VertexEdgeDictionary(); vertexEdges.set(1, new EdgeList([new Q.EquatableEdge(1, 2)])); vertexEdges.set(2, new EdgeList()); add('vertex-edge-dictionary', vertexEdges);
const edgeEdges = new EdgeEdgeDictionary(); edgeEdges.set(new Q.EquatableEdge(0, 1), new Q.EquatableEdge(1, 0)); add('edge-edge-dictionary', edgeEdges);
const exception = new Q.NegativeCycleGraphException('negative cycle'); exception.cause = new Q.InvalidOperationException('inner'); add('negative-cycle-exception', exception);
const doubles = new Q.AdjacencyGraph(); doubles.AddVertexRange([1, 2.5, 4]); doubles.AddEdgeRange([new Q.TaggedEdge(1, 2.5, 1), new Q.TaggedEdge(2.5, 4, 1.25)]); add('adjacency-double-tagged', doubles);
add('decimal-root', new NrbfDecimal('123.456'));
add('datetime-root', new NrbfDateTime(5248849013487387904n));
add('timespan-root', new NrbfPrimitive(NrbfPrimitiveType.TimeSpan, -1234567n));
add('vertex-list-empty', new VertexList());
add('edge-list-empty', new EdgeList());
add('edge-list-equatable-empty', new EdgeList());
const equatableType = ToNrbfRecord(new Q.EquatableEdge(0, 1));
options.set('edge-list-equatable-empty', {edgeType: {name: equatableType.TypeName, library: equatableType.LibraryName}});
add('queue-empty', new Queue());
await mkdir(output, {recursive: true});
for (const [name, value] of cases) await writeFile(resolve(output, name + '.nrbf'), SerializeNrbf(value, options.get(name)));
console.log(`Serialized ${cases.size} independently constructed JavaScript objects into ${output}`);
