import { scenarios, execute, label } from './scenarios.js';
import * as Q from '../src/index.js';
Q.defineQuikGraphViewer();
const $=id=>document.getElementById(id),viewer=$('viewer');
let current=scenarios[0],graph,selected,grid=false,runIndex=0;
function summarize(value){const seen=new WeakSet();return JSON.stringify(value,(_key,v)=>{if(v instanceof Map)return Object.fromEntries([...v].map(([k,val])=>[label(k),val]));if(v instanceof Set)return [...v];if(v&&typeof v==='object'){if(seen.has(v))return '[shared reference]';seen.add(v);}if(typeof v==='number'&&!Number.isFinite(v))return String(v);return v;},2);}
function updateGraph(){viewer.Graph=graph;viewer.VertexLabel=label;viewer.EdgeLabel=e=>e.Relation?.RelationName??(e.Annotation?'':e.Tag==null?'':String(e.Tag));const vs=[...graph.Vertices];for(const id of ['source','target']){$(id).replaceChildren(...vs.map((v,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=label(v);return o;}));}if(vs.length)$('target').value=String(vs.length-1);$('graph-kind').textContent=graph.IsDirected?'Directed graph':'Undirected graph';$('graph-count').textContent=`${graph.VertexCount} vertices · ${graph.EdgeCount} edges`;}
function selectScenario(id){current=scenarios.find(s=>s.id===id)??scenarios[0];graph=current.setup();selected=undefined;updateGraph();$('category').textContent=current.group.toUpperCase();$('title').textContent=current.id==='dijkstra'?'Shortest path, made visible.':current.label;$('description').textContent=current.description;for(const b of document.querySelectorAll('.scenario'))b.classList.toggle('selected',b.dataset.id===current.id);history.replaceState(null,'',`#${current.id}`);runScenario();}
export function runScenario(){const vs=[...graph.Vertices],source=vs[Number($('source').value)],target=vs[Number($('target').value)],started=performance.now();try{const result=execute(current.id,graph,source,target);viewer.HighlightedEdges=new Set(result.highlight);viewer.VertexColors=result.colors;viewer.Refresh();$('elapsed').textContent=`${(performance.now()-started).toFixed(2)} ms`;$('result-count').textContent=String(result.highlight.length||result.colors.size||(Array.isArray(result.result)?result.result.length:graph.VertexCount));$('result-summary').textContent=result.summary;$('output').textContent=typeof result.result==='string'?result.result:summarize(result.result);$('code').textContent=`import * as Q from '@wieslawsoltes/quikgraphweb';\n\n${result.code}`;$('output').dataset.status='success';runIndex++;return result;}catch(error){$('elapsed').textContent=`${(performance.now()-started).toFixed(2)} ms`;$('result-summary').textContent=error.message;$('output').textContent=`${error.name}: ${error.message}`;$('output').dataset.status='error';$('result-count').textContent='—';return{error:error.message,stack:error.stack};}}
function renderScenarios(filter=''){let group='';$('scenarios').replaceChildren();for(const s of scenarios.filter(s=>`${s.label} ${s.group}`.toLowerCase().includes(filter.toLowerCase()))){if(group!==s.group){const heading=document.createElement('div');heading.className='group-title';heading.textContent=s.group.toUpperCase();$('scenarios').append(heading);group=s.group;}const button=document.createElement('button');button.className=`scenario${s.id===current.id?' selected':''}`;button.dataset.id=s.id;const glyph=document.createElement('span');glyph.className='glyph';glyph.textContent={'Paths & traversal':'⌁','Structure & connectivity':'◇',Optimization:'△','Analysis & simulation':'◉','Formats & adapters':'▤','Structures & collections':'▦'}[s.group];button.append(glyph,document.createTextNode(s.label));button.addEventListener('click',()=>selectScenario(s.id));$('scenarios').append(button);}}
function renderApi(filter=''){$('api-list').replaceChildren(...Object.keys(Q).filter(k=>k.toLowerCase().includes(filter.toLowerCase())).sort().map(k=>{const el=document.createElement('div');el.textContent=k;return el;}));}
$('filter').addEventListener('input',event=>renderScenarios(event.target.value));$('api-filter').addEventListener('input',event=>renderApi(event.target.value));$('run').addEventListener('click',runScenario);$('reset').addEventListener('click',()=>selectScenario(current.id));$('fit').addEventListener('click',()=>viewer.Fit());$('layout').addEventListener('click',()=>viewer.Layout((grid=!grid)?'grid':'circle'));
$('theme').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('quikgraph-theme',document.documentElement.dataset.theme);viewer.Refresh();});
$('svg').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([viewer.ToSvg()],{type:'image/svg+xml'})),a=document.createElement('a');a.href=url;a.download='quikgraph.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
function addVertex(position){let n=graph.VertexCount+1;while(graph.ContainsVertex(`V${n}`))n++;const vertex=`V${n}`;graph.AddVertex(vertex);const positions=new Map(viewer.Positions);updateGraph();for(const[v,p]of positions)viewer.Positions.set(v,p);if(position)viewer.Positions.set(vertex,position);viewer.Refresh();}
$('add-vertex').addEventListener('click',()=>addVertex());$('add-edge').addEventListener('click',()=>{const vs=[...graph.Vertices],s=vs[Number($('source').value)],t=vs[Number($('target').value)],w=Number($('weight').value);if(s===undefined||t===undefined||!Number.isFinite(w))return;graph.AddEdge(new Q.TaggedEdge(s,t,w));$('graph-count').textContent=`${graph.VertexCount} vertices · ${graph.EdgeCount} edges`;viewer.Refresh();});
function removeSelected(){if(selected===undefined||!graph.ContainsVertex(selected))return;graph.RemoveVertex(selected);selected=undefined;updateGraph();}
$('remove-vertex').addEventListener('click',removeSelected);viewer.addEventListener('graph-select',event=>{selected=event.detail.vertex;$('selection').textContent=`Selected: ${label(selected)}`;});viewer.addEventListener('graph-create-vertex',event=>addVertex(event.detail));viewer.addEventListener('graph-delete-vertex',removeSelected);
for(const button of document.querySelectorAll('[data-tab]'))button.addEventListener('click',()=>{for(const tab of ['output','code','catalog'])$(tab).hidden=tab!==button.dataset.tab;for(const other of document.querySelectorAll('[data-tab]'))other.classList.toggle('selected',other===button);});
document.documentElement.dataset.theme=localStorage.getItem('quikgraph-theme')??'light';$('export-count').textContent=String(Object.keys(Q).length);renderScenarios();renderApi();selectScenario(location.hash.slice(1)||'dijkstra');
globalThis.quikgraphDemo={Q,scenarios,selectScenario,runScenario,get graph(){return graph;},get current(){return current;},get runIndex(){return runIndex;},viewer};
