import { scenarios, execute, executeAsync, label } from './scenarios.js';
import * as Q from '../src/index.js';
Q.defineQuikGraphViewer();
const $=id=>document.getElementById(id),viewer=$('viewer');
let current=scenarios[0],graph,selected,grid=false,runIndex=0,requestId=0,controller,previewUrl,lastResult,importBytes;
function summarize(value){const seen=new WeakSet();return JSON.stringify(value,(_key,v)=>{if(v instanceof Map)return Object.fromEntries([...v].map(([k,val])=>[label(k),val]));if(v instanceof Set)return [...v];if(v&&typeof v==='object'){if(seen.has(v))return '[shared reference]';seen.add(v);}if(typeof v==='number'&&!Number.isFinite(v))return String(v);return v;},2);}
function setBusy(busy){$('run').disabled=busy;$('cancel').hidden=!busy;$('output').setAttribute('aria-busy',String(busy));$('run').textContent=busy?'Working…':'▶  Run algorithm';}
function cancelCurrent(message){requestId++;controller?.abort();controller=null;viewer.CancelLayout();setBusy(false);if(message){$('result-summary').textContent=message;$('output').dataset.status='cancelled';}}
function updateGraph(){for(const [id,method]of [['add-vertex','AddVertex'],['add-edge','AddEdge'],['remove-vertex','RemoveVertex']])$(id).disabled=typeof graph[method]!=='function';viewer.Graph=graph;viewer.VertexLabel=label;viewer.EdgeLabel=e=>e.Relation?.RelationName??(e.Annotation?'':e.Tag==null?'':String(e.Tag));const vs=[...graph.Vertices];for(const id of ['source','target']){$(id).replaceChildren(...vs.map((v,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=label(v);return o;}));}if(vs.length)$('target').value=String(vs.length-1);$('graph-kind').textContent=graph.IsDirected?'Directed graph':'Undirected graph';$('graph-count').textContent=`${graph.VertexCount} vertices · ${graph.EdgeCount} edges`;}
function addSelect(name,id,values,requiresRun=true){const wrapper=document.createElement('label');wrapper.textContent=name;const input=document.createElement('select');input.id=id;for(const value of values){const option=document.createElement('option');option.value=value;option.textContent=value;input.append(option);}if(requiresRun)input.addEventListener('change',()=>cancelCurrent('Configuration changed. Run again to update the result.'));wrapper.append(input);$('feature-options').append(wrapper);}
function configureFeature(){
 importBytes=undefined;$('binary-input').value='';$('binary-controls').hidden=current.id!=='binary';$('download-binary').disabled=true;$('feature-options').replaceChildren();$('feature-options').hidden=!current.async;$('feature-editor').hidden=!['graphviz-render','graphml-validate'].includes(current.id);$('native-preview-tab').hidden=true;$('prepare-dot').hidden=current.id!=='graphviz-render';$('prepare-dot').disabled=true;lastResult=null;
 if(current.id==='graphviz-render'){addSelect('Graphviz engine','engine',['dot','neato','fdp','sfdp','circo','twopi','osage','patchwork','nop','nop1','nop2']);addSelect('Native output format','output-format',['svg'],false);const nativeExport=document.createElement('button');nativeExport.type='button';nativeExport.id='download-format';nativeExport.textContent='Download native format';nativeExport.disabled=true;nativeExport.addEventListener('click',downloadNativeFormat);$('feature-options').append(nativeExport);addSelect('Raster format','raster-format',['png','jpeg','webp'],false);$('editor-title').textContent='DOT source';$('feature-text').setAttribute('aria-label','DOT source');$('feature-text').value=execute('graphviz',graph).result;}
 if(current.id==='msagl-layout'){addSelect('Layout algorithm','algorithm',['Sugiyama','MDS','IPsepCola']);addSelect('Layout direction','direction',['TB','LR','BT','RL']);addSelect('Edge routing','routing',['Spline','SplineBundling','StraightLine','SugiyamaSplines','Rectilinear','None']);}
 if(current.id==='graphml-validate'){$('editor-title').textContent='GraphML document';$('feature-text').setAttribute('aria-label','GraphML document');$('feature-text').value=Q.SerializeToGraphML(graph);}
 showTab('output');if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}$('preview-image').removeAttribute('src');
}
function selectScenario(id){cancelCurrent();current=scenarios.find(s=>s.id===id)??scenarios[0];graph=current.setup();selected=undefined;updateGraph();configureFeature();$('selection').textContent='Select a vertex or edge to inspect';$('category').textContent=current.group.toUpperCase();$('title').textContent=current.id==='dijkstra'?'Shortest path, made visible.':current.label;$('description').textContent=current.description;for(const b of document.querySelectorAll('.scenario'))b.classList.toggle('selected',b.dataset.id===current.id);history.replaceState(null,'',`#${current.id}`);return runScenario();}
function options(){return{signal:controller.signal,text:$('feature-editor').hidden?undefined:$('feature-text').value,engine:$('engine')?.value,algorithm:$('algorithm')?.value,direction:$('direction')?.value,routing:$('routing')?.value,bytes:importBytes};}
export async function runScenario(){
 cancelCurrent();controller=new AbortController();const id=++requestId,scenario=current,inputGraph=graph,vs=[...graph.Vertices],source=vs[Number($('source').value)],target=vs[Number($('target').value)],started=performance.now(),settings=options();setBusy(true);$('output').dataset.status='running';$('output').dataset.scenario=scenario.id;$('result-summary').textContent=scenario.async?'Loading and running the selected engine…':'Running…';
 try{
  const result=scenario.async?await executeAsync(scenario.id,inputGraph,source,target,settings):execute(scenario.id,inputGraph,source,target);
  if(id!==requestId||settings.signal.aborted||graph!==inputGraph)return;
  if(result.layoutResult)await viewer.LayoutAsync(()=>result.layoutResult,{signal:settings.signal});
  if(id!==requestId||settings.signal.aborted)return;
  if(result.importedGraph){graph=result.importedGraph;selected=undefined;updateGraph();}viewer.HighlightedEdges=new Set(result.highlight);viewer.VertexColors=result.colors;viewer.Refresh();$('elapsed').textContent=`${(performance.now()-started).toFixed(2)} ms`;$('result-count').textContent=String(result.highlight.length||result.colors.size||(Array.isArray(result.result)?result.result.length:graph.VertexCount));$('result-summary').textContent=result.summary;$('output').textContent=typeof result.result==='string'?result.result:summarize(result.result);$('code').textContent=(scenario.async?'':"import * as Q from '@wieslawsoltes/quikgraphweb';\n\n")+result.code;$('output').dataset.status='success';lastResult=result;$('download-binary').disabled=!result.binaryBytes;if(result.formats){setChoices('output-format',result.formats,'svg');setChoices('engine',result.engines,$('engine').value);$('download-format').disabled=false;$('prepare-dot').disabled=false;}
  if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}
  $('native-preview-tab').hidden=!result.previewSvg;if(result.previewSvg){previewUrl=URL.createObjectURL(new Blob([result.previewSvg],{type:'image/svg+xml'}));$('preview-image').src=previewUrl;$('preview-image').alt=`${scenario.label} rendered graph`;$('download-png').hidden=!result.download;showTab('preview');}
  runIndex++;return result;
 }catch(error){if(id!==requestId||error.name==='AbortError')return; $('elapsed').textContent=`${(performance.now()-started).toFixed(2)} ms`;$('result-summary').textContent=error.message;$('output').textContent=`${error.name}: ${error.message}${error.Diagnostics?'\n'+summarize(error.Diagnostics):''}`;$('output').dataset.status='error';$('result-count').textContent='—';showTab('output');return{error:error.message,stack:error.stack};}
 finally{if(id===requestId){setBusy(false);controller=null;}}
}
function setChoices(id,values,fallback){const select=$(id),value=select.value;select.replaceChildren(...values.map(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;return option;}));select.value=values.includes(value)?value:fallback;}
function downloadNativeFormat(){if(!lastResult?.exportFormat)return;try{const format=$('output-format').value,text=lastResult.exportFormat(format,$('feature-text').value,$('engine').value),type=format==='svg'?'image/svg+xml':format.includes('json')?'application/json':'text/plain';downloadBlob(new Blob([text],{type}),`quikgraph-native.${format.replace(/[^a-z0-9]/ig,'')}`);}catch(error){$('result-summary').textContent=error.message;$('output').textContent=`${error.name}: ${error.message}`;$('output').dataset.status='error';showTab('output');}}
$('prepare-dot').addEventListener('click',()=>{if(!lastResult?.prepareDot)return;try{$('feature-text').value=lastResult.prepareDot($('feature-text').value);runScenario();}catch(error){$('result-summary').textContent=error.message;$('output').textContent=`${error.name}: ${error.message}`;$('output').dataset.status='error';showTab('output');}});
function renderScenarios(filter=''){let group='';$('scenarios').replaceChildren();for(const s of scenarios.filter(s=>`${s.label} ${s.group}`.toLowerCase().includes(filter.toLowerCase()))){if(group!==s.group){const heading=document.createElement('div');heading.className='group-title';heading.textContent=s.group.toUpperCase();$('scenarios').append(heading);group=s.group;}const button=document.createElement('button');button.className=`scenario${s.id===current.id?' selected':''}`;button.dataset.id=s.id;const glyph=document.createElement('span');glyph.className='glyph';glyph.textContent={'Paths & traversal':'⌁','Structure & connectivity':'◇',Optimization:'△','Analysis & simulation':'◉','Formats & adapters':'▤','Structures & collections':'▦','Native engines':'◈'}[s.group];button.append(glyph,document.createTextNode(s.label));button.addEventListener('click',()=>selectScenario(s.id));$('scenarios').append(button);}}
function renderApi(filter=''){$('api-list').replaceChildren(...Object.keys(Q).filter(k=>k.toLowerCase().includes(filter.toLowerCase())).sort().map(k=>{const el=document.createElement('div');el.textContent=k;return el;}));}
$('filter').addEventListener('input',event=>renderScenarios(event.target.value));$('api-filter').addEventListener('input',event=>renderApi(event.target.value));$('run').addEventListener('click',runScenario);$('cancel').addEventListener('click',()=>cancelCurrent('Operation cancelled. The previous graph layout is retained.'));$('reset').addEventListener('click',()=>selectScenario(current.id));$('fit').addEventListener('click',()=>viewer.Fit());$('layout').addEventListener('click',()=>{cancelCurrent();viewer.Layout((grid=!grid)?'grid':'circle');});
$('feature-text').addEventListener('input',()=>cancelCurrent('Source changed. Run again to update the result.'));$('invalid-source').addEventListener('click',()=>{cancelCurrent();$('feature-text').value=current.id==='graphviz-render'?'digraph { A -> ; }':Q.SerializeToGraphML(graph).replace(/<graph\b/,'<graph parse.nodes="-1"');runScenario();});$('restore-source').addEventListener('click',()=>{cancelCurrent();$('feature-text').value=current.id==='graphviz-render'?execute('graphviz',graph).result:Q.SerializeToGraphML(graph);runScenario();});
$('theme').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('quikgraph-theme',document.documentElement.dataset.theme);viewer.Refresh();});
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download-binary').addEventListener('click',()=>{if(lastResult?.binaryBytes)downloadBlob(new Blob([lastResult.binaryBytes],{type:'application/octet-stream'}),'quikgraph.bin');});
$('binary-input').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;cancelCurrent();const id=requestId;setBusy(true);$('output').dataset.status='running';try{if(file.size>10*1024*1024)throw new RangeError('Choose an NRBF file no larger than 10 MB.');const bytes=new Uint8Array(await file.arrayBuffer());if(id!==requestId||current.id!=='binary')return;importBytes=bytes;runScenario();}catch(error){if(id===requestId){setBusy(false);$('result-summary').textContent=error.message;$('output').textContent=`${error.name}: ${error.message}`;$('output').dataset.status='error';}}});
$('svg').addEventListener('click',()=>downloadBlob(new Blob([viewer.ToSvg()],{type:'image/svg+xml'}),'quikgraph.svg'));
$('download-native-svg').addEventListener('click',()=>{if(lastResult?.previewSvg)downloadBlob(new Blob([lastResult.previewSvg],{type:'image/svg+xml'}),'quikgraph-native.svg');});
$('download-png').addEventListener('click',async()=>{const result=lastResult;if(!result?.download)return;const button=$('download-png');button.disabled=true;try{const format=$('raster-format')?.value??'png',blob=await result.download(`image/${format}`);if(result===lastResult)downloadBlob(blob,`quikgraph-native.${format}`);}catch(error){$('result-summary').textContent=error.message;}finally{button.disabled=false;}});
function addVertex(position){if(typeof graph.AddVertex!=='function')return;cancelCurrent();let n=graph.VertexCount+1;while(graph.ContainsVertex(`V${n}`))n++;const vertex=`V${n}`;graph.AddVertex(vertex);const positions=new Map(viewer.Positions);updateGraph();for(const[v,p]of positions)viewer.Positions.set(v,p);if(position)viewer.Positions.set(vertex,position);viewer.Refresh();}
$('add-vertex').addEventListener('click',()=>addVertex());$('add-edge').addEventListener('click',()=>{if(typeof graph.AddEdge!=='function')return;cancelCurrent();const vs=[...graph.Vertices],s=vs[Number($('source').value)],t=vs[Number($('target').value)],w=Number($('weight').value);if(s===undefined||t===undefined||!Number.isFinite(w))return;graph.AddEdge(new Q.TaggedEdge(s,t,w));$('graph-count').textContent=`${graph.VertexCount} vertices · ${graph.EdgeCount} edges`;viewer.Refresh();});
function removeSelected(){if(typeof graph.RemoveVertex!=='function'||selected===undefined||!graph.ContainsVertex(selected))return;cancelCurrent();graph.RemoveVertex(selected);selected=undefined;updateGraph();}
$('remove-vertex').addEventListener('click',removeSelected);viewer.addEventListener('graph-select',event=>{selected=event.detail.vertex;$('selection').textContent=`Selected: ${label(selected)}`;});viewer.addEventListener('graph-select-edge',event=>{selected=undefined;$('selection').textContent=`Edge: ${label(event.detail.edge.Source)} → ${label(event.detail.edge.Target)}`;});viewer.addEventListener('graph-create-vertex',event=>addVertex(event.detail));viewer.addEventListener('graph-delete-vertex',removeSelected);viewer.addEventListener('graph-delete-edge',event=>{if(typeof graph.RemoveEdge!=='function')return;cancelCurrent();graph.RemoveEdge(event.detail.edge);$('graph-count').textContent=`${graph.VertexCount} vertices · ${graph.EdgeCount} edges`;viewer.Refresh();});
function showTab(name){for(const tab of ['output','code','catalog','preview'])$(tab).hidden=tab!==name;for(const button of document.querySelectorAll('[data-tab]'))button.classList.toggle('selected',button.dataset.tab===name);}
for(const button of document.querySelectorAll('[data-tab]'))button.addEventListener('click',()=>showTab(button.dataset.tab));
document.documentElement.dataset.theme=localStorage.getItem('quikgraph-theme')??'light';$('export-count').textContent=String(Object.keys(Q).length);renderScenarios();renderApi();selectScenario(location.hash.slice(1)||'dijkstra');
globalThis.quikgraphDemo={Q,scenarios,selectScenario,runScenario,get graph(){return graph;},get current(){return current;},get runIndex(){return runIndex;},viewer};
