import {createServer} from 'node:http';import {readFile,mkdir,stat} from 'node:fs/promises';import {resolve,extname,sep} from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';
const root=resolve('site'),mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+sep))throw new Error('Invalid path');res.writeHead(200,{'Content-Type':mime[extname(file)]??'application/octet-stream'});res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH}:{}),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1040}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForSelector('.scenario');assert.equal(await page.locator('#output').getAttribute('data-status'),'success');assert.match(await page.locator('#output').textContent(),/"distance": 16/);
 const labels=await page.locator('.scenario').allTextContents();for(const label of labels){await page.getByRole('button',{name:label,exact:true}).click();assert.equal(await page.locator('#output').getAttribute('data-status'),'success',`Example failed: ${label}: ${await page.locator('#output').textContent()}`);}
 await page.locator('[data-id="dijkstra"]').click();await page.getByRole('button',{name:'＋ Add vertex',exact:true}).click();assert.match(await page.locator('#graph-count').textContent(),/^9 vertices/);await page.locator('#reset').click();assert.match(await page.locator('#graph-count').textContent(),/^8 vertices/);
 await page.getByLabel('Source vertex').selectOption({label:'B'});await page.getByLabel('Target vertex').selectOption({label:'H'});await page.getByRole('button',{name:'Run algorithm'}).click();assert.match(await page.locator('#output').textContent(),/"distance": 12/);
 await page.locator('[data-tab="code"]').click();assert.match(await page.locator('#code').textContent(),/DijkstraShortestPathAlgorithm/);await page.locator('[data-tab="catalog"]').click();await page.getByLabel('Filter API exports').fill('Fibonacci');assert.ok(await page.locator('#api-list div').count()>=2);await page.locator('[data-tab="output"]').click();
 await page.locator('#reset').click();const canvas=page.locator('quikgraph-viewer canvas');const position=await canvas.boundingBox();await page.mouse.move(position.x+position.width/2,position.y+position.height/2);await page.mouse.wheel(0,-300);await canvas.press('0');await page.locator('#layout').click();await page.locator('#fit').click();
 const download=page.waitForEvent('download');await page.locator('#svg').click();const artifact=await download;assert.equal(artifact.suggestedFilename(),'quikgraph.svg');await mkdir('test-results',{recursive:true});await artifact.saveAs('test-results/graph.svg');assert.match(await readFile('test-results/graph.svg','utf8'),/<svg/);
 await page.locator('#reset').click();await page.screenshot({path:'test-results/showcase-light.png',fullPage:true});await page.getByRole('button',{name:'Switch color theme'}).click();await page.screenshot({path:'test-results/showcase-dark.png',fullPage:true});
 const workerResult=await page.evaluate(async(base)=>{const source=`import {BidirectionalGraph,TaggedEdge,DijkstraShortestPathAlgorithm} from '${base}/src/index.js';const g=new BidirectionalGraph();g.AddVerticesAndEdge(new TaggedEdge('a','b',7));const a=new DijkstraShortestPathAlgorithm(g,e=>e.Tag);a.Compute('a');postMessage(a.Distances.get('b'));`;const url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));try{return await new Promise((resolve,reject)=>{const worker=new Worker(url,{type:'module'});worker.onmessage=e=>{worker.terminate();resolve(e.data);};worker.onerror=e=>{worker.terminate();reject(new Error(e.message));};});}finally{URL.revokeObjectURL(url);}},url);assert.equal(workerResult,7);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/showcase-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile viewport must not overflow horizontally');assert.deepEqual(errors,[]);console.log(JSON.stringify({examples:labels.length,checks:['weighted route','all examples','graph editing','endpoint selection','code tab','API filter','pan/zoom/fit','SVG export','light/dark','mobile layout','worker module'],pageErrors:errors}));
}finally{await browser?.close();await new Promise(r=>server.close(r));}
