import {createServer} from 'node:http';import {readFile,mkdir,stat} from 'node:fs/promises';import {resolve,extname,sep} from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';
const root=resolve('site'),mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+sep))throw new Error('Invalid path');const bytes=await readFile(file);res.writeHead(200,{'Content-Type':mime[extname(file)]??'application/octet-stream'});res.end(bytes);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH}:{}),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1040}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForSelector('.scenario');const waitForResult=async(id)=>{await page.waitForFunction(id=>{const output=document.getElementById('output');return output.dataset.scenario===id&&['success','error'].includes(output.dataset.status);},id,{timeout:120000});};assert.equal(await page.locator('#output').getAttribute('data-status'),'success');assert.match(await page.locator('#output').textContent(),/"distance": 16/);
 const labels=await page.locator('.scenario').evaluateAll(nodes=>nodes.map(node=>({id:node.dataset.id,label:node.textContent})));for(const {id,label} of labels){await page.locator(`.scenario[data-id="${id}"]`).click();await waitForResult(id);assert.equal(await page.locator('#output').getAttribute('data-status'),'success',`Example failed: ${label}: ${await page.locator('#output').textContent()}`);}
 await page.locator('[data-id="graphviz-render"]').click();await waitForResult('graphviz-render');await page.waitForFunction(()=>{const img=document.getElementById('preview-image');return img.complete&&img.naturalWidth>0;});await page.getByLabel('Graphviz engine').selectOption('circo');await page.locator('#run').click();await waitForResult('graphviz-render');assert.match(await page.locator('#output').textContent(),/"engine": "circo"/);
 const pngDownload=page.waitForEvent('download');await page.locator('#download-png').click();const png=await pngDownload;await mkdir('test-results',{recursive:true});await png.saveAs('test-results/native-graph.png');await page.screenshot({path:'test-results/showcase-graphviz.png',fullPage:true});assert.equal(await page.locator('#engine option').count(),11);assert.equal(await page.locator('#output-format option').count(),27);await page.getByLabel('Native output format').selectOption('plain');const plainDownload=page.waitForEvent('download');await page.locator('#download-format').click();const plain=await plainDownload;await plain.saveAs('test-results/native-graph.plain');assert.match(await readFile('test-results/native-graph.plain','utf8'),/^graph /);await page.getByLabel('Graphviz engine').selectOption('nop2');await page.locator('#prepare-dot').click();await waitForResult('graphviz-render');assert.equal(await page.locator('#output').getAttribute('data-status'),'success');assert.match(await page.getByLabel('DOT source').inputValue(),/pos=/);await page.getByLabel('Graphviz engine').selectOption('circo');await page.locator('#run').click();await waitForResult('graphviz-render');assert.deepEqual([...((await readFile('test-results/native-graph.png')).subarray(0,8))],[137,80,78,71,13,10,26,10]);
 await page.locator('#invalid-source').click();await waitForResult('graphviz-render');assert.equal(await page.locator('#output').getAttribute('data-status'),'error');await page.locator('#restore-source').click();await waitForResult('graphviz-render');assert.equal(await page.locator('#output').getAttribute('data-status'),'success');
 await page.locator('[data-id="graphml-validate"]').click();await waitForResult('graphml-validate');assert.match(await page.locator('#output').textContent(),/"IsValid": true/);await page.locator('#invalid-source').click();await waitForResult('graphml-validate');assert.match(await page.locator('#output').textContent(),/"IsValid": false/);assert.match(await page.locator('#output').textContent(),/LineNumber/);await page.locator('#restore-source').click();await waitForResult('graphml-validate');assert.match(await page.locator('#output').textContent(),/"IsValid": true/);
 await page.locator('[data-id="msagl-layout"]').click();await waitForResult('msagl-layout');await page.waitForFunction(()=>{const img=document.getElementById('preview-image');return img.complete&&img.naturalWidth>0;});await page.screenshot({path:'test-results/showcase-native-layout.png',fullPage:true});assert.equal(await page.evaluate(()=>{const viewer=document.querySelector('quikgraph-viewer');return viewer.LayoutResult.Edges.some(edge=>viewer.ToSvg().includes(edge.Path));}),true);await page.getByLabel('Layout algorithm').selectOption('MDS');await page.getByLabel('Edge routing').selectOption('StraightLine');await page.locator('#run').click();await waitForResult('msagl-layout');assert.equal(await page.locator('#output').getAttribute('data-status'),'success');
 await page.locator('[data-id="binary"]').click();await waitForResult('binary');assert.match(await page.locator('#output').textContent(),/NRBF \/ BinaryFormatter/);const binaryDownload=page.waitForEvent('download');await page.locator('#download-binary').click();const binary=await binaryDownload;await binary.saveAs('test-results/graph.bin');await page.locator('#binary-input').setInputFiles('test-results/graph.bin');await waitForResult('binary');assert.match(await page.locator('#result-summary').textContent(),/Imported 8 vertices and 12 edges/);await page.locator('#binary-input').setInputFiles({name:'invalid.bin',mimeType:'application/octet-stream',buffer:Buffer.from([1,2,3])});await waitForResult('binary');assert.equal(await page.locator('#output').getAttribute('data-status'),'error');assert.match(await page.locator('#output').textContent(),/NrbfFormatError/);await page.locator('#reset').click();await waitForResult('binary');assert.equal(await page.locator('#output').getAttribute('data-status'),'success');
 const nativeGraphviz=await page.evaluate(async()=>{
  const {CreateGraphvizEngine}=await import('./dist/quikgraphweb-graphviz.js'),engine=await CreateGraphvizEngine();
  try{
   const dot='digraph {graph [bgcolor="transparent"];node [shape=box,style=filled,fillcolor="#e02020",fontcolor="white"];a [label="Alpha"];b [label="Beta"];a->b;}',element=engine.RenderSvgElement(dot),images=[];
   for(const type of ['image/png','image/jpeg','image/webp']){
    const image=await engine.RenderImage(dot,{type,width:320,quality:.9,background:'#ffffff',renderOptions:{engine:'dot'}}),bytes=new Uint8Array(await image.arrayBuffer()),bitmap=await createImageBitmap(image),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;
    const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(bitmap,0,0);const pixels=context.getImageData(0,0,canvas.width,canvas.height).data;let redPixels=0,nonWhitePixels=0;
    for(let i=0;i<pixels.length;i+=4){if(pixels[i+3]>200&&pixels[i]>140&&pixels[i+1]<100&&pixels[i+2]<100)redPixels++;if(pixels[i+3]>200&&(pixels[i]<230||pixels[i+1]<230||pixels[i+2]<230))nonWhitePixels++;}
    images.push({type:image.type,width:bitmap.width,height:bitmap.height,signature:[...bytes.subarray(0,12)],size:bytes.byteLength,redPixels,nonWhitePixels});bitmap.close();
   }
   return{namespace:element.namespaceURI,nodes:element.querySelectorAll('.node').length,edges:element.querySelectorAll('.edge').length,inserted:document.contains(element),labels:[...element.querySelectorAll('text')].map(node=>node.textContent),images};
  }finally{engine.Dispose();}
 });
 assert.equal(nativeGraphviz.namespace,'http://www.w3.org/2000/svg');assert.equal(nativeGraphviz.nodes,2);assert.equal(nativeGraphviz.edges,1);assert.equal(nativeGraphviz.inserted,false);assert.deepEqual(nativeGraphviz.labels,['Alpha','Beta']);
 for(const [i,type]of ['image/png','image/jpeg','image/webp'].entries()){const image=nativeGraphviz.images[i];assert.equal(image.type,type);assert.equal(image.width,320);assert(image.height>0);assert(image.size>100);assert(image.redPixels>100,`${type} must preserve actual red graph-node pixels`);assert(image.nonWhitePixels>image.redPixels,`${type} must contain graph text and borders`);if(type==='image/png')assert.deepEqual(image.signature.slice(0,8),[137,80,78,71,13,10,26,10]);else if(type==='image/jpeg')assert.deepEqual(image.signature.slice(0,3),[255,216,255]);else{assert.deepEqual(image.signature.slice(0,4),[82,73,70,70]);assert.deepEqual(image.signature.slice(8,12),[87,69,66,80]);}}
 await page.locator('[data-id="dijkstra"]').click();await page.getByRole('button',{name:'＋ Add vertex',exact:true}).click();assert.match(await page.locator('#graph-count').textContent(),/^9 vertices/);await page.locator('#reset').click();assert.match(await page.locator('#graph-count').textContent(),/^8 vertices/);
 await page.getByLabel('Source vertex').selectOption({label:'B'});await page.getByLabel('Target vertex').selectOption({label:'H'});await page.getByRole('button',{name:'Run algorithm'}).click();assert.match(await page.locator('#output').textContent(),/"distance": 12/);
 await page.locator('[data-tab="code"]').click();assert.match(await page.locator('#code').textContent(),/DijkstraShortestPathAlgorithm/);await page.locator('[data-tab="catalog"]').click();await page.getByLabel('Filter API exports').fill('Fibonacci');assert.ok(await page.locator('#api-list div').count()>=2);await page.locator('[data-tab="output"]').click();
 await page.locator('#reset').click();const canvas=page.locator('quikgraph-viewer canvas');const position=await canvas.boundingBox();await page.mouse.move(position.x+position.width/2,position.y+position.height/2);const beforePan=await canvas.evaluate(c=>c.toDataURL());await page.mouse.down();await page.mouse.move(position.x+position.width/2+55,position.y+position.height/2+30,{steps:4});await page.mouse.up();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),beforePan,'Dragging the background must redraw the camera');await page.mouse.wheel(0,-300);await canvas.press('0');await page.locator('#layout').click();await page.locator('#fit').click();
 await page.locator('quikgraph-viewer summary').click();const vertexList=page.getByRole('listbox',{name:'Graph vertices'});await vertexList.getByRole('option').first().waitFor();assert.equal(await vertexList.getByRole('option').count(),8);await vertexList.press('End');await vertexList.press('Enter');assert.match(await page.locator('#selection').textContent(),/Selected: H/);const beforeKeyboardMove=await canvas.evaluate(c=>c.toDataURL());await vertexList.press('Escape');await canvas.press('Shift+ArrowRight');await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),beforeKeyboardMove);
 await page.getByLabel('Graph item type').selectOption('edges');await page.getByLabel('Find graph items').fill('A to B');const edgeList=page.getByRole('listbox',{name:'Graph edges'});assert.equal(await edgeList.getByRole('option').count(),1);await edgeList.press('Enter');assert.match(await page.locator('#selection').textContent(),/Edge: A → B/);await edgeList.press('Delete');assert.match(await page.locator('#graph-count').textContent(),/11 edges/);await page.getByLabel('Find graph items').fill('');await page.locator('quikgraph-viewer summary').click();await page.locator('#reset').click();
 const download=page.waitForEvent('download');await page.locator('#svg').click();const artifact=await download;assert.equal(artifact.suggestedFilename(),'quikgraph.svg');await mkdir('test-results',{recursive:true});await artifact.saveAs('test-results/graph.svg');assert.match(await readFile('test-results/graph.svg','utf8'),/<svg/);
 await page.locator('#reset').click();await page.screenshot({path:'test-results/showcase-light.png',fullPage:true});await page.getByRole('button',{name:'Switch color theme'}).click();await page.screenshot({path:'test-results/showcase-dark.png',fullPage:true});
 const workerResult=await page.evaluate(async(base)=>{const source=`import {BidirectionalGraph,TaggedEdge,DijkstraShortestPathAlgorithm} from '${base}/src/index.js';const g=new BidirectionalGraph();g.AddVerticesAndEdge(new TaggedEdge('a','b',7));const a=new DijkstraShortestPathAlgorithm(g,e=>e.Tag);a.Compute('a');postMessage(a.Distances.get('b'));`;const url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));try{return await new Promise((resolve,reject)=>{const worker=new Worker(url,{type:'module'}),timer=setTimeout(()=>{worker.terminate();reject(new Error('Worker timed out'));},10000);worker.onmessage=e=>{clearTimeout(timer);worker.terminate();resolve(e.data);};worker.onerror=e=>{clearTimeout(timer);worker.terminate();reject(new Error(e.message));};});}finally{URL.revokeObjectURL(url);}},url);assert.equal(workerResult,7);
 const registrations=await page.evaluate(async()=>{const Q=await import('./src/index.js');const first=Q.defineQuikGraphViewer('quikgraph-test-one'),second=Q.defineQuikGraphViewer('quikgraph-test-two');class Vertex{constructor(id){this.id=id;}Equals(other){return other instanceof Vertex&&this.id===other.id;}GetHashCode(){return 1;}toString(){return this.id;}}const g=new Q.BidirectionalGraph();g.AddVertexRange([new Vertex('a'),new Vertex('b')]);g.AddEdge(new Q.TaggedEdge(new Vertex('a'),new Vertex('b'),'copied'));const element=document.createElement('quikgraph-test-one');element.style.height='240px';document.body.append(element);element.Graph=g;const svg=element.ToSvg(),result={distinct:first!==second,instance:element instanceof Q.QuikGraphViewer,registered:Q.defineQuikGraphViewer('quikgraph-test-one')===first,edge:svg.includes('copied'),vertices:element.Positions.size};element.remove();return result;});assert.deepEqual(registrations,{distinct:true,instance:true,registered:true,edge:true,vertices:2});
 const inspection=await page.evaluate(async()=>{const Q=await import('./src/index.js'),viewer=document.createElement('quikgraph-viewer'),graph=new Q.BidirectionalGraph();graph.AddVertexRange(Array.from({length:10000},(_,i)=>`node ${i}`));viewer.style.height='240px';document.body.append(viewer);viewer.Graph=graph;await new Promise(resolve=>{const details=viewer.shadowRoot.querySelector('details');details.addEventListener('toggle',resolve,{once:true});details.open=true;});const list=viewer.shadowRoot.querySelector('[role=listbox]'),result={rendered:list.querySelectorAll('[role=option]').length,total:list.querySelector('[role=option]').getAttribute('aria-setsize')};viewer.remove();return result;});assert.deepEqual(inspection,{rendered:50,total:'10000'});
 const racePage=await browser.newPage();let unblock;const gate=new Promise(resolve=>unblock=resolve);await racePage.route('**/dist/quikgraphweb-graphviz.js',async route=>{await gate;await route.continue();});await racePage.goto(url);await racePage.waitForSelector('.scenario');
 try{const requested=racePage.waitForRequest(request=>request.url().endsWith('/dist/quikgraphweb-graphviz.js')),staleRun=racePage.evaluate(()=>globalThis.quikgraphDemo.selectScenario('graphviz-render'));await requested;assert.equal(await racePage.locator('#output').getAttribute('data-status'),'running');await racePage.locator('[data-id="dijkstra"]').click();unblock();await staleRun;assert.equal(await racePage.locator('#output').getAttribute('data-scenario'),'dijkstra');assert.equal(await racePage.locator('#output').getAttribute('data-status'),'success');assert.match(await racePage.locator('#output').textContent(),/"distance": 16/);}finally{unblock();await racePage.close();}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot({path:'test-results/showcase-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile viewport must not overflow horizontally');assert.deepEqual(errors,[]);console.log(JSON.stringify({examples:labels.length,checks:['weighted route','all examples','graph editing','endpoint selection','code tab','API filter','pan/zoom/fit','SVG export','light/dark','mobile layout','worker module','multiple component tags','custom vertex equality','native Graphviz SVG and PNG/JPEG/WebP pixels','11 Graphviz engines and 27 native formats','positioned DOT nop2','editable DOT errors','real XSD diagnostics','native MSAGL routes','accessible graph navigation','10000-item DOM window','stale async results','NRBF import/export'],pageErrors:errors}));
}finally{await browser?.close();await new Promise(r=>server.close(r));}
