/** A data-only reader/writer for the MS-NRBF object graph wire format. */
export const NrbfPrimitiveType = Object.freeze({Boolean:1,Byte:2,Char:3,Decimal:5,Double:6,Int16:7,Int32:8,Int64:9,SByte:10,Single:11,TimeSpan:12,DateTime:13,UInt16:14,UInt32:15,UInt64:16,Null:17,String:18});
export const NrbfBinaryType = Object.freeze({Primitive:0,String:1,Object:2,SystemClass:3,Class:4,ObjectArray:5,StringArray:6,PrimitiveArray:7});
const P=NrbfPrimitiveType,B=NrbfBinaryType,utf8=new TextEncoder(),decoder=new TextDecoder('utf-8',{fatal:true});
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
const primitiveTypes=new Set(Object.values(P));
const fail=message=>{throw new NrbfFormatError(message);};
function checkedLimits(options){for(const [name,value]of Object.entries(options))if(name.startsWith('max')&&(!Number.isSafeInteger(value)||value<0))throw new RangeError(`${name} must be a nonnegative safe integer`);return options;}
export class NrbfPrimitive {constructor(type,value){if(!primitiveTypes.has(type)||type>=P.Null)throw new TypeError('Invalid boxed primitive type');this.Type=type;this.Value=value;}valueOf(){return this.Value;}toString(){return String(this.Value);}}
export class NrbfFormatError extends Error {constructor(message){super(message);this.name='NrbfFormatError';}}
/** Decimal preserves all .NET decimal digits; it never passes through IEEE-754. */
export class NrbfDecimal {constructor(value){const text=String(value);if(!/^-?\d+(?:\.\d+)?$/.test(text))throw new TypeError('Invalid decimal');const negative=text.startsWith('-');let [whole,fraction='']=text.replace(/^-/,'').split('.');whole=whole.replace(/^0+(?=\d)/,'');const outside=()=>{throw new RangeError('Decimal is outside the CLR 96-bit coefficient and 28-digit scale');};if(whole.length>29)outside();if(fraction.length>28){if(!/^0*$/.test(fraction.slice(28)))outside();fraction=fraction.slice(0,28);}let digits=(whole+fraction).replace(/^0+/,'')||'0';if(digits.length>29){fraction=fraction.replace(/0+$/,'');digits=(whole+fraction).replace(/^0+/,'')||'0';}if(digits.length>29)outside();let coefficient=BigInt(digits);if(coefficient>0xffffffffffffffffffffffffn&&fraction.endsWith('0')){fraction=fraction.replace(/0+$/,'');coefficient=BigInt(whole+fraction);}if(coefficient>0xffffffffffffffffffffffffn)outside();this.Value=(negative?'-':'')+whole+(fraction?'.'+fraction:'');}toString(){return this.Value;}}
/** Raw DateTime ticks and the two kind bits, including local-ambiguous state. */
export class NrbfDateTime {constructor(data){this.Data=BigInt(data);if(this.Data<0n||this.Data>0xffffffffffffffffn)throw new RangeError('DateTime data');}get Ticks(){return this.Data&0x3fffffffffffffffn;}get Kind(){return Number(this.Data>>62n);}}
export class NrbfClass {
  constructor(typeName,members={},memberTypes={},libraryName=null){if(typeof typeName!=='string'||!typeName)throw new TypeError('typeName');this.TypeName=typeName;this.LibraryName=libraryName;this.Members=Object.assign(Object.create(null),members);this.MemberTypes=Object.assign(Object.create(null),memberTypes);}
}
export class NrbfArray {
  constructor(values=[],options={}){this.Values=Array.from(values);this.Lengths=options.lengths?Array.from(options.lengths):[this.Values.length];this.LowerBounds=options.lowerBounds?Array.from(options.lowerBounds):this.Lengths.map(()=>0);this.ArrayType=options.arrayType??(this.Lengths.length>1?2:0);this.ElementType=options.elementType??{type:B.Object};if(this.Lengths.length<1||this.Lengths.length!==this.LowerBounds.length||this.Lengths.some(n=>!Number.isSafeInteger(n)||n<0)||this.LowerBounds.some(n=>!Number.isInteger(n))||this.Lengths.reduce((a,b)=>a*b,1)!==this.Values.length)throw new RangeError('Invalid array shape');}
  GetValue(...indices){if(indices.length!==this.Lengths.length)throw new RangeError('Array rank');let offset=0;for(let i=0;i<indices.length;i++){const n=indices[i]-this.LowerBounds[i];if(!Number.isInteger(n)||n<0||n>=this.Lengths[i])throw new RangeError('Array index');offset=offset*this.Lengths[i]+n;}return this.Values[offset];}
  [Symbol.iterator](){return this.Values[Symbol.iterator]();}
}
export class NrbfDocument {constructor(root,objects=new Map(),libraries=new Map()){this.Root=root;this.Objects=objects;this.Libraries=libraries;}}
class Ref {constructor(id){this.id=id;}}
class NullRun {constructor(count){this.count=count;}}
class Reader {
  constructor(bytes,options){if(bytes instanceof ArrayBuffer)bytes=new Uint8Array(bytes);if(!ArrayBuffer.isView(bytes))throw new TypeError('Expected binary bytes');this.bytes=new Uint8Array(bytes.buffer,bytes.byteOffset,bytes.byteLength);this.view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);this.pos=0;this.options=checkedLimits({maxBytes:64*1024*1024,maxObjects:1000000,maxArrayLength:10000000,maxTotalArrayLength:10000000,maxStringBytes:16*1024*1024,maxMembers:100000,maxDepth:256,...options});if(this.bytes.length>this.options.maxBytes)fail('Byte limit exceeded');this.objects=new Map();this.libraries=new Map();this.metadata=new Map();this.refs=[];this.depth=0;this.records=0;this.totalArrayLength=0;}
  need(n){if(!Number.isSafeInteger(n)||n<0||this.pos+n>this.bytes.length)fail(`Truncated NRBF record at byte ${this.pos}`);}
  u8(){this.need(1);return this.bytes[this.pos++];}
  num(method,n){this.need(n);const v=this.view[method](this.pos,true);this.pos+=n;return v;}
  i32(){return this.num('getInt32',4);}
  string(){let size=0,shift=0;for(let i=0;i<5;i++){const b=this.u8();if(i===4&&b>7)fail('Invalid string length');size+=(b&127)*2**shift;if(!(b&128)){if(size>this.options.maxStringBytes)fail('String limit exceeded');this.need(size);let result;try{result=decoder.decode(this.bytes.subarray(this.pos,this.pos+size));}catch{fail('Invalid UTF-8');}this.pos+=size;return result;}shift+=7;}fail('Invalid string length');}
  count(n,max=this.options.maxArrayLength){if(n<0||n>max)fail('Count limit exceeded');return n;}
  register(id,value){if(!Number.isInteger(id)||id===0||this.objects.has(id))fail(`Duplicate or invalid object ID ${id}`);if(this.objects.size>=this.options.maxObjects)fail('Object limit exceeded');this.objects.set(id,value);return value;}
  primitive(type){if(!primitiveTypes.has(type))fail(`Unknown primitive type ${type}`);switch(type){case P.Boolean:{const n=this.u8();if(n>1)fail('Invalid Boolean');return n===1;}case P.Byte:return this.u8();case P.Char:{const start=this.pos,first=this.u8(),n=first<128?1:first>=0xc2&&first<=0xdf?2:first>=0xe0&&first<=0xef?3:0;if(!n)fail('Invalid UTF-8 Char');this.need(n-1);this.pos+=n-1;try{const s=decoder.decode(this.bytes.subarray(start,this.pos));if(s.length!==1)fail('Invalid Char');return s;}catch{fail('Invalid UTF-8 Char');}break;}case P.Decimal:{const text=this.string();try{return new NrbfDecimal(text);}catch{fail('Invalid Decimal value');}break;}case P.Double:return this.num('getFloat64',8);case P.Int16:return this.num('getInt16',2);case P.Int32:return this.i32();case P.Int64:case P.TimeSpan:return this.num('getBigInt64',8);case P.SByte:return this.num('getInt8',1);case P.Single:return this.num('getFloat32',4);case P.DateTime:return new NrbfDateTime(this.num('getBigUint64',8));case P.UInt16:return this.num('getUint16',2);case P.UInt32:return this.num('getUint32',4);case P.UInt64:return this.num('getBigUint64',8);case P.Null:return null;case P.String:return this.string();}}
  type(type){if(type<0||type>7)fail(`Unknown binary type ${type}`);if(type===B.Primitive||type===B.PrimitiveArray){const primitive=this.u8();if(!primitiveTypes.has(primitive)||primitive>=P.Null)fail('Invalid primitive metadata');return {type,primitive};}if(type===B.SystemClass)return {type,name:this.string()};if(type===B.Class){const name=this.string(),libraryId=this.i32();if(!this.libraries.has(libraryId))fail('Unknown library reference');return {type,name,library:this.libraries.get(libraryId)};}return {type};}
  value(){for(;;){const result=this.record();if(result!==undefined)return result;}}
  record(){if(++this.records>this.options.maxObjects*8)fail('Record limit exceeded');if(++this.depth>this.options.maxDepth)fail('Nesting limit exceeded');try{const kind=this.u8();switch(kind){case 1:{const id=this.i32(),metadataId=this.i32(),m=this.metadata.get(metadataId);if(!m)fail('Unknown class metadata reference');return this.classValue(id,m);}case 2:case 3:case 4:case 5:{const id=this.i32(),name=this.string(),n=this.count(this.i32(),this.options.maxMembers),names=[];for(let i=0;i<n;i++)names.push(this.string());if(new Set(names).size!==names.length)fail('Duplicate member names');let types;if(kind>=4){const tags=Array.from({length:n},()=>this.u8());types=tags.map(t=>this.type(t));}else {const resolver=this.options.resolveMemberTypes;if(!resolver)fail('Untyped class metadata requires resolveMemberTypes');types=resolver(name,names);if(!Array.isArray(types)||types.length!==n)fail('Invalid resolved member metadata');}let library=null;if(kind===3||kind===5){const libraryId=this.i32();if(!this.libraries.has(libraryId))fail('Unknown class library');library=this.libraries.get(libraryId);}const m={name,names,types,library};this.metadata.set(id,m);return this.classValue(id,m);}case 6:{const id=this.i32();return this.register(id,this.string());}case 7:{const id=this.i32(),arrayType=this.u8();if(arrayType>5)fail('Invalid BinaryArray type');const rank=this.count(this.i32(),32);if(rank<1||(arrayType%3!==2&&rank!==1))fail('Invalid BinaryArray rank');const lengths=Array.from({length:rank},()=>this.count(this.i32()));let count=1;for(const n of lengths){count*=n;this.count(count);}const lowerBounds=arrayType>=3?Array.from({length:rank},()=>this.i32()):lengths.map(()=>0);const type=this.type(this.u8());return this.arrayValue(id,count,{lengths,lowerBounds,arrayType,elementType:type});}case 8:{const t=this.u8();if(t>=P.Null)fail('Invalid boxed primitive type');return new NrbfPrimitive(t,this.primitive(t));}case 9:{const ref=new Ref(this.i32());this.refs.push(ref);return ref;}case 10:return null;case 12:{const id=this.i32(),name=this.string();if(id<=0||this.libraries.has(id))fail('Duplicate or invalid library ID');this.libraries.set(id,name);return undefined;}case 13:return new NullRun(this.count(this.u8()));case 14:return new NullRun(this.count(this.i32()));case 15:{const id=this.i32(),n=this.count(this.i32()),primitive=this.u8();if(!primitiveTypes.has(primitive)||primitive>=P.Null)fail('Invalid array primitive');return this.arrayValue(id,n,{elementType:{type:B.Primitive,primitive}});}case 16:case 17:{const id=this.i32(),n=this.count(this.i32());return this.arrayValue(id,n,{elementType:{type:kind===16?B.Object:B.String}});}case 21:case 22:fail('Remoting method invocation records are not object graph data');default:fail(`Unexpected record type ${kind} at byte ${this.pos-1}`);}}finally{this.depth--;}}
  classValue(id,m){const result=this.register(id,new NrbfClass(m.name,{},Object.fromEntries(m.names.map((n,i)=>[n,m.types[i]])),m.library));result.IsValueType=id<0;for(let i=0;i<m.names.length;i++){const v=m.types[i].type===B.Primitive?this.primitive(m.types[i].primitive):this.value();if(v instanceof NullRun)fail('Null run outside an array');result.Members[m.names[i]]=v;}return result;}
  arrayValue(id,n,options){if(n>this.options.maxTotalArrayLength-this.totalArrayLength)fail('Total array length limit exceeded');this.totalArrayLength+=n;const result=this.register(id,Object.create(NrbfArray.prototype));result.Values=[];result.Lengths=options.lengths??[n];result.LowerBounds=options.lowerBounds??[0];result.ArrayType=options.arrayType??0;result.ElementType=options.elementType;while(result.Values.length<n){const v=result.ElementType.type===B.Primitive?this.primitive(result.ElementType.primitive):this.value();if(v instanceof NullRun){if(v.count===0||v.count>n-result.Values.length)fail('Invalid null run length');for(let j=0;j<v.count;j++)result.Values.push(null);}else result.Values.push(v);}return result;}
  read(){if(this.u8()!==0)fail('Missing SerializationHeaderRecord');const rootId=this.i32();this.i32();if(this.i32()!==1||this.i32()!==0)fail('Unsupported NRBF version');while(this.pos<this.bytes.length&&this.bytes[this.pos]!==11){const item=this.record();if(item instanceof NullRun)fail('Null run outside an array');}if(this.u8()!==11)fail('Missing MessageEnd');if(this.pos!==this.bytes.length&&!this.options.allowTrailingBytes)fail('Trailing bytes after MessageEnd');if(!this.objects.has(rootId))fail('Root object not found');for(const ref of this.refs)if(!this.objects.has(ref.id))fail(`Unresolved object reference ${ref.id}`);for(const v of this.objects.values()){const container=v instanceof NrbfClass?v.Members:v instanceof NrbfArray?v.Values:null;if(container)for(const key of Object.keys(container))if(container[key] instanceof Ref)container[key]=this.objects.get(container[key].id);}return new NrbfDocument(this.objects.get(rootId),this.objects,this.libraries);}
}
/** Parse without loading assemblies, invoking constructors, or evaluating payload code. */
export function DecodeNrbf(bytes,options={}){return new Reader(bytes,options).read();}
class Writer {
 constructor(options={}){this.bytes=new Uint8Array(1024);this.pos=0;this.objects=new Map();this.libraries=new Map();this.metadata=new Map();this.pending=[];this.options=checkedLimits({maxBytes:64*1024*1024,maxDepth:256,...options});this.depth=0;this.nextId=1;}
 need(n){if(this.pos+n>this.options.maxBytes)throw new RangeError('NRBF output byte limit exceeded');if(this.pos+n>this.bytes.length){const grown=new Uint8Array(Math.max(this.pos+n,this.bytes.length*2));grown.set(this.bytes);this.bytes=grown;}}
 u8(n){this.need(1);this.bytes[this.pos++]=n;}
 num(method,n,value){this.need(n);new DataView(this.bytes.buffer)[method](this.pos,value,true);this.pos+=n;}
 i32(n){this.num('setInt32',4,n);}
 string(s){const bytes=utf8.encode(String(s));let n=bytes.length;while(n>=128){this.u8((n&127)|128);n>>>=7;}this.u8(n);this.need(bytes.length);this.bytes.set(bytes,this.pos);this.pos+=bytes.length;}
 primitive(type,value){switch(type){case P.Boolean:if(typeof value!=='boolean')throw new TypeError('Boolean primitive');this.u8(value?1:0);break;case P.Byte:this.integer('setUint8',1,value,0,255);break;case P.Char:{if(typeof value!=='string'||value.length!==1||/^[\uD800-\uDFFF]$/.test(value))throw new TypeError('Char primitive');const bytes=utf8.encode(value);this.need(bytes.length);this.bytes.set(bytes,this.pos);this.pos+=bytes.length;break;}case P.Decimal:this.string(value instanceof NrbfDecimal?value.Value:new NrbfDecimal(value).Value);break;case P.Double:this.num('setFloat64',8,Number(value));break;case P.Int16:this.integer('setInt16',2,value,-32768,32767);break;case P.Int32:this.integer('setInt32',4,value,-2147483648,2147483647);break;case P.Int64:case P.TimeSpan:{const n=BigInt(value);if(n<-(1n<<63n)||n>=(1n<<63n))throw new RangeError('Int64 primitive');this.num('setBigInt64',8,n);break;}case P.SByte:this.integer('setInt8',1,value,-128,127);break;case P.Single:this.num('setFloat32',4,Number(value));break;case P.DateTime:this.num('setBigUint64',8,value instanceof NrbfDateTime?value.Data:new NrbfDateTime(value).Data);break;case P.UInt16:this.integer('setUint16',2,value,0,65535);break;case P.UInt32:this.integer('setUint32',4,value,0,4294967295);break;case P.UInt64:{const n=BigInt(value);if(n<0n||n>=(1n<<64n))throw new RangeError('UInt64 primitive');this.num('setBigUint64',8,n);break;}default:throw new TypeError(`Unsupported primitive ${type}`);}}
 integer(method,size,value,min,max){if(!Number.isInteger(value)||value<min||value>max)throw new RangeError('Integer primitive');this.num(method,size,value);}
 type(type){if(type.type===B.Primitive||type.type===B.PrimitiveArray){if(!primitiveTypes.has(type.primitive)||type.primitive>=P.Null)throw new TypeError('Invalid primitive metadata');this.u8(type.primitive);}else if(type.type===B.SystemClass)this.string(type.name);else if(type.type===B.Class){this.string(type.name);if(!this.libraries.has(type.library))throw new TypeError('Unknown library');this.i32(this.libraries.get(type.library));}else if(type.type<0||type.type>7)throw new TypeError('Invalid member type');}
 collect(root){const pending=[root],seen=new Set();while(pending.length){const v=pending.pop();if(!v||typeof v!=='object'||seen.has(v))continue;seen.add(v);const add=library=>{if(library&&!this.libraries.has(library))this.libraries.set(library,this.libraries.size+1);};if(v instanceof NrbfClass){add(v.LibraryName);for(const t of Object.values(v.MemberTypes))add(t.library);for(const member of Object.values(v.Members))pending.push(member);}else if(v instanceof NrbfArray){add(v.ElementType.library);for(const item of v.Values)pending.push(item);}else if(Array.isArray(v)){for(const item of v)pending.push(item);}else if(!(v instanceof NrbfPrimitive)&&!(v instanceof NrbfDecimal)&&!(v instanceof NrbfDateTime)&&!ArrayBuffer.isView(v))throw new TypeError('Unregistered object: encode an NrbfClass or register a CLR schema');}}
 value(value,forceRecord=false){if(++this.depth>this.options.maxDepth)throw new RangeError('NRBF output nesting limit exceeded');try{if(value instanceof NrbfPrimitive){this.u8(8);this.u8(value.Type);this.primitive(value.Type,value.Value);return;}if(value===null||value===undefined){this.u8(10);return;}if(typeof value==='number'||typeof value==='boolean'||typeof value==='bigint'||value instanceof NrbfDecimal||value instanceof NrbfDateTime){const p=inferPrimitive(value);this.u8(8);this.u8(p);this.primitive(p,value);return;}if(this.objects.has(value)&&!forceRecord){this.u8(9);this.i32(this.objects.get(value));return;}let id=this.objects.get(value);if(id===undefined){id=this.nextId++;if(value instanceof NrbfClass&&value.IsValueType&&this.depth>1)id=-id;this.objects.set(value,id);}if(!forceRecord&&typeof value!=='string'&&!(value instanceof NrbfClass&&value.IsValueType)){this.pending.push(value);this.u8(9);this.i32(id);return;}if(typeof value==='string'){this.u8(6);this.i32(id);this.string(value);return;}if(value instanceof NrbfClass){const names=Object.keys(value.Members),types=names.map(n=>value.MemberTypes[n]??inferType(value.Members[n]));const key=JSON.stringify([value.TypeName,value.LibraryName,names,types]);if(this.metadata.has(key)){this.u8(1);this.i32(id);this.i32(this.metadata.get(key));}else{this.metadata.set(key,id);this.u8(value.LibraryName?5:4);this.i32(id);this.string(value.TypeName);this.i32(names.length);for(const n of names)this.string(n);for(const t of types)this.u8(t.type);for(const t of types)this.type(t);if(value.LibraryName)this.i32(this.libraries.get(value.LibraryName));}for(let i=0;i<names.length;i++){if(types[i].type===B.Primitive)this.primitive(types[i].primitive,value.Members[names[i]]);else this.value(value.Members[names[i]]);}return;}let array=value;if(ArrayBuffer.isView(value))array=typedArray(value);else if(Array.isArray(value))array=new NrbfArray(value);if(!(array instanceof NrbfArray))throw new TypeError('Unsupported NRBF value');const {Values:values,ElementType:type,Lengths:lengths,LowerBounds:bounds}=array;const simple=lengths.length===1&&bounds[0]===0&&array.ArrayType===0;if(simple&&[B.Primitive,B.Object,B.String].includes(type.type)){this.u8(type.type===B.Primitive?15:type.type===B.Object?16:17);this.i32(id);this.i32(values.length);if(type.type===B.Primitive)this.u8(type.primitive);}else{this.u8(7);this.i32(id);const arrayType=bounds.some(n=>n!==0)?(array.ArrayType%3)+3:array.ArrayType;this.u8(arrayType);this.i32(lengths.length);for(const n of lengths)this.i32(n);if(arrayType>=3)for(const n of bounds)this.i32(n);this.u8(type.type);this.type(type);}for(let i=0;i<values.length;i++){if(type.type===B.Primitive)this.primitive(type.primitive,values[i]);else if(values[i]==null){let end=i+1;while(simple&&end<values.length&&values[end]==null)end++;const n=end-i;if(n===1)this.u8(10);else if(n<=255){this.u8(13);this.u8(n);}else{this.u8(14);this.i32(n);}i=end-1;}else this.value(values[i]);}}finally{this.depth--;}}
 write(root){if(root instanceof NrbfDocument)root=root.Root;if(root===null||root===undefined)throw new TypeError('NRBF root cannot be null');if(root instanceof NrbfPrimitive)root=boxedRecord(root.Type,root.Value);else if(root instanceof NrbfDecimal)root=boxedRecord(P.Decimal,root);else if(root instanceof NrbfDateTime)root=boxedRecord(P.DateTime,root);if(['number','boolean','bigint'].includes(typeof root)){const p=inferPrimitive(root),name=Object.keys(P).find(k=>P[k]===p);root=new NrbfClass('System.'+name,{m_value:root},{m_value:{type:B.Primitive,primitive:p}});}this.collect(root);this.u8(0);this.i32(1);this.i32(-1);this.i32(1);this.i32(0);for(const [name,id] of this.libraries){this.u8(12);this.i32(id);this.string(name);}this.value(root,true);for(let i=0;i<this.pending.length;i++)this.value(this.pending[i],true);this.u8(11);return this.bytes.slice(0,this.pos);}
}
function boxedRecord(type,value){const p=primitive=>({type:B.Primitive,primitive});if(type===P.Decimal){const decimal=value instanceof NrbfDecimal?value:new NrbfDecimal(value),negative=decimal.Value.startsWith('-'),[whole,fraction='']=decimal.Value.replace(/^-/,'').split('.'),coefficient=BigInt(whole+fraction),members={flags:((negative?0x80000000:0)|(fraction.length<<16))|0,hi:Number(coefficient>>64n)|0,lo:Number(coefficient&0xffffffffn)|0,mid:Number((coefficient>>32n)&0xffffffffn)|0};return new NrbfClass('System.Decimal',members,Object.fromEntries(Object.keys(members).map(k=>[k,p(P.Int32)])));}if(type===P.DateTime){const date=value instanceof NrbfDateTime?value:new NrbfDateTime(value);return new NrbfClass('System.DateTime',{ticks:date.Ticks,dateData:date.Data},{ticks:p(P.Int64),dateData:p(P.UInt64)});}if(type===P.TimeSpan)return new NrbfClass('System.TimeSpan',{_ticks:BigInt(value)},{_ticks:p(P.Int64)});const name=Object.keys(P).find(k=>P[k]===type);if(!name||type>=P.Null)throw new TypeError('Invalid root primitive');return new NrbfClass('System.'+name,{m_value:value},{m_value:p(type)});}
function inferPrimitive(value){if(typeof value==='boolean')return P.Boolean;if(typeof value==='bigint')return value<0n?P.Int64:value>(1n<<63n)-1n?P.UInt64:P.Int64;if(value instanceof NrbfDecimal)return P.Decimal;if(value instanceof NrbfDateTime)return P.DateTime;return Number.isInteger(value)&&value>=-2147483648&&value<=2147483647?P.Int32:P.Double;}
function inferType(v){return typeof v==='number'||typeof v==='boolean'||typeof v==='bigint'||v instanceof NrbfDecimal||v instanceof NrbfDateTime?{type:B.Primitive,primitive:inferPrimitive(v)}:typeof v==='string'?{type:B.String}:{type:B.Object};}
function typedArray(value){const names={Int8Array:P.SByte,Uint8Array:P.Byte,Uint8ClampedArray:P.Byte,Int16Array:P.Int16,Uint16Array:P.UInt16,Int32Array:P.Int32,Uint32Array:P.UInt32,Float32Array:P.Single,Float64Array:P.Double,BigInt64Array:P.Int64,BigUint64Array:P.UInt64};const primitive=names[value.constructor.name];if(!primitive)throw new TypeError('Unsupported typed array');return new NrbfArray(value,{elementType:{type:B.Primitive,primitive}});}
export function EncodeNrbf(value,options={}){return new Writer(options).write(value);}
/** Explicit schema registry: matching names never invokes a CLR constructor. */
export class NrbfTypeRegistry {
 constructor(){this.Types=new Map();}
 Register(typeName,schema){if(typeof typeName!=='string'||!schema||typeof schema.create!=='function'||typeof schema.populate!=='function')throw new TypeError('A schema needs create and populate callbacks');this.Types.set(typeName,schema);return this;}
 Materialize(document,options={}){const root=document instanceof NrbfDocument?document.Root:document,memo=new Map(),pending=[];const allocate=value=>{if(!value||typeof value!=='object'||value instanceof NrbfDecimal||value instanceof NrbfDateTime||value instanceof NrbfPrimitive)return value;if(memo.has(value))return memo.get(value);let target,schema;if(value instanceof NrbfClass){schema=this.Types.get(value.TypeName)??options.resolveType?.(value.TypeName,value.LibraryName);if(!schema){if(options.allowUnknownTypes)target=new NrbfClass(value.TypeName,{},value.MemberTypes,value.LibraryName);else throw new TypeError(`Unregistered NRBF class ${value.TypeName}`);}else target=schema.create(value);}else if(value instanceof NrbfArray)target=[];else throw new TypeError('Invalid NRBF value');if(!target||typeof target!=='object')throw new TypeError('Schema create must return an object');memo.set(value,target);pending.push({value,target,schema});return target;};const result=allocate(root);for(let i=0;i<pending.length;i++){const {value}=pending[i];for(const item of value instanceof NrbfClass?Object.values(value.Members):value.Values)allocate(item);}for(const {value,target,schema} of pending){if(value instanceof NrbfArray){for(const item of value.Values)target.push(allocate(item));Object.defineProperty(target,'NrbfShape',{value:{lengths:value.Lengths,lowerBounds:value.LowerBounds,arrayType:value.ArrayType},enumerable:false});}else{const members=Object.fromEntries(Object.entries(value.Members).map(([name,v])=>[name,allocate(v)]));if(schema)schema.populate(target,members,value);else Object.assign(target.Members,members);}}return result;}
}
/** Adapter accepted by QuikGraph's existing binary stream extension methods. */
export class NrbfFormatter {
 constructor(options={}){this.Options=options;this.Registry=options.registry??null;}
 Serialize(value,stream){const raw=this.Options.toRecord?this.Options.toRecord(value):value,bytes=EncodeNrbf(raw,this.Options);if(stream===undefined)return bytes;if(stream===null||stream.CanWrite===false)throw new TypeError('Stream must be writable');if(typeof stream.Write==='function'){stream.Write(bytes,0,bytes.length);return bytes;}if(typeof stream.write==='function'){stream.write(bytes);return bytes;}throw new TypeError('Stream needs Write or write');}
 Deserialize(stream){let bytes=stream;if(stream?.CanRead===false)throw new TypeError('Stream must be readable');if(typeof stream?.ToArray==='function')bytes=stream.ToArray();else if(typeof stream?.read==='function')bytes=stream.read();const document=DecodeNrbf(bytes,this.Options);return this.Registry?this.Registry.Materialize(document,this.Options):document.Root;}
}
